/**
 * Comprehensive Parser Unit Tests — Q2 (Stream Q Sprint 1)
 *
 * These tests cover format detection nuances, format-specific version
 * variations, edge cases (BOM, CRLF, truncated lines, duplicates,
 * non-standard chromosomes), VCF advanced scenarios, streaming
 * (iterateLines-level) behavior, and performance.
 *
 * Each test is self-contained with inline fixture data. No external
 * files or synthetic factories are used.
 *
 * Test groups:
 *  1. Parser — Format Detection (version headers, heuristic edge cases)
 *  2. Parser — 23andMe (v3/v4/v5 headers, version variations)
 *  3. Parser — AncestryDNA (v1/v2, chromosome codes, allele edge cases)
 *  4. Parser — MyHeritage (CSV quoting, mixed-case header, VG prefix variations)
 *  5. Parser — VCF (advanced: half-call, out-of-bounds index, invalid allele, long indel)
 *  6. Parser — Edge Cases (BOM, CRLF/LF, truncated last line, duplicates, empty)
 *  7. Parser — Streaming (iterateLines behavior exercised through parse functions)
 *  8. Parser — Performance (10K-line file under 1 second)
 */

import { describe, it, expect } from 'vitest';
import {
  detectFormat,
  parse23andMe,
  parseAncestryDNA,
  parseMyHeritage,
  parseVcf,
  parseGeneticFile,
  getGenotypeStats,
  detectChipVersion,
  buildParseResultSummary,
} from '../src/parser';

// ─── 1. Parser — Format Detection ────────────────────────────────────────────
//
// Tests format detection across header variations, heuristic fallback,
// 23andMe version-specific comment lines, and VCF alternatives.

describe('Parser — Format Detection', () => {
  // ── 23andMe version-specific comment headers ──────────────────────────────

  it('detects 23andMe v3 from comment containing "23andMe" + build 37', () => {
    // 23andMe v3 files (OmniExpress Plus) often include build number in comments.
    const content = [
      '# This data file generated by 23andMe',
      '# Below is a text version of your data.  Fields are TAB-separated',
      '# Build: 37',
      '# rsid\tchromosome\tposition\tgenotype',
      'rs4477212\t1\t82154\tAA',
    ].join('\n');
    expect(detectFormat(content)).toBe('23andme');
  });

  it('detects 23andMe v4 from comment containing "23andMe" and standard columns', () => {
    // v4 files have the same comment structure as v3.
    // Detection relies on the "23andme" keyword in the comment.
    const content = [
      '# This data file generated by 23andMe at: Sat May 01 2021',
      '# Genome Build: 37',
      '# rsid\tchromosome\tposition\tgenotype',
      'rs3094315\t1\t752566\tAG',
    ].join('\n');
    expect(detectFormat(content)).toBe('23andme');
  });

  it('detects 23andMe v5 from comment containing "23andMe" GSA chip note', () => {
    // v5 (GSA) files still have "23andMe" in the comment header.
    const content = [
      '# This data file was generated by 23andMe',
      '# Genome Build 37 SNP data - Illumina GSA chip',
      '# rsid\tchromosome\tposition\tgenotype',
      'rs548049170\t1\t100000\tAA',
    ].join('\n');
    expect(detectFormat(content)).toBe('23andme');
  });

  it('detects AncestryDNA v1 from comment "AncestryDNA" keyword', () => {
    // v1 (OmniExpress) files: comment with "AncestryDNA", 5-col tab format.
    const content = [
      '#AncestryDNA raw data download',
      'rsid\tchromosome\tposition\tallele1\tallele2',
      'rs4477212\t1\t82154\tA\tA',
    ].join('\n');
    expect(detectFormat(content)).toBe('ancestrydna');
  });

  it('detects AncestryDNA v2 from comment "AncestryDNA" keyword', () => {
    // v2 (GSA) files have the same comment structure.
    const content = [
      '#AncestryDNA',
      '#This file was generated by AncestryDNA at: 2022-01-01',
      'rsid\tchromosome\tposition\tallele1\tallele2',
      'rs548049170\t1\t100000\tA\tG',
    ].join('\n');
    expect(detectFormat(content)).toBe('ancestrydna');
  });

  it('detects AncestryDNA from 5-column tab header with allele1/allele2 (no keyword)', () => {
    // AncestryDNA heuristic: 5-column header with "allele1" and "allele2".
    const content = [
      'rsid\tchromosome\tposition\tallele1\tallele2',
      'rs4477212\t1\t82154\tA\tA',
      'rs3094315\t1\t752566\tA\tG',
    ].join('\n');
    expect(detectFormat(content)).toBe('ancestrydna');
  });

  it('detects MyHeritage from CSV header RSID,CHROMOSOME,POSITION,RESULT', () => {
    // MyHeritage: CSV with explicit column names.
    const content = ['RSID,CHROMOSOME,POSITION,RESULT', 'rs4477212,1,82154,AA'].join('\n');
    expect(detectFormat(content)).toBe('myheritage');
  });

  it('detects MyHeritage from lowercase CSV header (case-insensitive match)', () => {
    // The parser lowercases for comparison — lowercase header should still match.
    const content = ['rsid,chromosome,position,result', 'rs4477212,1,82154,AA'].join('\n');
    expect(detectFormat(content)).toBe('myheritage');
  });

  it('detects VCF from ##fileformat=VCFv4.2', () => {
    // Any VCF version number should trigger VCF detection.
    const content = [
      '##fileformat=VCFv4.2',
      '#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\tFORMAT\tS1',
      '1\t100\trs1\tA\tG\t.\tPASS\t.\tGT\t0/1',
    ].join('\n');
    expect(detectFormat(content)).toBe('vcf');
  });

  it('detects VCF from ##fileformat=VCFv4.3', () => {
    const content = [
      '##fileformat=VCFv4.3',
      '#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\tFORMAT\tS1',
      '1\t100\trs1\tA\tG\t.\tPASS\t.\tGT\t0/1',
    ].join('\n');
    expect(detectFormat(content)).toBe('vcf');
  });

  it('detects VCF from ## meta-lines + #CHROM (no ##fileformat line)', () => {
    // VCF heuristic: ## meta-line followed by #CHROM header.
    const content = [
      '##source=SomeApp',
      '##reference=GRCh37',
      '#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\tFORMAT\tS1',
      '1\t100\trs1\tA\tG\t.\tPASS\t.\tGT\t0/1',
    ].join('\n');
    expect(detectFormat(content)).toBe('vcf');
  });

  it('returns "unknown" for empty string', () => {
    expect(detectFormat('')).toBe('unknown');
  });

  it('returns "unknown" for whitespace-only content', () => {
    expect(detectFormat('   \n   \n   ')).toBe('unknown');
  });

  it('returns "unknown" for plain prose text', () => {
    expect(detectFormat('This is not a genetic data file. It contains only prose.')).toBe(
      'unknown',
    );
  });

  it('returns "unknown" for content with 4 columns but non-rs IDs (no clear format)', () => {
    // 4-column but IDs don't start with rs or i => not 23andMe heuristic
    const content = ['GENE001\t1\t100\tAA', 'GENE002\t1\t200\tAG', 'GENE003\t1\t300\tGG'].join(
      '\n',
    );
    expect(detectFormat(content)).toBe('unknown');
  });

  it('returns "unknown" for 3-column tab-separated data (ambiguous)', () => {
    const content = ['rs4477212\t1\tAA', 'rs3094315\t1\tAG'].join('\n');
    expect(detectFormat(content)).toBe('unknown');
  });
});

// ─── 2. Parser — 23andMe ─────────────────────────────────────────────────────
//
// Tests v3/v4/v5 header text differences, specific data format variations,
// indel notation, chromosome handling, and rsID prefix filtering.

describe('Parser — 23andMe', () => {
  // ── v3 format (OmniExpress Plus, ~960K SNPs) ──────────────────────────────

  it('parses v3 format: standard header with build 37 comment', () => {
    // v3 files have 4-column tab-separated format with build number in comments.
    const content = [
      '# This data file generated by 23andMe at: Mon Jan 01 2024',
      '# Below is a tab-separated file of your raw SNP data.',
      '# Build: 37',
      '# rsid\tchromosome\tposition\tgenotype',
      'rs4477212\t1\t82154\tAA',
      'rs3094315\t1\t752566\tAG',
      'rs3131972\t1\t752721\tGG',
    ].join('\n');
    const result = parse23andMe(content);
    expect(result['rs4477212']).toBe('AA');
    expect(result['rs3094315']).toBe('AG');
    expect(result['rs3131972']).toBe('GG');
    expect(Object.keys(result)).toHaveLength(3);
  });

  it('parses v4 format: same structure as v3 but with different SNPs', () => {
    // v4 header is identical in structure to v3.
    const content = [
      '# This data file generated by 23andMe at: Fri Mar 15 2019',
      '# rsid\tchromosome\tposition\tgenotype',
      'rs4477212\t1\t82154\tAA',
      'rs3094315\t1\t752566\tAG',
    ].join('\n');
    const result = parse23andMe(content);
    expect(result['rs4477212']).toBe('AA');
    expect(result['rs3094315']).toBe('AG');
    expect(Object.keys(result)).toHaveLength(2);
  });

  it('parses v5 format: GSA chip marker SNPs present', () => {
    // v5 (GSA chip) marker SNPs: rs548049170, rs13354714, rs2298108.
    const content = [
      '# This data file generated by 23andMe',
      '# rsid\tchromosome\tposition\tgenotype',
      'rs548049170\t1\t100000\tAA',
      'rs13354714\t2\t200000\tCC',
      'rs2298108\t3\t300000\tAG',
      'rs4477212\t1\t82154\tAA',
    ].join('\n');
    const result = parse23andMe(content);
    expect(result['rs548049170']).toBe('AA');
    expect(result['rs13354714']).toBe('CC');
    expect(result['rs2298108']).toBe('AG');
    expect(result['rs4477212']).toBe('AA');
    expect(Object.keys(result)).toHaveLength(4);
  });

  it('parses 23andMe files without any comment header lines', () => {
    // Some exports omit all comment lines. Parser relies on column count heuristic.
    const content = [
      'rs4477212\t1\t82154\tAA',
      'rs3094315\t1\t752566\tAG',
      'rs3131972\t1\t752721\tGG',
    ].join('\n');
    const result = parse23andMe(content);
    expect(result['rs4477212']).toBe('AA');
    expect(result['rs3094315']).toBe('AG');
    expect(result['rs3131972']).toBe('GG');
  });

  it('correctly extracts rsID (col 0), chromosome (col 1), position (col 2), genotype (col 3)', () => {
    // Confirms that column order: rsid, chr, pos, genotype is correctly parsed.
    const content = ['# 23andMe test', 'rs9999999\t22\t51244106\tCT'].join('\n');
    const result = parse23andMe(content);
    // Only the rsID and genotype are stored — chromosome and position are not in GenotypeMap.
    expect(result['rs9999999']).toBe('CT');
  });

  it('skips lines where genotype is "--" (no-call)', () => {
    const content = ['# 23andMe', 'rs4477212\t1\t82154\tAA', 'rs3094315\t1\t752566\t--'].join('\n');
    const result = parse23andMe(content);
    expect(result['rs3094315']).toBeUndefined();
    expect(Object.keys(result)).toHaveLength(1);
  });

  it('skips lines where genotype is empty string (no-call variant)', () => {
    // Some files have trailing tab with no genotype value.
    const content = ['# 23andMe', 'rs4477212\t1\t82154\tAA', 'rs3094315\t1\t752566\t'].join('\n');
    const result = parse23andMe(content);
    expect(result['rs3094315']).toBeUndefined();
  });

  it('handles i-prefixed indel rsIDs (present in 23andMe files)', () => {
    // 23andMe uses "i" prefix for proprietary indel IDs.
    const content = ['# 23andMe', 'i713426\t1\t817186\tCC', 'i3000468\t1\t831489\tTT'].join('\n');
    const result = parse23andMe(content);
    expect(result['i713426']).toBe('CC');
    expect(result['i3000468']).toBe('TT');
  });

  it('handles hemizygous single-character genotypes (X/Y chromosomes in males)', () => {
    // Male X/Y chromosomes produce single-character genotypes (e.g., "A" not "AA").
    const content = [
      '# 23andMe',
      'rs4477212\t1\t82154\tAA',
      'rs700001\tX\t100000\tA',
      'rs700002\tY\t200000\tG',
    ].join('\n');
    const result = parse23andMe(content);
    expect(result['rs700001']).toBe('A');
    expect(result['rs700002']).toBe('G');
  });

  it('handles MT chromosome entries', () => {
    // Mitochondrial DNA uses "MT" chromosome designation in 23andMe.
    const content = ['# 23andMe', 'rs1234\tMT\t12345\tAA'].join('\n');
    const result = parse23andMe(content);
    expect(result['rs1234']).toBe('AA');
  });

  it('skips lines where rsID does not start with rs or i', () => {
    // Lines with non-standard ID prefixes are silently dropped.
    const content = [
      '# 23andMe',
      'rs4477212\t1\t82154\tAA',
      'GENE001\t1\t99999\tCC',
      'VG00001\t1\t88888\tTT',
    ].join('\n');
    const result = parse23andMe(content);
    // Only rs4477212 passes — VG and GENE prefixes are dropped.
    expect(Object.keys(result)).toHaveLength(1);
    expect(result['rs4477212']).toBe('AA');
  });

  it('handles whitespace-padded rsIDs and genotypes (trims correctly)', () => {
    // Some tools export files with extra whitespace in fields.
    const content = ['# 23andMe', 'rs4477212 \t1\t82154\t AA '].join('\n');
    const result = parse23andMe(content);
    expect(result['rs4477212']).toBe('AA');
  });

  it('parses large genotypes like "DDII" (indel notation)', () => {
    // 23andMe v3 encodes indels as D (deletion) / I (insertion) characters.
    // These are valid genotypes and should NOT be skipped.
    const content = [
      '# 23andMe',
      'rs3135027\t1\t900000\tDD',
      'rs3135028\t1\t900001\tII',
      'rs3135029\t1\t900002\tDI',
    ].join('\n');
    const result = parse23andMe(content);
    expect(result['rs3135027']).toBe('DD');
    expect(result['rs3135028']).toBe('II');
    expect(result['rs3135029']).toBe('DI');
  });

  it('throws error when content has only comment lines and no SNP data', () => {
    const content = [
      '# 23andMe raw data file',
      '# This file contains no data',
      '# rsid\tchromosome\tposition\tgenotype',
    ].join('\n');
    expect(() => parse23andMe(content)).toThrow('No valid SNP data found');
  });
});

// ─── 3. Parser — AncestryDNA ─────────────────────────────────────────────────
//
// Tests v1/v2 format differences, chromosome code variations (23/24/25),
// allele uppercase normalization, and no-call (0) handling.

describe('Parser — AncestryDNA', () => {
  // ── v1 format (OmniExpress, ~700K SNPs) ──────────────────────────────────

  it('parses v1 format: 5-column tab-separated with allele1/allele2 columns', () => {
    // AncestryDNA v1 format: rsid, chromosome, position, allele1, allele2
    const content = [
      '#AncestryDNA raw data download',
      '#This file was generated by AncestryDNA',
      'rsid\tchromosome\tposition\tallele1\tallele2',
      'rs4477212\t1\t82154\tA\tA',
      'rs3094315\t1\t752566\tA\tG',
      'rs3131972\t1\t752721\tG\tG',
    ].join('\n');
    const result = parseAncestryDNA(content);
    expect(result['rs4477212']).toBe('AA');
    expect(result['rs3094315']).toBe('AG');
    expect(result['rs3131972']).toBe('GG');
    expect(Object.keys(result)).toHaveLength(3);
  });

  it('parses v2 format: same structure as v1 with GSA marker SNPs', () => {
    // AncestryDNA v2 (GSA chip) marker SNPs: rs548049170, rs13354714.
    const content = [
      '#AncestryDNA',
      'rsid\tchromosome\tposition\tallele1\tallele2',
      'rs548049170\t1\t100000\tA\tG',
      'rs13354714\t2\t200000\tC\tT',
      'rs4477212\t1\t82154\tA\tA',
    ].join('\n');
    const result = parseAncestryDNA(content);
    expect(result['rs548049170']).toBe('AG');
    expect(result['rs13354714']).toBe('CT');
    expect(result['rs4477212']).toBe('AA');
    expect(Object.keys(result)).toHaveLength(3);
  });

  it('combines allele1 and allele2 into a concatenated genotype string', () => {
    // Core behavior: allele1="A" + allele2="G" => genotype="AG".
    const content = ['#AncestryDNA', 'rs4477212\t1\t82154\tA\tG'].join('\n');
    const result = parseAncestryDNA(content);
    expect(result['rs4477212']).toBe('AG');
  });

  it('uppercases lowercase allele values before concatenation', () => {
    // Some exports may provide lowercase alleles; parser normalizes to uppercase.
    const content = ['#AncestryDNA', 'rs4477212\t1\t82154\ta\tg'].join('\n');
    const result = parseAncestryDNA(content);
    expect(result['rs4477212']).toBe('AG');
  });

  it('skips entries where allele1 is "0" (no-call)', () => {
    const content = [
      '#AncestryDNA',
      'rs4477212\t1\t82154\tA\tA',
      'rs3094315\t1\t752566\t0\tA',
    ].join('\n');
    const result = parseAncestryDNA(content);
    expect(result['rs3094315']).toBeUndefined();
    expect(Object.keys(result)).toHaveLength(1);
  });

  it('skips entries where allele2 is "0" (no-call)', () => {
    const content = [
      '#AncestryDNA',
      'rs4477212\t1\t82154\tA\tA',
      'rs3094315\t1\t752566\tA\t0',
    ].join('\n');
    const result = parseAncestryDNA(content);
    expect(result['rs3094315']).toBeUndefined();
    expect(Object.keys(result)).toHaveLength(1);
  });

  it('handles chromosome code "23" (AncestryDNA encoding for X chromosome)', () => {
    // AncestryDNA uses numeric codes: 23=X, 24=Y, 25=MT/PAR.
    const content = ['#AncestryDNA', 'rs9999\t23\t100000\tA\tA'].join('\n');
    const result = parseAncestryDNA(content);
    // Parser does not filter by chromosome, so this should be parsed.
    expect(result['rs9999']).toBe('AA');
  });

  it('handles chromosome code "24" (AncestryDNA encoding for Y chromosome)', () => {
    const content = ['#AncestryDNA', 'rs9999\t24\t100000\tA\tA'].join('\n');
    const result = parseAncestryDNA(content);
    expect(result['rs9999']).toBe('AA');
  });

  it('handles chromosome code "25" (AncestryDNA encoding for MT/PAR region)', () => {
    const content = ['#AncestryDNA', 'rs9999\t25\t100000\tA\tA'].join('\n');
    const result = parseAncestryDNA(content);
    expect(result['rs9999']).toBe('AA');
  });

  it('handles i-prefixed rsIDs in AncestryDNA files', () => {
    const content = ['#AncestryDNA', 'i713426\t1\t817186\tC\tC'].join('\n');
    const result = parseAncestryDNA(content);
    expect(result['i713426']).toBe('CC');
  });

  it('skips rsIDs that do not start with rs or i', () => {
    const content = ['#AncestryDNA', 'rs4477212\t1\t82154\tA\tA', 'VG00001\t1\t99999\tA\tA'].join(
      '\n',
    );
    const result = parseAncestryDNA(content);
    expect(result['VG00001']).toBeUndefined();
    expect(Object.keys(result)).toHaveLength(1);
  });

  it('skips the header row even when it appears without # prefix', () => {
    // Some AncestryDNA files have an uncommented header row.
    const content = [
      '#AncestryDNA',
      'rsid\tchromosome\tposition\tallele1\tallele2',
      'rs4477212\t1\t82154\tA\tA',
    ].join('\n');
    const result = parseAncestryDNA(content);
    // Header row starts with "rsid" — skipped by parser.
    expect(Object.keys(result)).toHaveLength(1);
    expect(result['rs4477212']).toBe('AA');
  });

  it('throws when file has only header/comment lines and no SNP data', () => {
    const content = ['#AncestryDNA', 'rsid\tchromosome\tposition\tallele1\tallele2'].join('\n');
    expect(() => parseAncestryDNA(content)).toThrow('No valid SNP data found');
  });
});

// ─── 4. Parser — MyHeritage ──────────────────────────────────────────────────
//
// Tests CSV parsing with quoted/unquoted fields, VG-prefix IDs,
// mixed-case header variants, and no-call behavior.

describe('Parser — MyHeritage', () => {
  it('parses standard unquoted CSV format', () => {
    // MyHeritage format: RSID,CHROMOSOME,POSITION,RESULT (unquoted).
    const content = [
      'RSID,CHROMOSOME,POSITION,RESULT',
      'rs4477212,1,82154,AA',
      'rs3094315,1,752566,AG',
      'rs3131972,1,752721,GG',
    ].join('\n');
    const result = parseMyHeritage(content);
    expect(result['rs4477212']).toBe('AA');
    expect(result['rs3094315']).toBe('AG');
    expect(result['rs3131972']).toBe('GG');
    expect(Object.keys(result)).toHaveLength(3);
  });

  it('parses fully-quoted CSV format (all fields wrapped in double quotes)', () => {
    // Some MyHeritage exports quote every field.
    const content = [
      '"RSID","CHROMOSOME","POSITION","RESULT"',
      '"rs4477212","1","82154","AA"',
      '"rs3094315","1","752566","AG"',
    ].join('\n');
    const result = parseMyHeritage(content);
    expect(result['rs4477212']).toBe('AA');
    expect(result['rs3094315']).toBe('AG');
  });

  it('handles quotes around only some fields (mixed quoting)', () => {
    const content = ['RSID,CHROMOSOME,POSITION,RESULT', '"rs4477212",1,82154,"AA"'].join('\n');
    const result = parseMyHeritage(content);
    expect(result['rs4477212']).toBe('AA');
  });

  it('handles escaped double-quotes inside a quoted field (RFC 4180)', () => {
    // A quoted field containing "" is treated as a single escaped quote.
    // This is a CSV robustness test. The RSID field contains an internal quote.
    // In practice MyHeritage doesn't do this, but the parser should handle it.
    const content = [
      'RSID,CHROMOSOME,POSITION,RESULT',
      // "rs4477212" is a valid RSID; the extra quote is RFC-4180 escaped
      '"rs4477212","1","82154","AA"',
    ].join('\n');
    const result = parseMyHeritage(content);
    expect(result['rs4477212']).toBe('AA');
  });

  it('accepts VG-prefixed proprietary MyHeritage variant IDs', () => {
    // MyHeritage uses "VG" prefix for proprietary variants not in dbSNP.
    const content = [
      'RSID,CHROMOSOME,POSITION,RESULT',
      'VG00001,1,999999,CT',
      'VG00002,1,888888,AA',
    ].join('\n');
    const result = parseMyHeritage(content);
    expect(result['VG00001']).toBe('CT');
    expect(result['VG00002']).toBe('AA');
  });

  it('skips no-call entries where RESULT is "--"', () => {
    const content = [
      'RSID,CHROMOSOME,POSITION,RESULT',
      'rs4477212,1,82154,AA',
      'rs3094315,1,752566,--',
    ].join('\n');
    const result = parseMyHeritage(content);
    expect(result['rs3094315']).toBeUndefined();
    expect(Object.keys(result)).toHaveLength(1);
  });

  it('skips entries with empty RESULT field', () => {
    const content = [
      'RSID,CHROMOSOME,POSITION,RESULT',
      'rs4477212,1,82154,AA',
      'rs3094315,1,752566,',
    ].join('\n');
    const result = parseMyHeritage(content);
    expect(result['rs3094315']).toBeUndefined();
    expect(Object.keys(result)).toHaveLength(1);
  });

  it('skips lines with fewer than 4 CSV fields', () => {
    const content = [
      'RSID,CHROMOSOME,POSITION,RESULT',
      'rs4477212,1,82154,AA',
      'rs3094315,1,752566',
    ].join('\n');
    const result = parseMyHeritage(content);
    expect(Object.keys(result)).toHaveLength(1);
  });

  it('skips rsIDs that do not start with rs, i, or VG', () => {
    const content = [
      'RSID,CHROMOSOME,POSITION,RESULT',
      'rs4477212,1,82154,AA',
      'CHRX_12345,X,12345,AG',
    ].join('\n');
    const result = parseMyHeritage(content);
    expect(result['CHRX_12345']).toBeUndefined();
    expect(Object.keys(result)).toHaveLength(1);
  });

  it('accepts i-prefixed rsIDs in MyHeritage files', () => {
    const content = ['RSID,CHROMOSOME,POSITION,RESULT', 'i713426,1,817186,CC'].join('\n');
    const result = parseMyHeritage(content);
    expect(result['i713426']).toBe('CC');
  });

  it('throws when file has header but no data rows', () => {
    expect(() => parseMyHeritage('RSID,CHROMOSOME,POSITION,RESULT')).toThrow(
      'No valid SNP data found',
    );
  });
});

// ─── 5. Parser — VCF ─────────────────────────────────────────────────────────
//
// Tests advanced VCF scenarios: half-call genotypes, out-of-bounds allele
// indices, invalid nucleotide characters, excessively long alleles,
// GT not at index 0, phased genotypes, and multi-sample files.

describe('Parser — VCF', () => {
  // Reusable VCF header prefix for test fixtures.
  const VCF_HEADER = [
    '##fileformat=VCFv4.1',
    '#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\tFORMAT\tSAMPLE1',
  ].join('\n');

  it('parses a standard SNP with GT=0/0 (homozygous REF)', () => {
    const content = VCF_HEADER + '\n' + '1\t82154\trs4477212\tA\tG\t.\tPASS\t.\tGT\t0/0';
    const result = parseVcf(content);
    expect(result['rs4477212']).toBe('AA');
  });

  it('parses a standard SNP with GT=0/1 (heterozygous REF/ALT)', () => {
    const content = VCF_HEADER + '\n' + '1\t82154\trs4477212\tA\tG\t.\tPASS\t.\tGT\t0/1';
    const result = parseVcf(content);
    expect(result['rs4477212']).toBe('AG');
  });

  it('parses a standard SNP with GT=1/1 (homozygous ALT)', () => {
    const content = VCF_HEADER + '\n' + '1\t82154\trs4477212\tA\tG\t.\tPASS\t.\tGT\t1/1';
    const result = parseVcf(content);
    expect(result['rs4477212']).toBe('GG');
  });

  it('handles phased genotype with "|" separator (GT=0|1)', () => {
    const content = VCF_HEADER + '\n' + '1\t82154\trs4477212\tA\tG\t.\tPASS\t.\tGT\t0|1';
    const result = parseVcf(content);
    expect(result['rs4477212']).toBe('AG');
  });

  it('handles phased genotype with "|" separator (GT=1|0)', () => {
    // Phased: allele order matters for indexing, but result is same alleles.
    const content = VCF_HEADER + '\n' + '1\t82154\trs4477212\tA\tG\t.\tPASS\t.\tGT\t1|0';
    const result = parseVcf(content);
    expect(result['rs4477212']).toBe('GA');
  });

  it('picks the first sample column (index 9) in a multi-sample VCF', () => {
    // Multi-sample VCF: parser only uses index 9 (first sample).
    const content = [
      '##fileformat=VCFv4.1',
      '#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\tFORMAT\tSAMPLE1\tSAMPLE2',
      '1\t82154\trs4477212\tA\tG\t.\tPASS\t.\tGT\t0/0\t1/1', // SAMPLE1=AA, SAMPLE2=GG
    ].join('\n');
    const result = parseVcf(content);
    // Only SAMPLE1 (AA) should be used.
    expect(result['rs4477212']).toBe('AA');
  });

  it('skips no-call genotype "." (single dot half-call)', () => {
    const content =
      VCF_HEADER +
      '\n' +
      '1\t100\trs100\tA\tG\t.\tPASS\t.\tGT\t0/1\n' +
      '1\t200\trs200\tA\tG\t.\tPASS\t.\tGT\t.';
    const result = parseVcf(content);
    expect(result['rs200']).toBeUndefined();
    expect(Object.keys(result)).toHaveLength(1);
  });

  it('skips half-call genotype "./1" (one allele missing)', () => {
    // "./1" has NaN for index 0 — should be skipped.
    const content =
      VCF_HEADER +
      '\n' +
      '1\t100\trs100\tA\tG\t.\tPASS\t.\tGT\t0/1\n' +
      '1\t200\trs200\tA\tG\t.\tPASS\t.\tGT\t./1';
    const result = parseVcf(content);
    expect(result['rs200']).toBeUndefined();
    expect(Object.keys(result)).toHaveLength(1);
  });

  it('skips half-call genotype "1/." (second allele missing)', () => {
    const content =
      VCF_HEADER +
      '\n' +
      '1\t100\trs100\tA\tG\t.\tPASS\t.\tGT\t0/1\n' +
      '1\t200\trs200\tA\tG\t.\tPASS\t.\tGT\t1/.';
    const result = parseVcf(content);
    expect(result['rs200']).toBeUndefined();
    expect(Object.keys(result)).toHaveLength(1);
  });

  it('skips variants where allele index is out of bounds', () => {
    // GT=2/1 with ALT="G" (only one ALT allele, index 0=REF, 1=G).
    // Index 2 is out of bounds for alleleList [A, G].
    const content =
      VCF_HEADER +
      '\n' +
      '1\t100\trs100\tA\tG\t.\tPASS\t.\tGT\t0/1\n' +
      '1\t200\trs200\tA\tG\t.\tPASS\t.\tGT\t2/1';
    const result = parseVcf(content);
    expect(result['rs200']).toBeUndefined();
    expect(Object.keys(result)).toHaveLength(1);
  });

  it('skips REF alleles containing invalid nucleotide characters', () => {
    // REF must match /^[ACGTN]+$/. Structural variant notation like "<DEL>" is skipped.
    const content =
      VCF_HEADER +
      '\n' +
      '1\t100\trs100\tA\tG\t.\tPASS\t.\tGT\t0/1\n' +
      '1\t200\trs200\t<DEL>\tG\t.\tPASS\t.\tGT\t0/1';
    const result = parseVcf(content);
    expect(result['rs200']).toBeUndefined();
    expect(Object.keys(result)).toHaveLength(1);
  });

  it('skips ALT alleles containing invalid nucleotide characters', () => {
    // ALT "." means monomorphic ref-only — skipped.
    const content =
      VCF_HEADER +
      '\n' +
      '1\t100\trs100\tA\tG\t.\tPASS\t.\tGT\t0/1\n' +
      '1\t200\trs200\tA\t.\t.\tPASS\t.\tGT\t0/1';
    const result = parseVcf(content);
    expect(result['rs200']).toBeUndefined();
    expect(Object.keys(result)).toHaveLength(1);
  });

  it('skips alleles exceeding MAX_INDEL_LENGTH (>50bp)', () => {
    // Structural variants longer than 50bp are excluded.
    const longAllele = 'A'.repeat(51); // 51 nucleotides — exceeds 50bp limit
    const content =
      VCF_HEADER +
      '\n' +
      '1\t100\trs100\tA\tG\t.\tPASS\t.\tGT\t0/1\n' +
      `1\t200\trs200\t${longAllele}\tG\t.\tPASS\t.\tGT\t0/1`;
    const result = parseVcf(content);
    expect(result['rs200']).toBeUndefined();
    expect(Object.keys(result)).toHaveLength(1);
  });

  it('accepts alleles exactly at MAX_INDEL_LENGTH (50bp)', () => {
    // 50bp allele is on the boundary — should be accepted.
    const allele50 = 'A'.repeat(50); // exactly 50 nucleotides
    const content = VCF_HEADER + '\n' + `1\t200\trs200\t${allele50}\tG\t.\tPASS\t.\tGT\t0/1`;
    const result = parseVcf(content);
    // 50bp REF allele, 1bp ALT => indel format with '/' separator.
    expect(result['rs200']).toBe(`${allele50}/G`);
  });

  it('parses multi-allelic site with GT=1/2 (two non-REF alleles)', () => {
    // REF=A, ALT=G,C. alleleList=[A,G,C]. GT=1/2 => G and C => "GC".
    const content = VCF_HEADER + '\n' + '1\t100\trs100\tA\tG,C\t.\tPASS\t.\tGT\t1/2';
    const result = parseVcf(content);
    expect(result['rs100']).toBe('GC');
  });

  it('parses multi-allelic site with GT=0/2 (REF and second ALT)', () => {
    // REF=A, ALT=G,C. GT=0/2 => A and C => "AC".
    const content = VCF_HEADER + '\n' + '1\t100\trs100\tA\tG,C\t.\tPASS\t.\tGT\t0/2';
    const result = parseVcf(content);
    expect(result['rs100']).toBe('AC');
  });

  it('formats indel genotypes with "/" separator instead of concatenation', () => {
    // When REF or ALT has >1 character, separator "/" is used.
    const content = VCF_HEADER + '\n' + '1\t200\trs200\tAT\tG\t.\tPASS\t.\tGT\t0/1';
    const result = parseVcf(content);
    expect(result['rs200']).toBe('AT/G');
  });

  it('formats indel genotype for ALT longer than REF with "/" separator', () => {
    const content = VCF_HEADER + '\n' + '1\t200\trs200\tA\tGTT\t.\tPASS\t.\tGT\t0/1';
    const result = parseVcf(content);
    expect(result['rs200']).toBe('A/GTT');
  });

  it('skips variants without rsID (ID column is ".")', () => {
    const content =
      VCF_HEADER +
      '\n' +
      '1\t100\trs100\tA\tG\t.\tPASS\t.\tGT\t0/1\n' +
      '1\t200\t.\tA\tG\t.\tPASS\t.\tGT\t0/1';
    const result = parseVcf(content);
    expect(Object.keys(result)).toHaveLength(1);
    expect(result['rs100']).toBe('AG');
  });

  it('skips variants with non-rs-prefixed ID (e.g., "." or "chrX_123")', () => {
    const content =
      VCF_HEADER +
      '\n' +
      '1\t100\trs100\tA\tG\t.\tPASS\t.\tGT\t0/1\n' +
      '1\t200\tCHR1_200\tA\tG\t.\tPASS\t.\tGT\t0/1';
    const result = parseVcf(content);
    expect(result['CHR1_200']).toBeUndefined();
    expect(Object.keys(result)).toHaveLength(1);
  });

  it('finds GT in FORMAT at a non-zero index (GT is not first field)', () => {
    // FORMAT="DP:GT:GQ" — GT is at index 1.
    const content = VCF_HEADER + '\n' + '1\t100\trs100\tA\tG\t.\tPASS\t.\tDP:GT:GQ\t30:0/1:99';
    const result = parseVcf(content);
    expect(result['rs100']).toBe('AG');
  });

  it('skips lines with no GT field in FORMAT', () => {
    // FORMAT="DP:GQ" — no GT field at all.
    const content =
      VCF_HEADER +
      '\n' +
      '1\t100\trs100\tA\tG\t.\tPASS\t.\tGT\t0/1\n' +
      '1\t200\trs200\tA\tG\t.\tPASS\t.\tDP:GQ\t30:99';
    const result = parseVcf(content);
    expect(result['rs200']).toBeUndefined();
    expect(Object.keys(result)).toHaveLength(1);
  });

  it('skips data lines appearing before the #CHROM header', () => {
    // Lines before #CHROM are ignored even if they look like data.
    const content = [
      '##fileformat=VCFv4.1',
      '1\t100\trs100\tA\tG\t.\tPASS\t.\tGT\t0/1', // before #CHROM — skipped
      '#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\tFORMAT\tSAMPLE1',
      '1\t200\trs200\tA\tG\t.\tPASS\t.\tGT\t0/1', // after #CHROM — parsed
    ].join('\n');
    const result = parseVcf(content);
    expect(result['rs100']).toBeUndefined();
    expect(result['rs200']).toBe('AG');
  });

  it('skips data lines with fewer than 10 tab-separated columns', () => {
    // VCF requires at least 10 columns to have a sample GT column.
    const content = VCF_HEADER + '\n' + '1\t100\trs100\tA\tG\t.\tPASS\t.\tGT'; // only 9 cols — skipped
    expect(() => parseVcf(content)).toThrow('No valid SNP data found');
  });

  it('throws when file has ##fileformat and #CHROM but no data lines', () => {
    const content = VCF_HEADER; // header only, no data
    expect(() => parseVcf(content)).toThrow('No valid SNP data found');
  });

  it('handles "N" as a valid ambiguous nucleotide in REF/ALT', () => {
    // N is a valid IUPAC code for "any nucleotide" and passes VALID_NUCLEOTIDE_CHARS.
    const content = VCF_HEADER + '\n' + '1\t100\trs100\tN\tA\t.\tPASS\t.\tGT\t0/1';
    const result = parseVcf(content);
    expect(result['rs100']).toBe('NA');
  });
});

// ─── 6. Parser — Edge Cases ───────────────────────────────────────────────────
//
// Tests BOM prefix, CRLF/mixed line endings, truncated last line,
// duplicate rsIDs, empty files, comment-only files, non-standard chromosomes,
// and the "00" no-call variant.

describe('Parser — Edge Cases', () => {
  // ── BOM (Byte Order Mark) ─────────────────────────────────────────────────

  it('parses 23andMe file with UTF-8 BOM prefix (\uFEFF)', () => {
    // Some tools prepend a BOM to the file. The BOM appears on the first line.
    // iterateLines uses trimEnd() which does NOT strip BOM — but BOM is at the
    // start of the first line. If the first line is a comment (# ...), the BOM
    // becomes part of the comment prefix and the line is skipped. Data lines
    // should still be parsed correctly because BOM only affects the first line.
    const bom = '\uFEFF';
    const content =
      bom +
      ['# 23andMe data file', 'rs4477212\t1\t82154\tAA', 'rs3094315\t1\t752566\tAG'].join('\n');
    const result = parse23andMe(content);
    // The BOM is on the comment line — data lines are parsed normally.
    expect(result['rs4477212']).toBe('AA');
    expect(result['rs3094315']).toBe('AG');
  });

  it('parses AncestryDNA file with UTF-8 BOM on the comment line', () => {
    const bom = '\uFEFF';
    const content =
      bom +
      [
        '#AncestryDNA',
        'rsid\tchromosome\tposition\tallele1\tallele2',
        'rs4477212\t1\t82154\tA\tA',
      ].join('\n');
    const result = parseAncestryDNA(content);
    expect(result['rs4477212']).toBe('AA');
  });

  it('parses MyHeritage file with UTF-8 BOM prefix', () => {
    const bom = '\uFEFF';
    // BOM is prepended to the header row — header contains "rsid" so it's skipped.
    const content = bom + ['RSID,CHROMOSOME,POSITION,RESULT', 'rs4477212,1,82154,AA'].join('\n');
    const result = parseMyHeritage(content);
    expect(result['rs4477212']).toBe('AA');
  });

  // ── CRLF Line Endings ─────────────────────────────────────────────────────

  it('parses 23andMe file with Windows CRLF line endings', () => {
    // iterateLines uses trimEnd() which strips trailing \r.
    const content =
      '# 23andMe\r\n' +
      'rs4477212\t1\t82154\tAA\r\n' +
      'rs3094315\t1\t752566\tAG\r\n' +
      'rs3131972\t1\t752721\tGG\r\n';
    const result = parse23andMe(content);
    expect(result['rs4477212']).toBe('AA');
    expect(result['rs3094315']).toBe('AG');
    expect(result['rs3131972']).toBe('GG');
  });

  it('parses AncestryDNA file with CRLF line endings', () => {
    const content =
      '#AncestryDNA\r\n' +
      'rsid\tchromosome\tposition\tallele1\tallele2\r\n' +
      'rs4477212\t1\t82154\tA\tA\r\n' +
      'rs3094315\t1\t752566\tA\tG\r\n';
    const result = parseAncestryDNA(content);
    expect(result['rs4477212']).toBe('AA');
    expect(result['rs3094315']).toBe('AG');
  });

  it('parses MyHeritage file with CRLF line endings', () => {
    const content =
      'RSID,CHROMOSOME,POSITION,RESULT\r\n' +
      'rs4477212,1,82154,AA\r\n' +
      'rs3094315,1,752566,AG\r\n';
    const result = parseMyHeritage(content);
    expect(result['rs4477212']).toBe('AA');
    expect(result['rs3094315']).toBe('AG');
  });

  it('parses VCF file with CRLF line endings', () => {
    const content =
      '##fileformat=VCFv4.1\r\n' +
      '#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\tFORMAT\tSAMPLE1\r\n' +
      '1\t82154\trs4477212\tA\tG\t.\tPASS\t.\tGT\t0/0\r\n';
    const result = parseVcf(content);
    expect(result['rs4477212']).toBe('AA');
  });

  it('parses 23andMe file with mixed CRLF and LF line endings', () => {
    // Some files have inconsistent line endings (editor-mixed).
    const content =
      '# 23andMe\r\n' + // CRLF
      'rs4477212\t1\t82154\tAA\n' + // LF
      'rs3094315\t1\t752566\tAG\r\n' + // CRLF
      'rs3131972\t1\t752721\tGG\n'; // LF
    const result = parse23andMe(content);
    expect(result['rs4477212']).toBe('AA');
    expect(result['rs3094315']).toBe('AG');
    expect(result['rs3131972']).toBe('GG');
  });

  // ── Truncated Last Line (no trailing newline) ─────────────────────────────

  it('parses 23andMe file with no trailing newline (truncated last line)', () => {
    // File does not end with \n — last line must still be yielded.
    const content = '# 23andMe\n' + 'rs4477212\t1\t82154\tAA\n' + 'rs3131972\t1\t752721\tGG'; // <-- no trailing newline
    const result = parse23andMe(content);
    expect(result['rs3131972']).toBe('GG');
    expect(Object.keys(result)).toHaveLength(2);
  });

  it('parses AncestryDNA file with no trailing newline', () => {
    const content = '#AncestryDNA\n' + 'rs4477212\t1\t82154\tA\tA\n' + 'rs3094315\t1\t752566\tA\tG'; // no trailing newline
    const result = parseAncestryDNA(content);
    expect(result['rs3094315']).toBe('AG');
  });

  it('parses MyHeritage file with no trailing newline', () => {
    const content =
      'RSID,CHROMOSOME,POSITION,RESULT\n' + 'rs4477212,1,82154,AA\n' + 'rs3094315,1,752566,AG'; // no trailing newline
    const result = parseMyHeritage(content);
    expect(result['rs3094315']).toBe('AG');
  });

  // ── Duplicate rsIDs ───────────────────────────────────────────────────────

  it('last entry wins when duplicate rsIDs appear in a 23andMe file', () => {
    // The parser uses object assignment: snps[rsid] = genotype.
    // Later assignments overwrite earlier ones => last occurrence wins.
    const content = [
      '# 23andMe',
      'rs4477212\t1\t82154\tAA', // first occurrence: AA
      'rs4477212\t1\t82154\tGG', // second occurrence: GG — overwrites AA
    ].join('\n');
    const result = parse23andMe(content);
    expect(result['rs4477212']).toBe('GG');
    expect(Object.keys(result)).toHaveLength(1);
  });

  it('last entry wins when duplicate rsIDs appear in an AncestryDNA file', () => {
    const content = [
      '#AncestryDNA',
      'rs4477212\t1\t82154\tA\tA', // first: AA
      'rs4477212\t1\t82154\tA\tG', // second: AG — overwrites
    ].join('\n');
    const result = parseAncestryDNA(content);
    expect(result['rs4477212']).toBe('AG');
    expect(Object.keys(result)).toHaveLength(1);
  });

  it('last entry wins when duplicate rsIDs appear in a MyHeritage file', () => {
    const content = [
      'RSID,CHROMOSOME,POSITION,RESULT',
      'rs4477212,1,82154,AA',
      'rs4477212,1,82154,CC',
    ].join('\n');
    const result = parseMyHeritage(content);
    expect(result['rs4477212']).toBe('CC');
    expect(Object.keys(result)).toHaveLength(1);
  });

  // ── Empty and Comment-only Files ──────────────────────────────────────────

  it('throws for an empty file passed to parse23andMe', () => {
    expect(() => parse23andMe('')).toThrow('No valid SNP data found');
  });

  it('throws for an empty file passed to parseAncestryDNA', () => {
    expect(() => parseAncestryDNA('')).toThrow('No valid SNP data found');
  });

  it('throws for an empty file passed to parseMyHeritage', () => {
    expect(() => parseMyHeritage('')).toThrow('No valid SNP data found');
  });

  it('throws for an empty file passed to parseVcf', () => {
    expect(() => parseVcf('')).toThrow('No valid SNP data found');
  });

  it('throws for 23andMe file consisting entirely of comment lines', () => {
    const content = [
      '# Comment line 1',
      '# Comment line 2',
      '# Comment line 3',
      '# Comment line 4',
    ].join('\n');
    expect(() => parse23andMe(content)).toThrow('No valid SNP data found');
  });

  it('throws for 23andMe file with header row but all data lines are no-calls', () => {
    const content = [
      '# 23andMe',
      '# rsid\tchromosome\tposition\tgenotype',
      'rs4477212\t1\t82154\t--',
      'rs3094315\t1\t752566\t--',
      'rs3131972\t1\t752721\t--',
    ].join('\n');
    expect(() => parse23andMe(content)).toThrow('No valid SNP data found');
  });

  // ── Non-standard Chromosome Names ─────────────────────────────────────────

  it('parses 23andMe entries with "M" chromosome (mitochondria alternative)', () => {
    // Some files use "M" instead of "MT" for mitochondrial chromosome.
    const content = ['# 23andMe', 'rs1234\tM\t12345\tAA'].join('\n');
    const result = parse23andMe(content);
    // Parser does not filter by chromosome name — "M" is accepted.
    expect(result['rs1234']).toBe('AA');
  });

  it('parses 23andMe entries with "chr1" style chromosome names', () => {
    // Some custom exports use "chr" prefix on chromosome names.
    // Parser does not validate chromosome values — they pass through.
    const content = ['# 23andMe', 'rs4477212\tchr1\t82154\tAA'].join('\n');
    const result = parse23andMe(content);
    expect(result['rs4477212']).toBe('AA');
  });

  it('parses AncestryDNA entries with non-numeric chromosome names', () => {
    // Parser does not validate chromosome values in parseAncestryDNA;
    // the validation function (validateAncestryDNA) does, but not the parser.
    const content = ['#AncestryDNA', 'rs4477212\tchrX\t82154\tA\tA'].join('\n');
    const result = parseAncestryDNA(content);
    expect(result['rs4477212']).toBe('AA');
  });

  // ── Extremely Large Comment Headers ──────────────────────────────────────

  it('parses 23andMe file with 200 comment lines before data', () => {
    // detectFormat only reads the first 4000 chars, but the parser reads all lines.
    // 200 comment lines should be skipped without error.
    const comments = Array.from({ length: 200 }, (_, i) => `# Comment line ${i + 1}`);
    const data = ['rs4477212\t1\t82154\tAA', 'rs3094315\t1\t752566\tAG'];
    // Include "23andMe" in one of the first few comments for format detection.
    comments[0] = '# This data file generated by 23andMe';
    const content = [...comments, ...data].join('\n');
    const result = parse23andMe(content);
    expect(result['rs4477212']).toBe('AA');
    expect(result['rs3094315']).toBe('AG');
  });

  // ── "00" No-call Genotype ─────────────────────────────────────────────────

  it('does NOT skip "00" genotype in 23andMe (only "--" and "" are no-calls)', () => {
    // The parser explicitly checks for "--" and "". "00" is NOT in that list.
    // This test documents the ACTUAL behavior: "00" is stored as-is.
    // TODO: If "00" should be treated as a no-call, the parser needs updating.
    const content = ['# 23andMe', 'rs4477212\t1\t82154\tAA', 'rs3094315\t1\t752566\t00'].join('\n');
    const result = parse23andMe(content);
    // "00" passes through — it is not filtered as a no-call.
    expect(result['rs3094315']).toBe('00');
  });

  // ── Large File Parsing via parseGeneticFile ────────────────────────────────

  it('parseGeneticFile throws descriptive error for unknown format', () => {
    expect(() => parseGeneticFile('not genetic data')).toThrow('Unrecognized genetic data format');
  });
});

// ─── 7. Parser — Streaming (iterateLines behavior) ───────────────────────────
//
// iterateLines is a private generator, so we test it through the public parse
// functions. Tests verify that single-line content, content without trailing
// newline, and content with only newlines all behave correctly.

describe('Parser — Streaming (iterateLines behavior)', () => {
  it('handles content with a single data line (no comments, no newline)', () => {
    // A single line with no trailing newline should still be parsed.
    const content = 'rs4477212\t1\t82154\tAA';
    const result = parse23andMe(content);
    expect(result['rs4477212']).toBe('AA');
    expect(Object.keys(result)).toHaveLength(1);
  });

  it('handles content with only empty lines (blank file body)', () => {
    // A file consisting entirely of blank lines produces no SNPs.
    const content = '\n\n\n\n\n';
    expect(() => parse23andMe(content)).toThrow('No valid SNP data found');
  });

  it('handles content with trailing blank lines after data', () => {
    const content = '# 23andMe\n' + 'rs4477212\t1\t82154\tAA\n' + '\n' + '\n';
    const result = parse23andMe(content);
    expect(result['rs4477212']).toBe('AA');
    expect(Object.keys(result)).toHaveLength(1);
  });

  it('handles content with blank lines interspersed between data lines', () => {
    const content = [
      '# 23andMe',
      '',
      'rs4477212\t1\t82154\tAA',
      '',
      'rs3094315\t1\t752566\tAG',
      '',
    ].join('\n');
    const result = parse23andMe(content);
    expect(result['rs4477212']).toBe('AA');
    expect(result['rs3094315']).toBe('AG');
    expect(Object.keys(result)).toHaveLength(2);
  });

  it('handles a 23andMe single-line file (no trailing newline) via parseGeneticFile', () => {
    // Full pipeline test: format detection + parsing for minimal valid content.
    // A single data line triggers the 23andMe heuristic.
    const content = 'rs4477212\t1\t82154\tAA';
    const [genotypes, format] = parseGeneticFile(content);
    expect(format).toBe('23andme');
    expect(genotypes['rs4477212']).toBe('AA');
  });

  it('handles MyHeritage content where lines have trailing spaces', () => {
    // Trailing whitespace after the last column value.
    const content = ['RSID,CHROMOSOME,POSITION,RESULT', 'rs4477212,1,82154,AA   '].join('\n');
    // The genotype "AA   " would have trailing spaces — trimEnd() in iterateLines
    // strips trailing whitespace from lines (including spaces after the last column).
    // But parseCsvLine splits on comma, so the last field is "AA   " which is
    // then trimmed by the parser (.trim() call on row[3]).
    const result = parseMyHeritage(content);
    expect(result['rs4477212']).toBe('AA');
  });
});

// ─── 8. Parser — Performance ─────────────────────────────────────────────────
//
// Verifies that parsing a large file (10,000+ SNP lines) completes within
// a reasonable time bound of 1 second. Uses inline string generation.

describe('Parser — Performance', () => {
  it('parses a 10,000-line 23andMe file in under 1 second', () => {
    // Build a 10K-line 23andMe file with sequential rsIDs.
    const lines: string[] = [
      '# This data file generated by 23andMe',
      '# rsid\tchromosome\tposition\tgenotype',
    ];
    const GENOTYPES = ['AA', 'AG', 'GG', 'CC', 'CT', 'TT'];
    for (let i = 0; i < 10000; i++) {
      const chr = ((i % 22) + 1).toString();
      const pos = (82154 + i * 100).toString();
      const genotype = GENOTYPES[i % GENOTYPES.length]!;
      lines.push(`rs${1000000 + i}\t${chr}\t${pos}\t${genotype}`);
    }
    const content = lines.join('\n');

    const start = performance.now();
    const result = parse23andMe(content);
    const elapsed = performance.now() - start;

    expect(Object.keys(result)).toHaveLength(10000);
    expect(elapsed).toBeLessThan(1000); // must complete within 1 second
  });

  it('parses a 10,000-line AncestryDNA file in under 1 second', () => {
    const lines: string[] = ['#AncestryDNA', 'rsid\tchromosome\tposition\tallele1\tallele2'];
    const ALLELE_PAIRS: [string, string][] = [
      ['A', 'A'],
      ['A', 'G'],
      ['G', 'G'],
      ['C', 'T'],
    ];
    for (let i = 0; i < 10000; i++) {
      const chr = ((i % 22) + 1).toString();
      const pos = (82154 + i * 100).toString();
      const [a1, a2] = ALLELE_PAIRS[i % ALLELE_PAIRS.length]!;
      lines.push(`rs${2000000 + i}\t${chr}\t${pos}\t${a1}\t${a2}`);
    }
    const content = lines.join('\n');

    const start = performance.now();
    const result = parseAncestryDNA(content);
    const elapsed = performance.now() - start;

    expect(Object.keys(result)).toHaveLength(10000);
    expect(elapsed).toBeLessThan(1000);
  });

  it('parses a 10,000-line MyHeritage file in under 1 second', () => {
    const lines: string[] = ['RSID,CHROMOSOME,POSITION,RESULT'];
    const RESULTS = ['AA', 'AG', 'GG', 'CC', 'CT', 'TT'];
    for (let i = 0; i < 10000; i++) {
      const chr = ((i % 22) + 1).toString();
      const pos = (82154 + i * 100).toString();
      const genotype = RESULTS[i % RESULTS.length]!;
      lines.push(`rs${3000000 + i},${chr},${pos},${genotype}`);
    }
    const content = lines.join('\n');

    const start = performance.now();
    const result = parseMyHeritage(content);
    const elapsed = performance.now() - start;

    expect(Object.keys(result)).toHaveLength(10000);
    expect(elapsed).toBeLessThan(1000);
  });

  it('parses a 10,000-line VCF file in under 1 second', () => {
    const lines: string[] = [
      '##fileformat=VCFv4.1',
      '#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\tFORMAT\tSAMPLE1',
    ];
    const GTS = ['0/0', '0/1', '1/1'];
    for (let i = 0; i < 10000; i++) {
      const chr = ((i % 22) + 1).toString();
      const pos = (82154 + i * 100).toString();
      const gt = GTS[i % GTS.length]!;
      lines.push(`${chr}\t${pos}\trs${4000000 + i}\tA\tG\t.\tPASS\t.\tGT\t${gt}`);
    }
    const content = lines.join('\n');

    const start = performance.now();
    const result = parseVcf(content);
    const elapsed = performance.now() - start;

    expect(Object.keys(result)).toHaveLength(10000);
    expect(elapsed).toBeLessThan(1000);
  });
});

// ─── 9. Parser — detectChipVersion (in-module function) ──────────────────────
//
// Tests the detectChipVersion export from parser.ts (not the chip-detection.ts
// module). This covers the basic routing and marker detection logic.

describe('Parser — detectChipVersion', () => {
  it('returns null for VCF format (no chip provider)', () => {
    expect(detectChipVersion('vcf', 1000000, {})).toBeNull();
  });

  it('returns null for unknown format', () => {
    expect(detectChipVersion('unknown', 500000, {})).toBeNull();
  });

  it('detects 23andMe v3 from high SNP count (~960K)', () => {
    const result = detectChipVersion('23andme', 960000, {});
    expect(result).not.toBeNull();
    expect(result!.provider).toBe('23andMe');
    expect(result!.version).toBe('v3');
  });

  it('detects 23andMe v4 from medium SNP count (~570K)', () => {
    const result = detectChipVersion('23andme', 570000, {});
    expect(result).not.toBeNull();
    expect(result!.provider).toBe('23andMe');
    expect(result!.version).toBe('v4');
  });

  it('detects 23andMe v5 from ~640K count with v5 marker SNPs present', () => {
    const genotypes = {
      rs548049170: 'AA',
      rs13354714: 'CC',
      rs2298108: 'AG',
    };
    const result = detectChipVersion('23andme', 640000, genotypes);
    expect(result).not.toBeNull();
    expect(result!.version).toBe('v5');
    expect(result!.confidence).toBeGreaterThanOrEqual(0.9);
  });

  it('detects 23andMe v3 with higher confidence when v3 markers are present', () => {
    const genotypes = {
      rs4851251: 'AG',
      rs2296442: 'CT',
      rs2032582: 'GG',
    };
    const result = detectChipVersion('23andme', 960000, genotypes);
    expect(result).not.toBeNull();
    expect(result!.version).toBe('v3');
    expect(result!.confidence).toBeGreaterThanOrEqual(0.9);
  });

  it('returns unknown version for out-of-range SNP count (23andMe)', () => {
    const result = detectChipVersion('23andme', 100000, {});
    expect(result).not.toBeNull();
    expect(result!.version).toBe('unknown');
    expect(result!.confidence).toBe(0);
  });

  it('detects AncestryDNA v1 from ~700K SNP count', () => {
    const result = detectChipVersion('ancestrydna', 700000, {});
    expect(result).not.toBeNull();
    expect(result!.provider).toBe('AncestryDNA');
    expect(result!.version).toBe('v1');
  });

  it('detects AncestryDNA v2 from ~650K SNP count', () => {
    const result = detectChipVersion('ancestrydna', 650000, {});
    expect(result).not.toBeNull();
    expect(result!.provider).toBe('AncestryDNA');
    expect(result!.version).toBe('v2');
  });

  it('detects MyHeritage v1 from count in typical range (600K-800K)', () => {
    const result = detectChipVersion('myheritage', 700000, {});
    expect(result).not.toBeNull();
    expect(result!.provider).toBe('MyHeritage');
    expect(result!.version).toBe('v1');
  });

  it('confidence is in [0, 1] range for all known versions', () => {
    const cases: [string, number][] = [
      ['23andme', 960000],
      ['23andme', 570000],
      ['23andme', 640000],
      ['ancestrydna', 700000],
      ['ancestrydna', 650000],
      ['myheritage', 700000],
    ];
    for (const [format, snpCount] of cases) {
      const result = detectChipVersion(
        format as 'myheritage' | '23andme' | 'ancestrydna',
        snpCount,
        {},
      );
      expect(result).not.toBeNull();
      expect(result!.confidence).toBeGreaterThanOrEqual(0);
      expect(result!.confidence).toBeLessThanOrEqual(1);
    }
  });
});

// ─── 10. Parser — getGenotypeStats (extended cases) ──────────────────────────
//
// Supplements the existing getGenotypeStats tests with indel genotype handling
// and larger distribution scenarios.

describe('Parser — getGenotypeStats (extended)', () => {
  it('does not count 4-character indel genotypes as homozygous or heterozygous', () => {
    // Indel genotypes like "DDII" or "AT/G" have length != 2, so they fall into
    // the "else" branch in the classifier and are not counted in either bucket.
    const genotypes = {
      rs1: 'AA', // homozygous (length 2, [0]===[1])
      rs2: 'AT/G', // indel (length 4 — neither counted)
      rs3: 'AG', // heterozygous (length 2, [0]!==[1])
    };
    const stats = getGenotypeStats(genotypes);
    expect(stats.totalSnps).toBe(3);
    expect(stats.homozygousCount).toBe(1);
    expect(stats.heterozygousCount).toBe(1);
    // rs2 (indel) is not counted in either bucket.
  });

  it('counts 3-character genotypes (indel-like) as neither homozygous nor heterozygous', () => {
    const genotypes = { rs1: 'ATG' };
    const stats = getGenotypeStats(genotypes);
    expect(stats.totalSnps).toBe(1);
    expect(stats.homozygousCount).toBe(0);
    expect(stats.heterozygousCount).toBe(0);
  });

  it('correctly builds distribution for a mixed genotype set', () => {
    const genotypes = {
      rs1: 'AA',
      rs2: 'AA',
      rs3: 'AA',
      rs4: 'AG',
      rs5: 'GG',
    };
    const stats = getGenotypeStats(genotypes);
    expect(stats.genotypeDistribution['AA']).toBe(3);
    expect(stats.genotypeDistribution['AG']).toBe(1);
    expect(stats.genotypeDistribution['GG']).toBe(1);
    expect(stats.homozygousCount).toBe(4); // AA×3 + GG×1
    expect(stats.heterozygousCount).toBe(1); // AG×1
  });

  it('handles a single-entry genotype map correctly', () => {
    const genotypes = { rs1: 'CT' };
    const stats = getGenotypeStats(genotypes);
    expect(stats.totalSnps).toBe(1);
    expect(stats.homozygousCount).toBe(0);
    expect(stats.heterozygousCount).toBe(1);
    expect(stats.genotypeDistribution['CT']).toBe(1);
  });
});

// ─── 11. Parser — buildParseResultSummary (extended cases) ───────────────────

describe('Parser — buildParseResultSummary (extended)', () => {
  it('skippedLines is 0 when rawLineCount equals totalSnps', () => {
    // If all raw lines produced valid SNPs (impossible in practice but valid math).
    const genotypes = { rs1: 'AA', rs2: 'AG' };
    const summary = buildParseResultSummary(genotypes, '23andme', {}, 2);
    expect(summary.skippedLines).toBe(0);
  });

  it('skippedLines is 0 when rawLineCount is less than totalSnps', () => {
    // rawLineCount < totalSnps shouldn't happen, but guard is: only set when >totalSnps.
    const genotypes = { rs1: 'AA', rs2: 'AG', rs3: 'GG' };
    const summary = buildParseResultSummary(genotypes, '23andme', {}, 2);
    // rawLineCount=2 < totalSnps=3 => condition is false => skippedLines=0
    expect(summary.skippedLines).toBe(0);
  });

  it('includes all metadata key-value pairs provided', () => {
    const genotypes = { rs1: 'AA' };
    const summary = buildParseResultSummary(genotypes, 'myheritage', {
      fileName: 'test_dna.csv',
      uploadDate: '2024-01-01',
    });
    expect(summary.metadata['fileName']).toBe('test_dna.csv');
    expect(summary.metadata['uploadDate']).toBe('2024-01-01');
  });

  it('returns empty metadata object when metadata is omitted', () => {
    const genotypes = { rs1: 'AA' };
    const summary = buildParseResultSummary(genotypes, 'vcf');
    expect(summary.metadata).toEqual({});
  });

  it('correctly reports format for all supported formats', () => {
    const formats = ['23andme', 'ancestrydna', 'myheritage', 'vcf', 'unknown'] as const;
    for (const format of formats) {
      const summary = buildParseResultSummary({}, format, {}, 0);
      expect(summary.format).toBe(format);
    }
  });
});
