/**
 * Tests for the genetic data file parser.
 *
 * Tests cover format detection, parsing of all 4 formats (23andMe, AncestryDNA,
 * MyHeritage/FTDNA, VCF), validation, and edge cases.
 */

import { describe, it, expect } from 'vitest';
import {
  detectFormat,
  parse23andMe,
  parseAncestryDNA,
  parseMyHeritage,
  parseVcf,
  parseGeneticFile,
  getGenotypeStats,
  buildParseResultSummary,
  validate23andMe,
  validateAncestryDNA,
  validateMyHeritage,
  validateVcf,
  validateGeneticFile,
} from '../src/parser';

// ─── Test Fixtures ────────────────────────────────────────────────────────

const SAMPLE_23ANDME = [
  '# This data file generated by 23andMe at: Mon Jan 01 2024',
  '# rsid\tchromosome\tposition\tgenotype',
  'rs4477212\t1\t82154\tAA',
  'rs3094315\t1\t752566\tAG',
  'rs3131972\t1\t752721\tGG',
  'rs12124819\t1\t776546\tAA',
  'i713426\t1\t817186\tCC',
].join('\n');

const SAMPLE_ANCESTRYDNA = [
  '#AncestryDNA raw data download',
  '#This file was generated by AncestryDNA',
  'rsid\tchromosome\tposition\tallele1\tallele2',
  'rs4477212\t1\t82154\tA\tA',
  'rs3094315\t1\t752566\tA\tG',
  'rs3131972\t1\t752721\tG\tG',
  'rs12124819\t1\t776546\tA\tA',
  'i713426\t1\t817186\tC\tC',
].join('\n');

const SAMPLE_MYHERITAGE = [
  'RSID,CHROMOSOME,POSITION,RESULT',
  'rs4477212,1,82154,AA',
  'rs3094315,1,752566,AG',
  'rs3131972,1,752721,GG',
  'rs12124819,1,776546,AA',
  'VG00001,1,999999,CT',
].join('\n');

const SAMPLE_VCF = [
  '##fileformat=VCFv4.1',
  '##INFO=<ID=DP,Number=1,Type=Integer>',
  '#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\tFORMAT\tSAMPLE1',
  '1\t82154\trs4477212\tA\tG\t100\tPASS\t.\tGT:DP\t0/0:30',
  '1\t752566\trs3094315\tA\tG\t100\tPASS\t.\tGT:DP\t0/1:25',
  '1\t752721\trs3131972\tA\tG\t100\tPASS\t.\tGT:DP\t1/1:20',
  '1\t776546\trs12124819\tC\tT\t100\tPASS\t.\tGT:DP\t0/0:28',
].join('\n');

// ─── Format Detection ───────────────────────────────────────────────────────

describe('detectFormat', () => {
  it('should detect 23andMe format from comment signature', () => {
    expect(detectFormat(SAMPLE_23ANDME)).toBe('23andme');
  });

  it('should detect AncestryDNA format from comment signature', () => {
    expect(detectFormat(SAMPLE_ANCESTRYDNA)).toBe('ancestrydna');
  });

  it('should detect VCF format from ##fileformat=VCF line', () => {
    expect(detectFormat(SAMPLE_VCF)).toBe('vcf');
  });

  it('should detect MyHeritage format from CSV header', () => {
    expect(detectFormat(SAMPLE_MYHERITAGE)).toBe('myheritage');
  });

  it('should return "unknown" for unrecognized formats', () => {
    expect(detectFormat('random data\nno format here')).toBe('unknown');
    expect(detectFormat('')).toBe('unknown');
    expect(detectFormat('just some text')).toBe('unknown');
  });

  it('should detect 23andMe format from 4-column tab-separated data without header', () => {
    // 23andMe heuristic detection: 4-column tab-separated with rs-prefixed IDs
    const noHeader = [
      'rs4477212\t1\t82154\tAA',
      'rs3094315\t1\t752566\tAG',
      'rs3131972\t1\t752721\tGG',
      'rs12124819\t1\t776546\tAA',
    ].join('\n');
    expect(detectFormat(noHeader)).toBe('23andme');
  });

  it('should detect AncestryDNA format from 5-column header with allele1/allele2', () => {
    const headerOnly = [
      'rsid\tchromosome\tposition\tallele1\tallele2',
      'rs4477212\t1\t82154\tA\tA',
      'rs3094315\t1\t752566\tA\tG',
    ].join('\n');
    expect(detectFormat(headerOnly)).toBe('ancestrydna');
  });

  it('should detect VCF from ## comments with #CHROM header', () => {
    const vcfNoFileformat = [
      '##source=myApp',
      '#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\tFORMAT\tSAMPLE',
      '1\t100\trs123\tA\tG\t30\tPASS\t.\tGT\t0/1',
    ].join('\n');
    expect(detectFormat(vcfNoFileformat)).toBe('vcf');
  });

  it('should detect MyHeritage from data heuristics without explicit header', () => {
    // 4-column comma-separated with rs-prefixed IDs and 2-char results
    const noHeaderMyHeritage = [
      'rs4477212,1,82154,AA',
      'rs3094315,1,752566,AG',
      'rs3131972,1,752721,GG',
    ].join('\n');
    expect(detectFormat(noHeaderMyHeritage)).toBe('myheritage');
  });
});

// ─── 23andMe Parser ─────────────────────────────────────────────────────────

describe('parse23andMe', () => {
  it('should parse valid 23andMe content', () => {
    const result = parse23andMe(SAMPLE_23ANDME);
    expect(result['rs4477212']).toBe('AA');
    expect(result['rs3094315']).toBe('AG');
    expect(result['rs3131972']).toBe('GG');
    expect(result['rs12124819']).toBe('AA');
    expect(result['i713426']).toBe('CC');
    expect(Object.keys(result)).toHaveLength(5);
  });

  it('should skip comment lines starting with #', () => {
    const content = [
      '# Comment line 1',
      '# Comment line 2',
      'rs4477212\t1\t82154\tAA',
    ].join('\n');
    const result = parse23andMe(content);
    expect(Object.keys(result)).toHaveLength(1);
    expect(result['rs4477212']).toBe('AA');
  });

  it('should skip no-call entries (--)', () => {
    const content = [
      'rs4477212\t1\t82154\tAA',
      'rs3094315\t1\t752566\t--',
      'rs3131972\t1\t752721\tGG',
    ].join('\n');
    const result = parse23andMe(content);
    expect(Object.keys(result)).toHaveLength(2);
    expect(result['rs3094315']).toBeUndefined();
  });

  it('should skip malformed lines with fewer than 4 columns', () => {
    const content = [
      'rs4477212\t1\t82154\tAA',
      'rs3094315\t1',
      'only_one_column',
      'rs3131972\t1\t752721\tGG',
    ].join('\n');
    const result = parse23andMe(content);
    expect(Object.keys(result)).toHaveLength(2);
  });

  it('should throw on empty file', () => {
    expect(() => parse23andMe('')).toThrow('No valid SNP data found');
    expect(() => parse23andMe('# only comments\n# nothing here')).toThrow(
      'No valid SNP data found',
    );
  });

  it('should handle both rs and i prefixed rsIDs', () => {
    const content = [
      'rs4477212\t1\t82154\tAA',
      'i713426\t1\t817186\tCC',
    ].join('\n');
    const result = parse23andMe(content);
    expect(result['rs4477212']).toBe('AA');
    expect(result['i713426']).toBe('CC');
  });

  it('should skip all common header rows (rsid, id, snp)', () => {
    // All common header keywords are skipped before the rsid prefix check

    // "snp" header is skipped
    const contentWithSnp = [
      'snp\tchromosome\tposition\tgenotype',
      'rs4477212\t1\t82154\tAA',
    ].join('\n');
    const resultSnp = parse23andMe(contentWithSnp);
    expect(Object.keys(resultSnp)).toHaveLength(1);
    expect(resultSnp['rs4477212']).toBe('AA');

    // "rsid" header is skipped
    const contentWithRsid = [
      'rsid\tchromosome\tposition\tgenotype',
      'rs4477212\t1\t82154\tAA',
    ].join('\n');
    const resultRsid = parse23andMe(contentWithRsid);
    expect(Object.keys(resultRsid)).toHaveLength(1);
    expect(resultRsid['rs4477212']).toBe('AA');

    // "id" header is skipped
    const contentWithId = [
      'id\tchromosome\tposition\tgenotype',
      'rs4477212\t1\t82154\tAA',
    ].join('\n');
    const resultId = parse23andMe(contentWithId);
    expect(Object.keys(resultId)).toHaveLength(1);
    expect(resultId['rs4477212']).toBe('AA');
  });

  it('should skip empty genotype entries', () => {
    const content = [
      'rs4477212\t1\t82154\tAA',
      'rs3094315\t1\t752566\t',
      'rs3131972\t1\t752721\tGG',
    ].join('\n');
    const result = parse23andMe(content);
    expect(Object.keys(result)).toHaveLength(2);
  });
});

// ─── AncestryDNA Parser ─────────────────────────────────────────────────────

describe('parseAncestryDNA', () => {
  it('should parse valid AncestryDNA content with separate allele columns', () => {
    const result = parseAncestryDNA(SAMPLE_ANCESTRYDNA);
    expect(result['rs4477212']).toBe('AA');
    expect(result['rs3094315']).toBe('AG');
    expect(result['rs3131972']).toBe('GG');
    expect(result['rs12124819']).toBe('AA');
    expect(result['i713426']).toBe('CC');
    expect(Object.keys(result)).toHaveLength(5);
  });

  it('should concatenate allele1 + allele2 into genotype', () => {
    const content = [
      '# AncestryDNA test',
      'rs4477212\t1\t82154\tA\tG',
    ].join('\n');
    const result = parseAncestryDNA(content);
    expect(result['rs4477212']).toBe('AG');
  });

  it('should skip no-call entries where allele is 0', () => {
    const content = [
      '# AncestryDNA test',
      'rs4477212\t1\t82154\tA\tA',
      'rs3094315\t1\t752566\t0\tA',
      'rs3131972\t1\t752721\tG\t0',
      'rs12124819\t1\t776546\tG\tG',
    ].join('\n');
    const result = parseAncestryDNA(content);
    expect(Object.keys(result)).toHaveLength(2);
    expect(result['rs3094315']).toBeUndefined();
    expect(result['rs3131972']).toBeUndefined();
  });

  it('should skip header rows', () => {
    const content = [
      'rsid\tchromosome\tposition\tallele1\tallele2',
      'rs4477212\t1\t82154\tA\tG',
    ].join('\n');
    const result = parseAncestryDNA(content);
    expect(Object.keys(result)).toHaveLength(1);
  });

  it('should skip comment lines starting with #', () => {
    const content = [
      '#AncestryDNA raw data download',
      '#This file was generated',
      'rs4477212\t1\t82154\tA\tG',
    ].join('\n');
    const result = parseAncestryDNA(content);
    expect(Object.keys(result)).toHaveLength(1);
  });

  it('should uppercase alleles', () => {
    const content = [
      '# AncestryDNA test',
      'rs4477212\t1\t82154\ta\tg',
    ].join('\n');
    const result = parseAncestryDNA(content);
    expect(result['rs4477212']).toBe('AG');
  });

  it('should throw on empty file', () => {
    expect(() => parseAncestryDNA('# comments only')).toThrow(
      'No valid SNP data found',
    );
  });

  it('should skip lines with fewer than 5 columns', () => {
    const content = [
      '# AncestryDNA test',
      'rs4477212\t1\t82154\tA\tG',
      'rs3094315\t1\t752566',
      'rs3131972\t1\t752721\tG\tG',
    ].join('\n');
    const result = parseAncestryDNA(content);
    expect(Object.keys(result)).toHaveLength(2);
  });
});

// ─── MyHeritage Parser ──────────────────────────────────────────────────────

describe('parseMyHeritage', () => {
  it('should parse valid MyHeritage CSV content', () => {
    const result = parseMyHeritage(SAMPLE_MYHERITAGE);
    expect(result['rs4477212']).toBe('AA');
    expect(result['rs3094315']).toBe('AG');
    expect(result['rs3131972']).toBe('GG');
    expect(result['rs12124819']).toBe('AA');
    expect(result['VG00001']).toBe('CT');
    expect(Object.keys(result)).toHaveLength(5);
  });

  it('should handle quoted CSV fields', () => {
    const content = [
      '"RSID","CHROMOSOME","POSITION","RESULT"',
      '"rs4477212","1","82154","AA"',
      '"rs3094315","1","752566","AG"',
    ].join('\n');
    const result = parseMyHeritage(content);
    expect(result['rs4477212']).toBe('AA');
    expect(result['rs3094315']).toBe('AG');
  });

  it('should skip no-call entries (--)', () => {
    const content = [
      'RSID,CHROMOSOME,POSITION,RESULT',
      'rs4477212,1,82154,AA',
      'rs3094315,1,752566,--',
      'rs3131972,1,752721,GG',
    ].join('\n');
    const result = parseMyHeritage(content);
    expect(Object.keys(result)).toHaveLength(2);
    expect(result['rs3094315']).toBeUndefined();
  });

  it('should accept VG-prefixed rsIDs (MyHeritage proprietary)', () => {
    const content = [
      'RSID,CHROMOSOME,POSITION,RESULT',
      'VG00123,1,999999,CT',
      'rs4477212,1,82154,AA',
    ].join('\n');
    const result = parseMyHeritage(content);
    expect(result['VG00123']).toBe('CT');
    expect(result['rs4477212']).toBe('AA');
  });

  it('should skip the header row', () => {
    const content = [
      'RSID,CHROMOSOME,POSITION,RESULT',
      'rs4477212,1,82154,AA',
    ].join('\n');
    const result = parseMyHeritage(content);
    expect(Object.keys(result)).toHaveLength(1);
  });

  it('should accept i-prefixed rsIDs', () => {
    const content = [
      'RSID,CHROMOSOME,POSITION,RESULT',
      'i713426,1,817186,CC',
    ].join('\n');
    const result = parseMyHeritage(content);
    expect(result['i713426']).toBe('CC');
  });

  it('should throw on empty file', () => {
    expect(() => parseMyHeritage('RSID,CHROMOSOME,POSITION,RESULT')).toThrow(
      'No valid SNP data found',
    );
  });

  it('should skip empty genotype entries', () => {
    const content = [
      'RSID,CHROMOSOME,POSITION,RESULT',
      'rs4477212,1,82154,AA',
      'rs3094315,1,752566,',
      'rs3131972,1,752721,GG',
    ].join('\n');
    const result = parseMyHeritage(content);
    expect(Object.keys(result)).toHaveLength(2);
  });
});

// ─── VCF Parser ─────────────────────────────────────────────────────────────

describe('parseVcf', () => {
  it('should parse valid VCF content', () => {
    const result = parseVcf(SAMPLE_VCF);
    expect(result['rs4477212']).toBe('AA');
    expect(result['rs3094315']).toBe('AG');
    expect(result['rs3131972']).toBe('GG');
    expect(result['rs12124819']).toBe('CC');
    expect(Object.keys(result)).toHaveLength(4);
  });

  it('should correctly map GT allele indices to nucleotides', () => {
    const content = [
      '##fileformat=VCFv4.1',
      '#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\tFORMAT\tSAMPLE',
      '1\t100\trs100\tA\tG\t30\tPASS\t.\tGT\t0/0',    // AA (ref/ref)
      '1\t200\trs200\tA\tG\t30\tPASS\t.\tGT\t0/1',    // AG (ref/alt)
      '1\t300\trs300\tA\tG\t30\tPASS\t.\tGT\t1/1',    // GG (alt/alt)
    ].join('\n');
    const result = parseVcf(content);
    expect(result['rs100']).toBe('AA');
    expect(result['rs200']).toBe('AG');
    expect(result['rs300']).toBe('GG');
  });

  it('should skip indels (multi-base REF or ALT)', () => {
    const content = [
      '##fileformat=VCFv4.1',
      '#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\tFORMAT\tSAMPLE',
      '1\t100\trs100\tA\tG\t30\tPASS\t.\tGT\t0/1',       // SNP - kept
      '1\t200\trs200\tAT\tG\t30\tPASS\t.\tGT\t0/1',      // Indel REF - skipped
      '1\t300\trs300\tA\tGTT\t30\tPASS\t.\tGT\t0/1',     // Indel ALT - skipped
    ].join('\n');
    const result = parseVcf(content);
    expect(Object.keys(result)).toHaveLength(1);
    expect(result['rs100']).toBe('AG');
  });

  it('should skip no-call genotypes (./.)', () => {
    const content = [
      '##fileformat=VCFv4.1',
      '#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\tFORMAT\tSAMPLE',
      '1\t100\trs100\tA\tG\t30\tPASS\t.\tGT\t0/1',
      '1\t200\trs200\tA\tG\t30\tPASS\t.\tGT\t./.',
      '1\t300\trs300\tA\tG\t30\tPASS\t.\tGT\t.|.',
    ].join('\n');
    const result = parseVcf(content);
    expect(Object.keys(result)).toHaveLength(1);
    expect(result['rs100']).toBe('AG');
  });

  it('should only include variants with rsIDs', () => {
    const content = [
      '##fileformat=VCFv4.1',
      '#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\tFORMAT\tSAMPLE',
      '1\t100\trs100\tA\tG\t30\tPASS\t.\tGT\t0/1',
      '1\t200\t.\tA\tG\t30\tPASS\t.\tGT\t0/1',      // "." ID - skipped
      '1\t300\tCHR1_300\tA\tG\t30\tPASS\t.\tGT\t0/1', // No rs prefix - skipped
    ].join('\n');
    const result = parseVcf(content);
    expect(Object.keys(result)).toHaveLength(1);
    expect(result['rs100']).toBe('AG');
  });

  it('should handle phased (|) and unphased (/) GT separators', () => {
    const content = [
      '##fileformat=VCFv4.1',
      '#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\tFORMAT\tSAMPLE',
      '1\t100\trs100\tA\tG\t30\tPASS\t.\tGT\t0/1',   // unphased
      '1\t200\trs200\tA\tG\t30\tPASS\t.\tGT\t1|0',   // phased
    ].join('\n');
    const result = parseVcf(content);
    expect(result['rs100']).toBe('AG');
    expect(result['rs200']).toBe('GA');
  });

  it('should throw on empty VCF data', () => {
    const content = [
      '##fileformat=VCFv4.1',
      '#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\tFORMAT\tSAMPLE',
    ].join('\n');
    expect(() => parseVcf(content)).toThrow('No valid SNP data found');
  });

  it('should handle multi-allelic ALT correctly', () => {
    const content = [
      '##fileformat=VCFv4.1',
      '#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\tFORMAT\tSAMPLE',
      '1\t100\trs100\tA\tG,C\t30\tPASS\t.\tGT\t1/2',  // G and C alts
    ].join('\n');
    const result = parseVcf(content);
    expect(result['rs100']).toBe('GC');
  });

  it('should skip lines before the #CHROM header', () => {
    const content = [
      '##fileformat=VCFv4.1',
      '##contig=<ID=1>',
      'not_a_data_line_before_header',
      '#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\tFORMAT\tSAMPLE',
      '1\t100\trs100\tA\tG\t30\tPASS\t.\tGT\t0/1',
    ].join('\n');
    const result = parseVcf(content);
    expect(Object.keys(result)).toHaveLength(1);
  });
});

// ─── Universal Parser ───────────────────────────────────────────────────────

describe('parseGeneticFile', () => {
  it('should auto-detect and parse 23andMe files', () => {
    const [genotypes, format] = parseGeneticFile(SAMPLE_23ANDME);
    expect(format).toBe('23andme');
    expect(genotypes['rs4477212']).toBe('AA');
    expect(Object.keys(genotypes).length).toBeGreaterThan(0);
  });

  it('should auto-detect and parse AncestryDNA files', () => {
    const [genotypes, format] = parseGeneticFile(SAMPLE_ANCESTRYDNA);
    expect(format).toBe('ancestrydna');
    expect(genotypes['rs4477212']).toBe('AA');
  });

  it('should auto-detect and parse VCF files', () => {
    const [genotypes, format] = parseGeneticFile(SAMPLE_VCF);
    expect(format).toBe('vcf');
    expect(Object.keys(genotypes).length).toBeGreaterThan(0);
  });

  it('should auto-detect and parse MyHeritage files', () => {
    const [genotypes, format] = parseGeneticFile(SAMPLE_MYHERITAGE);
    expect(format).toBe('myheritage');
    expect(genotypes['rs4477212']).toBe('AA');
  });

  it('should throw descriptive error for unrecognized formats', () => {
    expect(() => parseGeneticFile('random garbage data')).toThrow(
      'Unrecognized genetic data format',
    );
  });

  it('should return both genotype map and detected format', () => {
    const result = parseGeneticFile(SAMPLE_23ANDME);
    expect(Array.isArray(result)).toBe(true);
    expect(result).toHaveLength(2);
    expect(typeof result[0]).toBe('object');
    expect(typeof result[1]).toBe('string');
  });
});

// ─── Genotype Statistics ────────────────────────────────────────────────────

describe('getGenotypeStats', () => {
  it('should correctly count homozygous and heterozygous genotypes', () => {
    const genotypes = {
      rs1: 'AA',  // homozygous
      rs2: 'AG',  // heterozygous
      rs3: 'GG',  // homozygous
      rs4: 'CT',  // heterozygous
      rs5: 'TT',  // homozygous
    };
    const stats = getGenotypeStats(genotypes);
    expect(stats.totalSnps).toBe(5);
    expect(stats.homozygousCount).toBe(3);
    expect(stats.heterozygousCount).toBe(2);
  });

  it('should return zero counts for empty genotype map', () => {
    const stats = getGenotypeStats({});
    expect(stats.totalSnps).toBe(0);
    expect(stats.homozygousCount).toBe(0);
    expect(stats.heterozygousCount).toBe(0);
    expect(stats.genotypeDistribution).toEqual({});
  });

  it('should count single-character genotypes as homozygous (chrX/Y males)', () => {
    const genotypes = {
      rs1: 'A',   // single allele, hemi
      rs2: 'AG',  // heterozygous
    };
    const stats = getGenotypeStats(genotypes);
    expect(stats.homozygousCount).toBe(1);
    expect(stats.heterozygousCount).toBe(1);
  });

  it('should build a genotype distribution', () => {
    const genotypes = {
      rs1: 'AA',
      rs2: 'AA',
      rs3: 'AG',
      rs4: 'GG',
    };
    const stats = getGenotypeStats(genotypes);
    expect(stats.genotypeDistribution['AA']).toBe(2);
    expect(stats.genotypeDistribution['AG']).toBe(1);
    expect(stats.genotypeDistribution['GG']).toBe(1);
  });
});

// ─── buildParseResultSummary ─────────────────────────────────────────────────

describe('buildParseResultSummary', () => {
  it('should compute skippedLines from rawLineCount', () => {
    const genotypes = { rs1: 'AA', rs2: 'AG', rs3: 'GG' };
    // 10 raw lines, 3 valid SNPs -> 7 skipped (comments, headers, blank, no-calls)
    const summary = buildParseResultSummary(genotypes, '23andme', {}, 10);
    expect(summary.totalSnps).toBe(3);
    expect(summary.validSnps).toBe(3);
    expect(summary.skippedLines).toBe(7);
    expect(summary.format).toBe('23andme');
  });

  it('should default skippedLines to 0 when rawLineCount is not provided', () => {
    const genotypes = { rs1: 'AA', rs2: 'AG' };
    const summary = buildParseResultSummary(genotypes, 'vcf');
    expect(summary.skippedLines).toBe(0);
  });

  it('should include fileName in metadata when provided', () => {
    const genotypes = { rs1: 'AA' };
    const summary = buildParseResultSummary(genotypes, 'ancestrydna', { fileName: 'test.txt' });
    expect(summary.metadata['fileName']).toBe('test.txt');
  });

  it('should handle empty genotype map', () => {
    const summary = buildParseResultSummary({}, 'unknown', {}, 5);
    expect(summary.totalSnps).toBe(0);
    expect(summary.skippedLines).toBe(5);
  });
});

// ─── Validation Functions ──────────────────────────────────────────────────

describe('validation functions', () => {
  // ── validate23andMe ──────────────────────────────────────────────────────

  describe('validate23andMe', () => {
    it('should return [true, ""] for a valid 23andMe file', () => {
      const [isValid, err] = validate23andMe(SAMPLE_23ANDME);
      expect(isValid).toBe(true);
      expect(err).toBe('');
    });

    it('should fail for a file that is too short (< 2 lines)', () => {
      const [isValid, err] = validate23andMe('single line only');
      expect(isValid).toBe(false);
      expect(err).toContain('too short');
    });

    it('should fail when missing 23andMe header signature', () => {
      const content = [
        '# Some random genetic tool',
        '# Not from the expected provider',
        'ABCD\tsome\tgarbage\tdata',
      ].join('\n');
      const [isValid, err] = validate23andMe(content);
      expect(isValid).toBe(false);
      expect(err).toContain('missing header signature');
    });

    it('should pass with rsid+chromosome in header but no 23andMe keyword', () => {
      const content = [
        '# rsid\tchromosome\tposition\tgenotype',
        'rs4477212\t1\t82154\tAA',
        'rs3094315\t1\t752566\tAG',
      ].join('\n');
      const [isValid, err] = validate23andMe(content);
      expect(isValid).toBe(true);
      expect(err).toBe('');
    });
  });

  // ── validateAncestryDNA ──────────────────────────────────────────────────

  describe('validateAncestryDNA', () => {
    it('should return [true, ""] for a valid AncestryDNA file', () => {
      const [isValid, err] = validateAncestryDNA(SAMPLE_ANCESTRYDNA);
      expect(isValid).toBe(true);
      expect(err).toBe('');
    });

    it('should fail for a file that is too short', () => {
      const [isValid, err] = validateAncestryDNA('one line');
      expect(isValid).toBe(false);
      expect(err).toContain('too short');
    });

    it('should fail when missing AncestryDNA header signature', () => {
      const content = [
        '# Some random tool',
        'rs4477212\t1\t82154\tA\tG',
        'rs3094315\t1\t752566\tA\tC',
      ].join('\n');
      const [isValid, err] = validateAncestryDNA(content);
      expect(isValid).toBe(false);
      expect(err).toContain('missing header signature');
    });

    it('should pass with allele1/allele2 header even without AncestryDNA keyword', () => {
      const content = [
        'rsid\tchromosome\tposition\tallele1\tallele2',
        'rs4477212\t1\t82154\tA\tG',
        'rs3094315\t1\t752566\tA\tC',
      ].join('\n');
      const [isValid, err] = validateAncestryDNA(content);
      expect(isValid).toBe(true);
      expect(err).toBe('');
    });
  });

  // ── validateMyHeritage ───────────────────────────────────────────────────

  describe('validateMyHeritage', () => {
    it('should return [true, ""] for a valid MyHeritage file', () => {
      const [isValid, err] = validateMyHeritage(SAMPLE_MYHERITAGE);
      expect(isValid).toBe(true);
      expect(err).toBe('');
    });

    it('should fail for a file that is too short', () => {
      const [isValid, err] = validateMyHeritage('single line');
      expect(isValid).toBe(false);
      expect(err).toContain('too short');
    });

    it('should fail when missing RSID,CHROMOSOME,POSITION,RESULT header', () => {
      const content = [
        'random,header,here,values',
        'notanrsid,1,82154,ZZ',
      ].join('\n');
      const [isValid, err] = validateMyHeritage(content);
      expect(isValid).toBe(false);
      expect(err).toContain('missing');
    });

    it('should pass with proper CSV header', () => {
      const content = [
        'RSID,CHROMOSOME,POSITION,RESULT',
        'rs4477212,1,82154,AA',
        'rs3094315,1,752566,AG',
      ].join('\n');
      const [isValid, err] = validateMyHeritage(content);
      expect(isValid).toBe(true);
      expect(err).toBe('');
    });
  });

  // ── validateVcf ──────────────────────────────────────────────────────────

  describe('validateVcf', () => {
    it('should return [true, ""] for a valid VCF file', () => {
      const [isValid, err] = validateVcf(SAMPLE_VCF);
      expect(isValid).toBe(true);
      expect(err).toBe('');
    });

    it('should fail when missing ##fileformat line', () => {
      const content = [
        '##source=myApp',
        '#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\tFORMAT\tSAMPLE',
        '1\t100\trs100\tA\tG\t30\tPASS\t.\tGT\t0/1',
      ].join('\n');
      const [isValid, err] = validateVcf(content);
      expect(isValid).toBe(false);
      expect(err).toContain('##fileformat=VCF');
    });

    it('should fail when missing #CHROM header line', () => {
      const content = [
        '##fileformat=VCFv4.1',
        '##source=myApp',
        '1\t100\trs100\tA\tG\t30\tPASS\t.\tGT\t0/1',
      ].join('\n');
      const [isValid, err] = validateVcf(content);
      expect(isValid).toBe(false);
      expect(err).toContain('#CHROM');
    });

    it('should fail for a file that is too short', () => {
      const [isValid, err] = validateVcf('single line');
      expect(isValid).toBe(false);
      // too short falls through to missing fileformat check
      expect(isValid).toBe(false);
    });

    it('should fail when #CHROM header has insufficient columns', () => {
      const content = [
        '##fileformat=VCFv4.1',
        '#CHROM\tPOS\tID',
        '1\t100\trs100',
      ].join('\n');
      const [isValid, err] = validateVcf(content);
      expect(isValid).toBe(false);
      expect(err).toContain('columns');
    });
  });

  // ── validateGeneticFile ──────────────────────────────────────────────────

  describe('validateGeneticFile', () => {
    it('should auto-detect and validate 23andMe files', () => {
      const [isValid, err, fmt] = validateGeneticFile(SAMPLE_23ANDME);
      expect(isValid).toBe(true);
      expect(err).toBe('');
      expect(fmt).toBe('23andme');
    });

    it('should auto-detect and validate AncestryDNA files', () => {
      const [isValid, err, fmt] = validateGeneticFile(SAMPLE_ANCESTRYDNA);
      expect(isValid).toBe(true);
      expect(err).toBe('');
      expect(fmt).toBe('ancestrydna');
    });

    it('should auto-detect and validate MyHeritage files', () => {
      const [isValid, err, fmt] = validateGeneticFile(SAMPLE_MYHERITAGE);
      expect(isValid).toBe(true);
      expect(err).toBe('');
      expect(fmt).toBe('myheritage');
    });

    it('should auto-detect and validate VCF files', () => {
      const [isValid, err, fmt] = validateGeneticFile(SAMPLE_VCF);
      expect(isValid).toBe(true);
      expect(err).toBe('');
      expect(fmt).toBe('vcf');
    });

    it('should return false with "unknown" format for unrecognized files', () => {
      const [isValid, err, fmt] = validateGeneticFile('random garbage data');
      expect(isValid).toBe(false);
      expect(err).toContain('Unrecognized');
      expect(fmt).toBe('unknown');
    });
  });
});
