/**
 * Parser / Decompression Fuzzing Tests — Q22 (Stream Q Sprint 3)
 *
 * Tests parser robustness against malicious, malformed, and adversarial input.
 *
 * Security scenarios covered:
 *  1. Zip bomb ratio enforcement (>100:1 ratio aborts)
 *  2. Truncated files (file cut mid-line) → graceful error, not crash
 *  3. Garbage/binary headers → graceful error, not crash
 *  4. Massive uncompressed sizes (very long lines) → handled without OOM
 *  5. Empty file (0 bytes) → empty result or error, not crash
 *  6. Binary file (non-text) → graceful error
 *  7. Null bytes embedded in text → handled
 *  8. Extremely long rsIDs → rejected or truncated
 *  9. 30s timeout enforcement (it.todo — timeout not yet enforced on parse path)
 *
 * These tests use the parser's string-based API directly to avoid needing
 * the full decompression pipeline (which requires browser APIs not present in Node).
 * For decompression ratio tests we test the detectCompression + DecompressionError
 * interfaces directly.
 *
 * All tests assert that the parser returns an error result rather than
 * throwing an uncaught exception. Acceptable outcomes:
 *  - Returns an Error via rejection/throw (caught with try/catch)
 *  - Returns an empty GenotypeMap ({}), never crashes Node
 *
 * Note on Vitest APIs:
 *  - Use `it.todo('description')` for unimplemented/deferred tests (Vitest equivalent of test.fixme)
 *  - Use the timeout number as the third argument to `it()` for slow tests
 */

import { describe, it, expect } from 'vitest';
import {
  detectFormat,
  parse23andMe,
  parseAncestryDNA,
  parseMyHeritage,
  parseVcf,
  parseGeneticFile,
} from '../src/parser';
import {
  detectCompression,
  DecompressionError,
} from '../src/decompression';
import { generateSyntheticGenome } from '../src/test-utils/synthetic-factory';

// ─── Helpers ─────────────────────────────────────────────────────────────────

/**
 * Assert that a parse call either throws an Error (expected for invalid input)
 * or resolves gracefully without crashing the process.
 * The returned Error (if any) is also returned for further assertions.
 */
async function expectGracefulError(fn: () => unknown): Promise<Error | null> {
  try {
    const result = await Promise.resolve(fn());
    // If the parser returned something without throwing, that is also acceptable
    // as long as the process did not crash. A valid empty object is acceptable
    // only if there was truly nothing parseable.
    if (result !== undefined && result !== null) {
      return null;
    }
    return null;
  } catch (err) {
    // Must be an Error instance — not an uncaught anything-goes crash
    expect(err).toBeInstanceOf(Error);
    return err as Error;
  }
}

/**
 * Build a string of repeating ASCII garbage (non-genetic-data bytes).
 */
function makeGarbage(length: number): string {
  const chars = '!@#$%^&*()_+=-[]{};:\'"<>?,./~`|\\';
  let result = '';
  for (let i = 0; i < length; i++) {
    result += chars[i % chars.length];
  }
  return result;
}

/**
 * Build a string with null bytes embedded in valid-looking 23andMe content.
 */
function make23andMeWithNulls(): string {
  return [
    '# This data file generated by 23andMe',
    '# rsid\tchromosome\tposition\tgenotype',
    `rs111\t1\t100\tAA`,
    `rs222\t1\t200\tGG`,
    `rs\x00333\t1\t300\tAT`, // null byte in rsid
    `rs444\t1\t400\tCC`,
  ].join('\n');
}

// ─── 1. Zip Bomb Ratio Enforcement ──────────────────────────────────────────

describe('Fuzzing — Zip Bomb Ratio Detection', () => {
  /**
   * The decompression module enforces maxRatio (default 100:1).
   * We test the DecompressionError class and the ratio logic directly since
   * actual browser-based decompression is not available in Node/Vitest.
   */

  it('DecompressionError is constructable with RATIO_EXCEEDED code', () => {
    const err = new DecompressionError(
      'RATIO_EXCEEDED',
      'Compression ratio (101:1) exceeds maximum allowed (100:1).',
    );
    expect(err).toBeInstanceOf(Error);
    expect(err).toBeInstanceOf(DecompressionError);
    expect(err.code).toBe('RATIO_EXCEEDED');
    expect(err.name).toBe('DecompressionError');
    expect(err.message).toContain('101:1');
  });

  it('DecompressionError is constructable with SIZE_EXCEEDED code', () => {
    const err = new DecompressionError(
      'SIZE_EXCEEDED',
      'Decompressed size exceeds maximum.',
    );
    expect(err.code).toBe('SIZE_EXCEEDED');
  });

  it('DecompressionError is constructable with TIMEOUT code', () => {
    const err = new DecompressionError('TIMEOUT', 'Decompression timed out after 30000 ms.');
    expect(err.code).toBe('TIMEOUT');
  });

  it('DecompressionError is constructable with CORRUPT code', () => {
    const err = new DecompressionError('CORRUPT', 'No genetic data file found inside ZIP.');
    expect(err.code).toBe('CORRUPT');
  });

  it('DecompressionError is constructable with UNSUPPORTED_FORMAT code', () => {
    const err = new DecompressionError(
      'UNSUPPORTED_FORMAT',
      'DecompressionStream API is not available.',
    );
    expect(err.code).toBe('UNSUPPORTED_FORMAT');
  });

  /**
   * Simulate ratio check logic in isolation: if originalSize > 0 and
   * decompressedSize / originalSize > maxRatio, a RATIO_EXCEEDED error
   * must be constructable and carry the correct metadata.
   */
  it('ratio check: 101:1 ratio would trigger RATIO_EXCEEDED', () => {
    const originalSize = 1000;
    const decompressedSize = 101000; // 101:1 ratio
    const maxRatio = 100;

    const ratio = decompressedSize / originalSize;
    expect(ratio).toBeGreaterThan(maxRatio);

    const err = new DecompressionError(
      'RATIO_EXCEEDED',
      `Compression ratio (${Math.round(ratio)}:1) exceeds maximum allowed (${maxRatio}:1).`,
    );
    expect(err.code).toBe('RATIO_EXCEEDED');
    expect(err.message).toContain('101:1');
  });

  it('ratio check: 99:1 ratio does NOT trigger RATIO_EXCEEDED', () => {
    const originalSize = 1000;
    const decompressedSize = 99000; // 99:1 ratio
    const maxRatio = 100;

    const ratio = decompressedSize / originalSize;
    expect(ratio).toBeLessThanOrEqual(maxRatio);
  });

  /**
   * Deferred: zip bomb test requires browser environment (DecompressionStream API).
   * The monitoring stream in decompression.ts enforces this in production via
   * createMonitoredStream which checks ratio > maxRatio on each chunk.
   */
  it.todo(
    'zip bomb (>100:1 ratio) aborts decompression and throws RATIO_EXCEEDED [requires browser env]',
  );
});

// ─── 2. Truncated Files ──────────────────────────────────────────────────────

describe('Fuzzing — Truncated Files', () => {
  it('23andMe file cut mid-line throws graceful error (no crash)', async () => {
    // Generate a valid 100-variant file and cut it mid-line
    const full = generateSyntheticGenome({ format: '23andme', seed: 1, variantCount: 100 });
    // Cut at the 60% mark — likely mid-line
    const truncated = full.slice(0, Math.floor(full.length * 0.6));

    const err = await expectGracefulError(() => parse23andMe(truncated));
    // Either parses some data (lines before truncation) or throws with a message.
    // It must NOT crash the runtime.
    if (err !== null) {
      expect(err.message).toBeTruthy();
    }
    // No uncaught error = pass
  });

  it('AncestryDNA file cut mid-line throws graceful error (no crash)', async () => {
    const full = generateSyntheticGenome({ format: 'ancestrydna', seed: 2, variantCount: 100 });
    const truncated = full.slice(0, Math.floor(full.length * 0.5));

    const err = await expectGracefulError(() => parseAncestryDNA(truncated));
    if (err !== null) {
      expect(err.message).toBeTruthy();
    }
  });

  it('MyHeritage file cut mid-line throws graceful error (no crash)', async () => {
    const full = generateSyntheticGenome({ format: 'myheritage', seed: 3, variantCount: 100 });
    const truncated = full.slice(0, Math.floor(full.length * 0.7));

    const err = await expectGracefulError(() => parseMyHeritage(truncated));
    if (err !== null) {
      expect(err.message).toBeTruthy();
    }
  });

  it('VCF file cut mid-line throws graceful error (no crash)', async () => {
    const full = generateSyntheticGenome({ format: 'vcf', seed: 4, variantCount: 100 });
    // Cut in the data section
    const truncated = full.slice(0, Math.floor(full.length * 0.55));

    const err = await expectGracefulError(() => parseVcf(truncated));
    if (err !== null) {
      expect(err.message).toBeTruthy();
    }
  });

  it('file cut to only header comments (no data rows) → throws "no SNP data" error', () => {
    const onlyComments = [
      '# This data file generated by 23andMe',
      '# rsid\tchromosome\tposition\tgenotype',
    ].join('\n');

    expect(() => parse23andMe(onlyComments)).toThrow(/no valid snp data/i);
  });

  it('file cut to exactly 1 byte → graceful error (no crash)', async () => {
    const singleByte = '#';
    const err = await expectGracefulError(() => parse23andMe(singleByte));
    if (err !== null) {
      expect(err.message).toBeTruthy();
    }
  });
});

// ─── 3. Garbage Headers ──────────────────────────────────────────────────────

describe('Fuzzing — Garbage Headers', () => {
  it('random ASCII garbage → detectFormat returns "unknown"', () => {
    const garbage = makeGarbage(500);
    const format = detectFormat(garbage);
    expect(format).toBe('unknown');
  });

  it('random ASCII garbage → parseGeneticFile throws descriptive error', () => {
    const garbage = makeGarbage(500);
    expect(() => parseGeneticFile(garbage)).toThrow(
      /unrecognized genetic data format/i,
    );
  });

  it('null-only content → detectFormat returns "unknown" (no crash)', () => {
    const nullContent = '\x00\x00\x00\x00\x00';
    const format = detectFormat(nullContent);
    expect(format).toBe('unknown');
  });

  it('null-only content → parseGeneticFile throws descriptive error', () => {
    const nullContent = '\x00\x00\x00\x00\x00';
    expect(() => parseGeneticFile(nullContent)).toThrow(
      /unrecognized genetic data format/i,
    );
  });

  it('repeated special characters → detectFormat returns "unknown" (no crash)', () => {
    const specialChars = '\xFF\xFE\xFD\xFC'.repeat(100);
    const format = detectFormat(specialChars);
    expect(format).toBe('unknown');
  });

  it('content that looks like JSON → detectFormat returns "unknown"', () => {
    const jsonContent = JSON.stringify({ rsid: 'rs123', genotype: 'AG', chr: '1' });
    const format = detectFormat(jsonContent.repeat(10));
    expect(format).toBe('unknown');
  });

  it('HTML content → detectFormat returns "unknown" (no crash)', () => {
    const html = '<html><body><p>This is not a genetic data file.</p></body></html>';
    const format = detectFormat(html);
    expect(format).toBe('unknown');
  });

  it('random garbage that triggers parse23andMe directly → throws gracefully', async () => {
    const garbage = makeGarbage(1000);
    const err = await expectGracefulError(() => parse23andMe(garbage));
    // Should throw "No valid SNP data found"
    if (err !== null) {
      expect(err.message).toMatch(/no valid snp data/i);
    }
  });
});

// ─── 4. Massive Uncompressed Sizes (Very Long Lines) ────────────────────────

describe('Fuzzing — Massive Uncompressed Sizes / Long Lines', () => {
  it(
    '23andMe file with a 1MB comment line → parses without OOM (skips comment)',
    () => {
      // A 1MB comment line should be skipped (starts with '#') without crash
      const oneMbComment = '# ' + 'X'.repeat(1_000_000);
      const content = [
        oneMbComment,
        '# rsid\tchromosome\tposition\tgenotype',
        'rs111\t1\t100\tAA',
        'rs222\t1\t200\tGG',
      ].join('\n');

      // Should parse fine — the 1MB comment line is skipped
      const result = parse23andMe(content);
      expect(Object.keys(result).length).toBe(2);
      expect(result['rs111']).toBe('AA');
    },
    30_000,
  );

  it(
    '23andMe file with a 100KB rsid → skipped or parsed, but no crash',
    () => {
      // A very long rsID that starts with 'rs' but is 100KB
      const longRsid = 'rs' + 'A'.repeat(100_000);
      const content = [
        '# This data file generated by 23andMe',
        '# rsid\tchromosome\tposition\tgenotype',
        `${longRsid}\t1\t100\tAA`, // extremely long rsid
        'rs222\t1\t200\tGG', // valid line — this is the only parseable variant
      ].join('\n');

      // The parser must not crash. The long rsid will either be accepted or rejected.
      // Either outcome is acceptable as long as there is no crash.
      let result: Record<string, string> | null = null;
      let caughtError: Error | null = null;
      try {
        result = parse23andMe(content);
      } catch (err) {
        caughtError = err as Error;
      }

      if (caughtError !== null) {
        expect(caughtError).toBeInstanceOf(Error);
      } else {
        // At minimum, the valid rs222 line should be present
        expect(result).not.toBeNull();
        expect(result!['rs222']).toBe('GG');
      }
    },
    30_000,
  );

  it(
    '23andMe file with 10000 valid lines + 1 extremely long data line → no crash',
    () => {
      const lines: string[] = [
        '# This data file generated by 23andMe',
        '# rsid\tchromosome\tposition\tgenotype',
      ];
      for (let i = 0; i < 9999; i++) {
        lines.push(`rs${1000000 + i}\t1\t${100000 + i}\tAA`);
      }
      // One very long line (100KB data in the genotype field — will be skipped as invalid genotype)
      lines.push(`rs9999999\t1\t999999\t${'A'.repeat(100_000)}`);

      const content = lines.join('\n');
      // Should parse the valid lines without crashing.
      // The parser accepts any non-empty genotype, so the 100KB genotype line
      // may also be parsed (rs9999999 with a 100K-char genotype).
      // We assert: no crash, and at least 9999 lines were parsed.
      const result = parse23andMe(content);
      expect(Object.keys(result).length).toBeGreaterThanOrEqual(9999);
    },
    30_000,
  );

  it(
    'AncestryDNA with a 500KB genotype value → handled without crash',
    () => {
      const content = [
        '#AncestryDNA raw data download',
        '#This file was generated by AncestryDNA',
        'rsid\tchromosome\tposition\tallele1\tallele2',
        `rs111\t1\t100\t${'A'.repeat(500_000)}\tG`, // 500KB allele1
        'rs222\t1\t200\tA\tG', // valid fallback
      ].join('\n');

      // AncestryDNA parser: allele1.toUpperCase().trim() is 500K chars.
      // A 500KB allele1 will be concatenated with G, producing a 500KB+ genotype.
      // The rs222 line will still parse.
      let result: Record<string, string> | null = null;
      let caughtError: Error | null = null;
      try {
        result = parseAncestryDNA(content);
      } catch (err) {
        caughtError = err as Error;
      }

      // Must not crash the process
      if (caughtError !== null) {
        expect(caughtError).toBeInstanceOf(Error);
      } else {
        expect(result).not.toBeNull();
      }
    },
    30_000,
  );
});

// ─── 5. Empty File ────────────────────────────────────────────────────────────

describe('Fuzzing — Empty File', () => {
  it('empty string → detectFormat returns "unknown" (no crash)', () => {
    const format = detectFormat('');
    expect(format).toBe('unknown');
  });

  it('empty string → parseGeneticFile throws descriptive error (no crash)', () => {
    expect(() => parseGeneticFile('')).toThrow(/unrecognized genetic data format/i);
  });

  it('empty string → parse23andMe throws "no valid SNP data" (no crash)', () => {
    expect(() => parse23andMe('')).toThrow(/no valid snp data/i);
  });

  it('empty string → parseAncestryDNA throws "no valid SNP data" (no crash)', () => {
    expect(() => parseAncestryDNA('')).toThrow(/no valid snp data/i);
  });

  it('empty string → parseMyHeritage throws "no valid SNP data" (no crash)', () => {
    expect(() => parseMyHeritage('')).toThrow(/no valid snp data/i);
  });

  it('empty string → parseVcf throws "no valid SNP data" (no crash)', () => {
    expect(() => parseVcf('')).toThrow(/no valid snp data/i);
  });

  it('whitespace-only content → detectFormat returns "unknown"', () => {
    const format = detectFormat('   \n\t\n   ');
    expect(format).toBe('unknown');
  });

  it('whitespace-only content → parse23andMe throws (no crash)', () => {
    expect(() => parse23andMe('   \n\t\n   ')).toThrow();
  });
});

// ─── 6. Binary File (Non-Text) ───────────────────────────────────────────────

describe('Fuzzing — Binary File / Non-Text Input', () => {
  it('binary magic bytes (PDF) → detectCompression returns "raw"', () => {
    // PDF starts with %PDF (0x25 0x50 0x44 0x46)
    const pdfHeader = new Uint8Array([0x25, 0x50, 0x44, 0x46, 0x2d, 0x31, 0x2e]);
    const format = detectCompression('report.pdf', pdfHeader);
    expect(format).toBe('raw');
  });

  it('binary-looking string content → detectFormat returns "unknown"', () => {
    // Simulate binary data as a string (non-printable characters)
    let binaryStr = '';
    for (let i = 0; i < 200; i++) {
      binaryStr += String.fromCharCode(i % 256);
    }
    const format = detectFormat(binaryStr);
    expect(format).toBe('unknown');
  });

  it('binary content → parseGeneticFile throws descriptive error (no crash)', () => {
    let binaryStr = '';
    for (let i = 1; i < 200; i++) {
      // Avoid null byte to keep as string
      binaryStr += String.fromCharCode(i);
    }
    expect(() => parseGeneticFile(binaryStr)).toThrow(/unrecognized genetic data format/i);
  });

  it('PNG magic bytes → detectCompression returns "raw"', () => {
    // PNG: 0x89 0x50 0x4E 0x47
    const pngHeader = new Uint8Array([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]);
    const format = detectCompression('image.png', pngHeader);
    // PNG magic doesn't match ZIP (0x50 0x4B) or GZIP (0x1F 0x8B)
    expect(format).toBe('raw');
  });

  it('JPEG magic bytes → detectCompression returns "raw"', () => {
    // JPEG: 0xFF 0xD8
    const jpegHeader = new Uint8Array([0xff, 0xd8, 0xff, 0xe0]);
    const format = detectCompression('photo.jpg', jpegHeader);
    expect(format).toBe('raw');
  });
});

// ─── 7. Null Bytes Embedded in Text ──────────────────────────────────────────

describe('Fuzzing — Null Bytes Embedded in Text', () => {
  it('23andMe with null byte in rsid → that entry skipped, valid entries parsed', () => {
    const content = make23andMeWithNulls();

    // The parser should not crash. The null-byte rsid may be skipped.
    let result: Record<string, string> | null = null;
    let caughtError: Error | null = null;
    try {
      result = parse23andMe(content);
    } catch (err) {
      caughtError = err as Error;
    }

    if (caughtError !== null) {
      expect(caughtError).toBeInstanceOf(Error);
    } else {
      // At minimum, the clean entries (rs111, rs222, rs444) should be present.
      expect(result).not.toBeNull();
      // rs111, rs222, rs444 are clean
      expect(result!['rs111']).toBe('AA');
      expect(result!['rs222']).toBe('GG');
      expect(result!['rs444']).toBe('CC');
    }
  });

  it('23andMe with null byte in genotype → that entry skipped', () => {
    const content = [
      '# This data file generated by 23andMe',
      '# rsid\tchromosome\tposition\tgenotype',
      'rs111\t1\t100\tAA',
      'rs222\t1\t200\tG\x00G', // null byte in genotype
      'rs333\t1\t300\tCC',
    ].join('\n');

    // Must not crash.
    let result: Record<string, string> | null = null;
    let caughtError: Error | null = null;
    try {
      result = parse23andMe(content);
    } catch (err) {
      caughtError = err as Error;
    }

    if (caughtError !== null) {
      expect(caughtError).toBeInstanceOf(Error);
    } else {
      expect(result!['rs111']).toBe('AA');
      expect(result!['rs333']).toBe('CC');
    }
  });

  it('content that is all null bytes → graceful error (no crash)', () => {
    const nullContent = '\x00'.repeat(1000);
    const format = detectFormat(nullContent);
    expect(format).toBe('unknown');

    expect(() => parseGeneticFile(nullContent)).toThrow(/unrecognized genetic data format/i);
  });
});

// ─── 8. Extremely Long rsIDs ─────────────────────────────────────────────────

describe('Fuzzing — Extremely Long rsIDs', () => {
  it('rsid with 1000 characters → line skipped or truncated gracefully', () => {
    const longRsid = 'rs' + '1'.repeat(998); // 1000 chars total, starts with 'rs'
    const content = [
      '# This data file generated by 23andMe',
      '# rsid\tchromosome\tposition\tgenotype',
      `${longRsid}\t1\t100\tAA`, // 1000-char rsid
      'rs222\t1\t200\tGG', // valid entry
    ].join('\n');

    // Parser may or may not accept a 1000-char rsid. Either is fine.
    // It MUST NOT crash.
    let result: Record<string, string> | null = null;
    let caughtError: Error | null = null;
    try {
      result = parse23andMe(content);
    } catch (err) {
      caughtError = err as Error;
    }

    if (caughtError !== null) {
      expect(caughtError).toBeInstanceOf(Error);
    } else {
      // rs222 must always be present if parser succeeded
      expect(result!['rs222']).toBe('GG');
    }
  });

  it(
    'rsid with 10000 characters → handled without crash',
    () => {
      const veryLongRsid = 'rs' + '9'.repeat(9998);
      const content = [
        '# This data file generated by 23andMe',
        '# rsid\tchromosome\tposition\tgenotype',
        `${veryLongRsid}\t1\t100\tAA`,
        'rs333\t1\t300\tCT',
      ].join('\n');

      let result: Record<string, string> | null = null;
      let caughtError: Error | null = null;
      try {
        result = parse23andMe(content);
      } catch (err) {
        caughtError = err as Error;
      }

      if (caughtError !== null) {
        expect(caughtError).toBeInstanceOf(Error);
      } else {
        expect(result!['rs333']).toBe('CT');
      }
    },
    15_000,
  );

  it('AncestryDNA with extremely long rsid → handled without crash', () => {
    const longRsid = 'rs' + '7'.repeat(5000);
    const content = [
      '#AncestryDNA raw data download',
      'rsid\tchromosome\tposition\tallele1\tallele2',
      `${longRsid}\t1\t100\tA\tG`,
      'rs444\t1\t400\tC\tT',
    ].join('\n');

    let result: Record<string, string> | null = null;
    let caughtError: Error | null = null;
    try {
      result = parseAncestryDNA(content);
    } catch (err) {
      caughtError = err as Error;
    }

    if (caughtError !== null) {
      expect(caughtError).toBeInstanceOf(Error);
    } else {
      expect(result!['rs444']).toBe('CT');
    }
  });

  it('VCF with extremely long variant ID → line skipped gracefully', () => {
    const longId = 'rs' + '5'.repeat(5000);
    const content = [
      '##fileformat=VCFv4.1',
      '##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">',
      '#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\tFORMAT\tSAMPLE1',
      `1\t100\t${longId}\tA\tG\t100\tPASS\t.\tGT\t0/1`,
      `1\t200\trs555\tC\tT\t100\tPASS\t.\tGT\t0/0`,
    ].join('\n');

    let result: Record<string, string> | null = null;
    let caughtError: Error | null = null;
    try {
      result = parseVcf(content);
    } catch (err) {
      caughtError = err as Error;
    }

    if (caughtError !== null) {
      expect(caughtError).toBeInstanceOf(Error);
    } else {
      // rs555 should be parsed
      expect(result!['rs555']).toBe('CC'); // 0/0 = ref/ref = CC
    }
  });
});

// ─── 9. 30s Timeout Enforcement ──────────────────────────────────────────────

describe('Fuzzing — 30s Timeout Enforcement', () => {
  /**
   * Deferred: The parser itself does not enforce a 30s timeout.
   * The timeout is enforced in the decompression pipeline (createMonitoredStream).
   * A parser-level timeout guard has not yet been implemented.
   * These todos document the requirement and mark it as future work.
   */
  it.todo(
    'TODO(stream-ops): decompression timeout (30s) throws TIMEOUT error for slow decompressions [requires browser env]',
  );

  it.todo(
    'TODO(stream-ops): parser enforces 30-second timeout on individual file parsing — parse timeout guard aborts infinite-loop-vulnerable inputs [not yet implemented]',
  );

  /**
   * Verify that TIMEOUT DecompressionError is well-formed (non-todo, immediate value).
   */
  it('DecompressionError with TIMEOUT code has correct structure', () => {
    const timeoutMs = 30_000;
    const err = new DecompressionError(
      'TIMEOUT',
      `Decompression timed out after ${timeoutMs} ms.`,
    );
    expect(err.code).toBe('TIMEOUT');
    expect(err.message).toContain('30000');
    expect(err.name).toBe('DecompressionError');
    expect(err).toBeInstanceOf(Error);
  });
});
