/**
 * Smoke Test — Critical Path Validation
 *
 * Validates that the core genetics engine pipeline works end-to-end
 * using tiny inline fixtures. Designed to run in <5 seconds and
 * catch complete system failures before the full test suite runs.
 *
 * Covers: parser → format detection → carrier analysis → summary
 */

import { describe, it, expect, beforeAll } from 'vitest';
import {
  detectFormat,
  parse23andMe,
  parseGeneticFile,
  getGenotypeStats,
} from '../src/parser';
import {
  analyzeCarrierRisk,
  getAnalysisSummary,
} from '../src/carrier';
import type { CarrierPanelEntry, GenotypeMap } from '../src/types';

// ─── Inline Fixtures ─────────────────────────────────────────────────────────

/**
 * Minimal 23andMe file — 10 lines total, 8 data SNPs.
 * Comment lines, a header comment, and real rsID entries.
 */
const SMOKE_23ANDME_CONTENT = [
  '# This data file generated by 23andMe at: Mon Jan 01 2024',
  '# rsid\tchromosome\tposition\tgenotype',
  'rs4477212\t1\t82154\tAA',
  'rs3094315\t1\t752566\tAG',
  'rs3131972\t1\t752721\tGG',
  'rs12124819\t1\t776546\tAA',
  'i713426\t1\t817186\tCC',
  'rs11240777\t1\t798959\tAG',
  'rs6681049\t1\t838555\tCC',
  'rs4970383\t1\t917270\tAC',
].join('\n');

/**
 * Minimal carrier panel — two entries for smoke testing.
 * rs4477212 → CFTR carrier test (pathogenic allele absent in fixture → normal).
 * rs3094315 → SMN1 carrier test (AG heterozygous → carrier).
 */
const SMOKE_PANEL: CarrierPanelEntry[] = [
  {
    rsid: 'rs4477212',
    gene: 'CFTR',
    condition: 'Cystic Fibrosis (Smoke)',
    inheritance: 'autosomal_recessive',
    carrier_frequency: '1 in 25',
    pathogenic_allele: 'T',
    reference_allele: 'A',
    description: 'Smoke test disease A',
    severity: 'high',
    prevalence: '1 in 3500',
    omim_id: '219700',
    category: 'Metabolic',
    sources: [],
    confidence: 'high',
    notes: '',
  },
  {
    rsid: 'rs3094315',
    gene: 'SMN1',
    condition: 'Spinal Muscular Atrophy (Smoke)',
    inheritance: 'autosomal_recessive',
    carrier_frequency: '1 in 54',
    pathogenic_allele: 'A',
    reference_allele: 'G',
    description: 'Smoke test disease B',
    severity: 'high',
    prevalence: '1 in 10000',
    omim_id: '253300',
    category: 'Neurological',
    sources: [],
    confidence: 'high',
    notes: '',
  },
];

// ─── Smoke Test Suite ────────────────────────────────────────────────────────

describe('Smoke — Parser critical path', () => {
  it('detects 23andMe format from inline fixture', () => {
    const format = detectFormat(SMOKE_23ANDME_CONTENT);
    expect(format).toBe('23andme');
  });

  it('parses 23andMe content and returns a non-empty genotype map', () => {
    const genotypes = parse23andMe(SMOKE_23ANDME_CONTENT);
    // Must be a plain object (GenotypeMap)
    expect(typeof genotypes).toBe('object');
    expect(genotypes).not.toBeNull();
    // All 8 data lines should be parsed
    const snpCount = Object.keys(genotypes).length;
    expect(snpCount).toBeGreaterThanOrEqual(8);
  });

  it('parseGeneticFile auto-detects format and returns correct genotype count', () => {
    const [genotypes, format] = parseGeneticFile(SMOKE_23ANDME_CONTENT);
    expect(format).toBe('23andme');
    expect(Object.keys(genotypes).length).toBeGreaterThanOrEqual(8);
  });

  it('parsed genotype map contains expected rsIDs', () => {
    const genotypes = parse23andMe(SMOKE_23ANDME_CONTENT);
    expect(genotypes['rs4477212']).toBe('AA');
    expect(genotypes['rs3094315']).toBe('AG');
    expect(genotypes['rs3131972']).toBe('GG');
    expect(genotypes['i713426']).toBe('CC');
  });

  it('getGenotypeStats returns correct totals', () => {
    const genotypes = parse23andMe(SMOKE_23ANDME_CONTENT);
    const stats = getGenotypeStats(genotypes);
    expect(stats.totalSnps).toBeGreaterThanOrEqual(8);
    // AA, GG, CC are homozygous; AG, AC are heterozygous
    expect(stats.homozygousCount).toBeGreaterThan(0);
    expect(stats.heterozygousCount).toBeGreaterThan(0);
    expect(stats.homozygousCount + stats.heterozygousCount).toBeLessThanOrEqual(stats.totalSnps);
  });
});

describe('Smoke — Carrier analysis critical path', () => {
  let parentAGenotypes: GenotypeMap;
  let parentBGenotypes: GenotypeMap;

  beforeAll(() => {
    // Use parsed fixture genotypes for parent A; construct a different parent B
    parentAGenotypes = parse23andMe(SMOKE_23ANDME_CONTENT);
    // Parent B: carrier for CFTR (rs4477212 → AT), normal for SMN1 (rs3094315 → GG)
    parentBGenotypes = {
      rs4477212: 'AT',
      rs3094315: 'GG',
    };
  });

  it('analyzeCarrierRisk returns at least one result', () => {
    const results = analyzeCarrierRisk(parentAGenotypes, parentBGenotypes, SMOKE_PANEL);
    expect(results.length).toBeGreaterThanOrEqual(1);
  });

  it('carrier analysis produces correctly typed results', () => {
    const results = analyzeCarrierRisk(parentAGenotypes, parentBGenotypes, SMOKE_PANEL);
    for (const result of results) {
      expect(result).toHaveProperty('condition');
      expect(result).toHaveProperty('gene');
      expect(result).toHaveProperty('riskLevel');
      expect(result).toHaveProperty('offspringRisk');
      expect(result).toHaveProperty('parentAStatus');
      expect(result).toHaveProperty('parentBStatus');
    }
  });

  it('CFTR result: parent A normal (AA with pathogenic=T), parent B carrier (AT)', () => {
    const results = analyzeCarrierRisk(parentAGenotypes, parentBGenotypes, SMOKE_PANEL);
    const cftr = results.find((r) => r.gene === 'CFTR');
    expect(cftr).toBeDefined();
    // Parent A has AA genotype, pathogenic=T → normal
    expect(cftr?.parentAStatus).toBe('normal');
    // Parent B has AT genotype, pathogenic=T → carrier
    expect(cftr?.parentBStatus).toBe('carrier');
    // normal × carrier → low risk (no affected offspring, but one carrier parent)
    expect(cftr?.riskLevel).toBe('carrier_detected');
  });

  it('getAnalysisSummary returns correct disease count', () => {
    const results = analyzeCarrierRisk(parentAGenotypes, parentBGenotypes, SMOKE_PANEL);
    const summary = getAnalysisSummary(results, 'pro');
    expect(summary.diseasesAnalyzed).toBe(SMOKE_PANEL.length);
    expect(summary.tier).toBe('pro');
  });
});
