/**
 * Tests for the Web Worker message handling logic.
 *
 * Since Vitest runs in Node.js (not a Worker context), these tests verify
 * the exported helper functions and types rather than the full Worker
 * message loop. The streaming parser and progress reporter are tested
 * in their own test files.
 *
 * Integration tests for the full Worker lifecycle require a browser
 * environment (or jsdom with Worker polyfills) and are covered in e2e tests.
 */

import { describe, it, expect } from 'vitest';
import { ProgressReporter } from '../src/progress';
import type { ProgressEvent } from '../src/progress';
import {
  iterateStreamLines,
  detectFormatFromStream,
  chainIterators,
  parseStreaming,
} from '../src/parser';
import type { FileFormat, GenotypeMap } from '../src/types';

// ─── iterateStreamLines ─────────────────────────────────────────────────────

describe('iterateStreamLines', () => {
  /**
   * Helper: create a ReadableStream from a string.
   */
  function stringToStream(content: string): ReadableStream<Uint8Array> {
    const encoder = new TextEncoder();
    return new ReadableStream({
      start(controller) {
        controller.enqueue(encoder.encode(content));
        controller.close();
      },
    });
  }

  /**
   * Helper: create a ReadableStream from multiple chunks.
   */
  function chunksToStream(chunks: string[]): ReadableStream<Uint8Array> {
    const encoder = new TextEncoder();
    return new ReadableStream({
      start(controller) {
        for (const chunk of chunks) {
          controller.enqueue(encoder.encode(chunk));
        }
        controller.close();
      },
    });
  }

  it('should yield lines from a simple stream with LF', async () => {
    const stream = stringToStream('line1\nline2\nline3');
    const lines: string[] = [];
    for await (const line of iterateStreamLines(stream)) {
      lines.push(line);
    }
    expect(lines).toEqual(['line1', 'line2', 'line3']);
  });

  it('should handle CRLF line endings', async () => {
    const stream = stringToStream('line1\r\nline2\r\nline3');
    const lines: string[] = [];
    for await (const line of iterateStreamLines(stream)) {
      lines.push(line);
    }
    expect(lines).toEqual(['line1', 'line2', 'line3']);
  });

  it('should handle standalone CR line endings', async () => {
    const stream = stringToStream('line1\rline2\rline3');
    const lines: string[] = [];
    for await (const line of iterateStreamLines(stream)) {
      lines.push(line);
    }
    expect(lines).toEqual(['line1', 'line2', 'line3']);
  });

  it('should handle lines split across chunks', async () => {
    const stream = chunksToStream(['line', '1\nli', 'ne2\nline3']);
    const lines: string[] = [];
    for await (const line of iterateStreamLines(stream)) {
      lines.push(line);
    }
    expect(lines).toEqual(['line1', 'line2', 'line3']);
  });

  it('should handle trailing newline', async () => {
    const stream = stringToStream('line1\nline2\n');
    const lines: string[] = [];
    for await (const line of iterateStreamLines(stream)) {
      lines.push(line);
    }
    expect(lines).toEqual(['line1', 'line2']);
  });

  it('should handle empty stream', async () => {
    const stream = stringToStream('');
    const lines: string[] = [];
    for await (const line of iterateStreamLines(stream)) {
      lines.push(line);
    }
    expect(lines).toEqual([]);
  });

  it('should handle single line without newline', async () => {
    const stream = stringToStream('single line');
    const lines: string[] = [];
    for await (const line of iterateStreamLines(stream)) {
      lines.push(line);
    }
    expect(lines).toEqual(['single line']);
  });

  it('should handle CRLF split across chunks', async () => {
    // \r at end of one chunk, \n at start of next
    const stream = chunksToStream(['line1\r', '\nline2']);
    const lines: string[] = [];
    for await (const line of iterateStreamLines(stream)) {
      lines.push(line);
    }
    expect(lines).toEqual(['line1', 'line2']);
  });

  it('should handle multiple empty lines', async () => {
    const stream = stringToStream('a\n\n\nb');
    const lines: string[] = [];
    for await (const line of iterateStreamLines(stream)) {
      lines.push(line);
    }
    expect(lines).toEqual(['a', '', '', 'b']);
  });
});

// ─── detectFormatFromStream ─────────────────────────────────────────────────

describe('detectFormatFromStream', () => {
  async function* linesFromArray(arr: string[]): AsyncGenerator<string> {
    for (const line of arr) {
      yield line;
    }
  }

  it('should detect 23andMe format from comment signature', async () => {
    const lines = [
      '# This data file generated by 23andMe',
      '# rsid\tchromosome\tposition\tgenotype',
      'rs4477212\t1\t82154\tAA',
      'rs3094315\t1\t752566\tAG',
    ];
    const result = await detectFormatFromStream(linesFromArray(lines));
    expect(result.format).toBe('23andme');
    expect(result.bufferedLines).toHaveLength(4);
    expect(result.bufferedLines[0]).toContain('23andMe');
  });

  it('should detect AncestryDNA format', async () => {
    const lines = [
      '#AncestryDNA raw data download',
      'rsid\tchromosome\tposition\tallele1\tallele2',
      'rs4477212\t1\t82154\tA\tA',
    ];
    const result = await detectFormatFromStream(linesFromArray(lines));
    expect(result.format).toBe('ancestrydna');
  });

  it('should detect VCF format', async () => {
    const lines = [
      '##fileformat=VCFv4.1',
      '##INFO=<ID=DP,Number=1>',
      '#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\tFORMAT\tSAMPLE',
      '1\t82154\trs4477212\tA\tG\t100\tPASS\t.\tGT:DP\t0/0:30',
    ];
    const result = await detectFormatFromStream(linesFromArray(lines));
    expect(result.format).toBe('vcf');
  });

  it('should detect MyHeritage format', async () => {
    const lines = [
      'RSID,CHROMOSOME,POSITION,RESULT',
      'rs4477212,1,82154,AA',
      'rs3094315,1,752566,AG',
    ];
    const result = await detectFormatFromStream(linesFromArray(lines));
    expect(result.format).toBe('myheritage');
  });

  it('should return unknown for unrecognized data', async () => {
    const lines = ['garbage', 'random data', 'nothing useful'];
    const result = await detectFormatFromStream(linesFromArray(lines));
    expect(result.format).toBe('unknown');
  });

  it('should buffer up to 20 lines', async () => {
    const lines = Array.from({ length: 30 }, (_, i) => `line${String(i)}`);
    const result = await detectFormatFromStream(linesFromArray(lines));
    expect(result.bufferedLines).toHaveLength(20);
  });

  it('should handle fewer than 20 lines', async () => {
    const lines = ['# 23andMe', 'rs123\t1\t100\tAA'];
    const result = await detectFormatFromStream(linesFromArray(lines));
    expect(result.bufferedLines).toHaveLength(2);
  });
});

// ─── chainIterators ─────────────────────────────────────────────────────────

describe('chainIterators', () => {
  async function* asyncLines(arr: string[]): AsyncGenerator<string> {
    for (const line of arr) {
      yield line;
    }
  }

  it('should yield buffered lines first, then remaining', async () => {
    const buffered = ['line1', 'line2'];
    const remaining = asyncLines(['line3', 'line4']);
    const result: string[] = [];
    for await (const line of chainIterators(buffered, remaining)) {
      result.push(line);
    }
    expect(result).toEqual(['line1', 'line2', 'line3', 'line4']);
  });

  it('should handle empty buffered lines', async () => {
    const remaining = asyncLines(['a', 'b']);
    const result: string[] = [];
    for await (const line of chainIterators([], remaining)) {
      result.push(line);
    }
    expect(result).toEqual(['a', 'b']);
  });

  it('should handle empty remaining iterator', async () => {
    const remaining = asyncLines([]);
    const result: string[] = [];
    for await (const line of chainIterators(['x', 'y'], remaining)) {
      result.push(line);
    }
    expect(result).toEqual(['x', 'y']);
  });

  it('should handle both empty', async () => {
    const remaining = asyncLines([]);
    const result: string[] = [];
    for await (const line of chainIterators([], remaining)) {
      result.push(line);
    }
    expect(result).toEqual([]);
  });
});

// ─── parseStreaming ─────────────────────────────────────────────────────────

describe('parseStreaming', () => {
  async function* linesFromArray(arr: string[]): AsyncGenerator<string> {
    for (const line of arr) {
      yield line;
    }
  }

  it('should parse 23andMe lines via streaming', async () => {
    const lines = [
      '# This data file generated by 23andMe',
      '# rsid\tchromosome\tposition\tgenotype',
      'rs4477212\t1\t82154\tAA',
      'rs3094315\t1\t752566\tAG',
      'rs3131972\t1\t752721\tGG',
    ];
    const result = await parseStreaming(linesFromArray(lines), '23andme');
    expect(result['rs4477212']).toBe('AA');
    expect(result['rs3094315']).toBe('AG');
    expect(result['rs3131972']).toBe('GG');
    expect(Object.keys(result)).toHaveLength(3);
  });

  it('should parse AncestryDNA lines via streaming', async () => {
    const lines = [
      '#AncestryDNA raw data',
      'rsid\tchromosome\tposition\tallele1\tallele2',
      'rs4477212\t1\t82154\tA\tA',
      'rs3094315\t1\t752566\tA\tG',
    ];
    const result = await parseStreaming(linesFromArray(lines), 'ancestrydna');
    expect(result['rs4477212']).toBe('AA');
    expect(result['rs3094315']).toBe('AG');
  });

  it('should parse MyHeritage CSV lines via streaming', async () => {
    const lines = [
      'RSID,CHROMOSOME,POSITION,RESULT',
      'rs4477212,1,82154,AA',
      'rs3094315,1,752566,AG',
      'VG00001,1,999999,CT',
    ];
    const result = await parseStreaming(linesFromArray(lines), 'myheritage');
    expect(result['rs4477212']).toBe('AA');
    expect(result['rs3094315']).toBe('AG');
    expect(result['VG00001']).toBe('CT');
  });

  it('should parse VCF lines via streaming', async () => {
    const lines = [
      '##fileformat=VCFv4.1',
      '##INFO=<ID=DP,Number=1,Type=Integer>',
      '#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\tFORMAT\tSAMPLE1',
      '1\t82154\trs4477212\tA\tG\t100\tPASS\t.\tGT:DP\t0/0:30',
      '1\t752566\trs3094315\tA\tG\t100\tPASS\t.\tGT:DP\t0/1:25',
    ];
    const result = await parseStreaming(linesFromArray(lines), 'vcf');
    expect(result['rs4477212']).toBe('AA');
    expect(result['rs3094315']).toBe('AG');
  });

  it('should throw for unknown format', async () => {
    const lines = ['random data'];
    await expect(parseStreaming(linesFromArray(lines), 'unknown')).rejects.toThrow(
      'Unrecognized genetic data format',
    );
  });

  it('should throw when no valid SNPs found', async () => {
    const lines = ['# only comments', '# nothing useful here'];
    await expect(parseStreaming(linesFromArray(lines), '23andme')).rejects.toThrow(
      'No valid SNP data found',
    );
  });

  it('should skip no-call entries (23andMe --)', async () => {
    const lines = [
      'rs4477212\t1\t82154\tAA',
      'rs3094315\t1\t752566\t--',
      'rs3131972\t1\t752721\tGG',
    ];
    const result = await parseStreaming(linesFromArray(lines), '23andme');
    expect(Object.keys(result)).toHaveLength(2);
    expect(result['rs3094315']).toBeUndefined();
  });

  it('should skip VCF no-call genotypes (./.)', async () => {
    const lines = [
      '##fileformat=VCFv4.1',
      '#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\tFORMAT\tSAMPLE',
      '1\t100\trs100\tA\tG\t30\tPASS\t.\tGT\t0/1',
      '1\t200\trs200\tA\tG\t30\tPASS\t.\tGT\t./.',
    ];
    const result = await parseStreaming(linesFromArray(lines), 'vcf');
    expect(Object.keys(result)).toHaveLength(1);
    expect(result['rs100']).toBe('AG');
  });
});

// ─── ProgressReporter integration check ─────────────────────────────────────

describe('ProgressReporter in worker context', () => {
  it('should work as a postMessage wrapper', () => {
    const messages: ProgressEvent[] = [];
    const reporter = new ProgressReporter((event) => {
      messages.push(event);
    }, 0);

    reporter.forceReport('initializing', 0, 'Worker initializing');
    reporter.report('parsing', 50);
    reporter.forceReport('complete', 100, 'Done');

    expect(messages).toHaveLength(3);
    expect(messages[0]!.stage).toBe('initializing');
    expect(messages[1]!.progress).toBe(50);
    expect(messages[2]!.stage).toBe('complete');
  });
});
