/**
 * Edge Case File Generators
 *
 * Functions to generate synthetic genetic data files with known edge-case
 * conditions. Used to verify that the parser handles malformed or unusual
 * inputs gracefully (no crashes, correct skipping of invalid lines).
 *
 * All generated files are zero-PII synthetic data.
 */

import { generateSyntheticGenome } from './synthetic-factory';

// ─── Edge Case Generators ────────────────────────────────────────────────────

/**
 * Generate an empty file (zero bytes).
 * Expected parser behavior: throws "No valid SNP data found".
 */
export function generateEmptyFile(): string {
  return '';
}

/**
 * Generate a 23andMe-formatted file with a UTF-8 BOM prefix (U+FEFF).
 *
 * Some Windows tools prepend a BOM to text files. The parser should handle
 * this gracefully: either parse normally (if BOM-stripping is implemented)
 * or throw "No valid SNP data" (because the first line is broken).
 *
 * The file contains a few valid lines after the header so the parser
 * can find SNP data if it strips the BOM.
 */
export function generateBomPrefixedFile(): string {
  const BOM = '\uFEFF';
  return (
    BOM +
    [
      '# This data file generated by 23andMe at: Thu Jan 01 2026',
      '# rsid\tchromosome\tposition\tgenotype',
      'rs4477212\t1\t82154\tAA',
      'rs3094315\t1\t752566\tAG',
      'rs3131972\t1\t752721\tGG',
    ].join('\n')
  );
}

/**
 * Convert LF line endings to CRLF in any string.
 *
 * Usage: generate a valid file with LF, pass to this function to get
 * the CRLF variant. Parsers should produce identical results for both.
 */
export function generateCrlfFile(lfContent: string): string {
  // Replace bare LF (not already preceded by CR) with CRLF
  return lfContent.replace(/\r?\n/g, '\r\n');
}

/**
 * Generate a 23andMe file where the last line is truncated (no trailing newline).
 *
 * Tests that the parser correctly handles a partial last line, which
 * happens when a file stream is cut off or the user saves without a final newline.
 */
export function generateTruncatedFile(): string {
  const lines = [
    '# This data file generated by 23andMe at: Thu Jan 01 2026',
    '# rsid\tchromosome\tposition\tgenotype',
    'rs4477212\t1\t82154\tAA',
    'rs3094315\t1\t752566\tAG',
    'rs3131972\t1\t752721\tGG',
    // Note: no trailing newline — this is intentionally truncated at a data line end
  ];
  // Join without a final newline
  return lines.join('\n');
}

/**
 * Generate a 23andMe file with duplicate rsIDs.
 *
 * The file has two lines for 'rs4477212': first with genotype 'AA', then with 'GG'.
 * The parser processes all lines, overwriting duplicates with the last occurrence.
 * Expected result: rs4477212 → 'GG'.
 */
export function generateDuplicateRsidFile(): string {
  return [
    '# This data file generated by 23andMe at: Thu Jan 01 2026',
    '# rsid\tchromosome\tposition\tgenotype',
    'rs4477212\t1\t82154\tAA', // first occurrence
    'rs3094315\t1\t752566\tAG',
    'rs4477212\t1\t82154\tGG', // duplicate — overwrites first
    'rs3131972\t1\t752721\tCC',
  ].join('\n');
}

/**
 * Generate a 23andMe file where every data line is a no-call ('--').
 *
 * Expected parser behavior: throws "No valid SNP data found" because
 * no-calls are excluded by the parser.
 */
export function generateNoCallFile(): string {
  return [
    '# This data file generated by 23andMe at: Thu Jan 01 2026',
    '# rsid\tchromosome\tposition\tgenotype',
    'rs4477212\t1\t82154\t--',
    'rs3094315\t1\t752566\t--',
    'rs3131972\t1\t752721\t--',
    'rs12124819\t1\t776546\t--',
  ].join('\n');
}

/**
 * Generate a 23andMe file with one extremely long comment line (>10,000 characters).
 *
 * The parser should skip comment lines regardless of length. Valid data lines
 * after the long comment should parse normally.
 */
export function generateLongCommentFile(): string {
  const longComment = `# ${'A'.repeat(12000)}`;
  return [
    '# This data file generated by 23andMe at: Thu Jan 01 2026',
    longComment,
    '# rsid\tchromosome\tposition\tgenotype',
    'rs4477212\t1\t82154\tAA',
    'rs3094315\t1\t752566\tAG',
    'rs3131972\t1\t752721\tGG',
    'rs12124819\t1\t776546\tAA',
    'rs2268119\t1\t817186\tCC',
  ].join('\n');
}

/**
 * Generate a 23andMe file with non-standard chromosome values.
 *
 * Includes chromosomes like 'chr1' (UCSC notation) instead of '1' (Ensembl).
 * The parser does not validate chromosome values for 23andMe format, so
 * these lines should still be parsed.
 *
 * Returns both the file content and the expected genotype map.
 */
export function generateNonstandardChromosomeFile(): {
  content: string;
  expectedGenotypes: Record<string, string>;
} {
  const content = [
    '# This data file generated by 23andMe at: Thu Jan 01 2026',
    '# rsid\tchromosome\tposition\tgenotype',
    // Non-standard chromosome names — 23andMe parser doesn't validate chr column
    'rs4477212\tchr1\t82154\tAA',
    'rs3094315\tchrX\t752566\tAG',
    'rs3131972\tchrMT\t752721\tGG',
  ].join('\n');

  return {
    content,
    expectedGenotypes: {
      rs4477212: 'AA',
      rs3094315: 'AG',
      rs3131972: 'GG',
    },
  };
}

/**
 * Generate a small synthetic file with a specific format for edge-case integration testing.
 * Delegates to the main factory with edgeCases: true.
 */
export function generateEdgeCaseGenome(
  format: '23andme' | 'ancestrydna' | 'myheritage' | 'vcf',
  seed: number,
): string {
  return generateSyntheticGenome({ format, seed, variantCount: 50, edgeCases: true });
}
