/**
 * Golden Standard Dataset — Edge Cases (23andMe format) (Q1a)
 *
 * A 23andMe-formatted file that contains multiple edge-case constructs.
 * Serves as a regression anchor for parser robustness.
 *
 * Edge cases covered:
 * - BOM-like Unicode in a comment (safe: parser skips comment lines)
 * - Extra tabs in a comment (safe: parser skips comment lines)
 * - A data line with trailing whitespace (parser trims)
 * - A data line with mixed-case rsid prefix ('RS' instead of 'rs') — skipped by parser
 * - A no-call ('--') line — skipped by parser
 * - Valid data lines that MUST appear in output
 *
 * Zero PII — all data is synthetic.
 */

import type { GoldenDataset } from './golden-types';

/**
 * Golden edge-case dataset (23andMe format).
 *
 * A 23andMe-formatted file that contains multiple edge-case constructs:
 * - BOM-like Unicode in a comment (safe: parser skips comment lines)
 * - Extra tabs in a comment (safe: parser skips comment lines)
 * - A data line with trailing whitespace (parser trims)
 * - A data line with mixed-case rsid prefix ('RS' instead of 'rs') — skipped by parser
 * - A no-call ('--') line — skipped by parser
 * - Valid data lines that MUST appear in output
 *
 * Expected: only the clearly valid data lines appear in the output.
 */
export const GOLDEN_EDGE_CASES: GoldenDataset = {
  name: '23andMe Edge Cases Golden',
  content: [
    '# This data file generated by 23andMe at: Thu Jan 01 2026',
    '# Column header with extra tabs:	rsid	chromosome	position	genotype',
    '# rsid\tchromosome\tposition\tgenotype',
    // Valid data lines — must be in output
    'rs4477212\t1\t82154\tAA',
    'rs3094315\t1\t752566\tAG',
    'rs3131972\t1\t752721\tGG',
    'rs12124819\t1\t776546\tAA',
    'rs2268119\t1\t817186\tCC',
    // Data line with trailing whitespace — parser trims, so this IS valid
    'rs2905035\t1\t825852\tAA   ',
    // Mixed-case rsid prefix — must NOT be in output (parser requires lowercase 'rs'/'i')
    'RS3748816\t1\t861808\tCC',
    // No-call — must NOT be in output
    'rs9442372\t1\t843817\t--',
    // Completely empty line — must be skipped
    '',
    // More valid data
    'rs10458597\t1\t891021\tAA',
    'rs7419119\t1\t949608\tGG',
    'rs13302982\t1\t1018704\tCC',
    'rs4970383\t1\t1048955\tAA',
    'rs4475691\t1\t1061166\tCC',
    'rs1806153\t1\t1070426\tGG',
    'rs7537756\t1\t1071580\tAA',
    // Short line (only 3 columns) — must be skipped
    'rs1110052\t2\t234668',
    // Valid again
    'rs2272756\t2\t337674\tGG',
    'rs1372726\t2\t423345\tAA',
    'rs1390716\t2\t543236\tCC',
    'rs2312724\t2\t644457\tAG',
    'rs1011721\t2\t745678\tGG',
  ].join('\n'),

  expectedGenotypes: {
    rs4477212: 'AA',
    rs3094315: 'AG',
    rs3131972: 'GG',
    rs12124819: 'AA',
    rs2268119: 'CC',
    rs2905035: 'AA', // trailing whitespace stripped
    // RS3748816 NOT present (wrong case)
    // rs9442372 NOT present (no-call)
    rs10458597: 'AA',
    rs7419119: 'GG',
    rs13302982: 'CC',
    rs4970383: 'AA',
    rs4475691: 'CC',
    rs1806153: 'GG',
    rs7537756: 'AA',
    // rs1110052 NOT present (short line)
    rs2272756: 'GG',
    rs1372726: 'AA',
    rs1390716: 'CC',
    rs2312724: 'AG',
    rs1011721: 'GG',
  },
};
