"""Tests for streaming parser infrastructure and streaming format parsers.

Covers:
- _line_iterator() with str path, BytesIO, and generic file-like objects
- _read_header_lines() returning correct number of lines and resetting position
- _validate_file_size() rejecting oversized files
- Streaming parsers producing identical output to content-based parsers
- SNP count limit enforcement
- Empty / malformed file handling
- parse_genetic_file() two-phase streaming path
"""

from io import BytesIO, StringIO
from pathlib import Path
from unittest.mock import patch

import pytest
from Source.parser import (
    MAX_FILE_SIZE_BYTES,
    _detect_format_from_lines,
    _line_iterator,
    _parse_23andme_from_content,
    _parse_23andme_streaming,
    _parse_ancestry_from_content,
    _parse_ancestry_streaming,
    _parse_myheritage_from_content,
    _parse_myheritage_streaming,
    _parse_vcf_from_content,
    _parse_vcf_streaming,
    _read_file_content,
    _read_header_lines,
    _validate_file_size,
    parse_genetic_file,
)

# ---------------------------------------------------------------------------
# Paths to sample data fixtures
# ---------------------------------------------------------------------------
SAMPLE_DIR = Path(__file__).resolve().parent.parent / "sample_data"

SAMPLE_23ANDME = SAMPLE_DIR / "23andme" / "sample_23andme_v3_carrier_01.txt"
SAMPLE_23ANDME_V4 = SAMPLE_DIR / "23andme" / "sample_23andme_v4_female_01.txt"
SAMPLE_ANCESTRY = SAMPLE_DIR / "ancestry" / "sample_ancestry_v1_female_01.txt"
SAMPLE_ANCESTRY_V2 = SAMPLE_DIR / "ancestry" / "sample_ancestry_v2_diverse_01.txt"
SAMPLE_MYHERITAGE_QUOTED = SAMPLE_DIR / "myheritage" / "sample1_quoted.csv"
SAMPLE_MYHERITAGE_UNQUOTED = SAMPLE_DIR / "myheritage" / "sample5_unquoted.csv"
SAMPLE_VCF = SAMPLE_DIR / "vcf" / "sample_vcf_panel_01.vcf"
SAMPLE_VCF_WGS = SAMPLE_DIR / "vcf" / "sample_vcf_wgs_male_01.vcf"


# ===================================================================
# _line_iterator tests
# ===================================================================

class TestLineIterator:
    """Test _line_iterator with various input types."""

    def test_str_path(self):
        """_line_iterator should yield lines from a string file path."""
        lines = list(_line_iterator(str(SAMPLE_23ANDME)))
        assert len(lines) > 0
        # First line should be a 23andMe comment
        assert lines[0].startswith("# This data file generated by 23andMe")

    def test_path_object(self):
        """_line_iterator should yield lines from a Path object."""
        lines = list(_line_iterator(SAMPLE_23ANDME))
        assert len(lines) > 0
        assert lines[0].startswith("#")

    def test_bytesio(self):
        """_line_iterator should yield lines from a BytesIO object."""
        content = SAMPLE_23ANDME.read_text(encoding="utf-8")
        bio = BytesIO(content.encode("utf-8"))
        lines = list(_line_iterator(bio))
        assert len(lines) > 0
        assert lines[0].startswith("#")

    def test_stringio(self):
        """_line_iterator should yield lines from a StringIO (generic file-like)."""
        content = SAMPLE_ANCESTRY.read_text(encoding="utf-8")
        sio = StringIO(content)
        lines = list(_line_iterator(sio))
        assert len(lines) > 0
        assert lines[0].startswith("#")

    def test_lines_are_stripped_of_newlines(self):
        """Yielded lines should have trailing \\n and \\r removed."""
        content = "line1\nline2\r\nline3\n"
        bio = BytesIO(content.encode("utf-8"))
        lines = list(_line_iterator(bio))
        for line in lines:
            assert not line.endswith("\n")
            assert not line.endswith("\r")

    def test_empty_file(self):
        """_line_iterator on an empty file should yield nothing."""
        bio = BytesIO(b"")
        lines = list(_line_iterator(bio))
        assert lines == []


# ===================================================================
# _read_header_lines tests
# ===================================================================

class TestReadHeaderLines:
    """Test _read_header_lines."""

    def test_returns_correct_count(self):
        """Should return at most max_lines lines."""
        lines = _read_header_lines(str(SAMPLE_23ANDME), max_lines=10)
        assert len(lines) == 10

    def test_default_max_lines(self):
        """Default max_lines is 50; should return up to 50 lines."""
        lines = _read_header_lines(str(SAMPLE_23ANDME))
        assert len(lines) <= 50

    def test_resets_bytesio_position(self):
        """After reading, BytesIO position should be reset to 0."""
        content = SAMPLE_23ANDME.read_text(encoding="utf-8")
        bio = BytesIO(content.encode("utf-8"))
        _read_header_lines(bio, max_lines=5)
        assert bio.tell() == 0

    def test_short_file_returns_all_lines(self):
        """A file shorter than max_lines returns all available lines."""
        content = "line1\nline2\nline3\n"
        bio = BytesIO(content.encode("utf-8"))
        lines = _read_header_lines(bio, max_lines=50)
        assert len(lines) == 3


# ===================================================================
# _validate_file_size tests
# ===================================================================

class TestValidateFileSize:
    """Test _validate_file_size."""

    def test_accepts_small_file_path(self):
        """Should not raise for a small sample file."""
        _validate_file_size(str(SAMPLE_23ANDME))  # No exception expected

    def test_accepts_small_bytesio(self):
        """Should not raise for a small BytesIO."""
        bio = BytesIO(b"small content")
        _validate_file_size(bio)  # No exception expected

    def test_rejects_oversized_file_path(self, tmp_path):
        """Should raise ValueError for a file exceeding MAX_FILE_SIZE_BYTES."""
        # Create a sparse file (just set size metadata)
        big_file = tmp_path / "big.txt"
        big_file.write_bytes(b"x")
        # Patch Path.stat to report a huge size
        original_stat = Path.stat

        def fake_stat(self_path):
            if str(self_path) == str(big_file):
                result = original_stat(self_path)
                # Create a mock-like object with overridden st_size
                class FakeStat:
                    pass
                fs = FakeStat()
                for attr in dir(result):
                    if attr.startswith("st_"):
                        setattr(fs, attr, getattr(result, attr))
                fs.st_size = MAX_FILE_SIZE_BYTES + 1
                return fs
            return original_stat(self_path)

        with patch.object(Path, "stat", fake_stat):
            with pytest.raises(ValueError, match="File too large"):
                _validate_file_size(str(big_file))

    def test_rejects_oversized_bytesio(self):
        """Should raise ValueError for a BytesIO exceeding MAX_FILE_SIZE_BYTES."""

        class FakeBigBytesIO(BytesIO):
            """BytesIO subclass that reports an oversized getvalue()."""

            def getvalue(self):
                return b"x" * (MAX_FILE_SIZE_BYTES + 1)

        big_bio = FakeBigBytesIO(b"small")
        with pytest.raises(ValueError, match="File too large"):
            _validate_file_size(big_bio)

    def test_accepts_generic_file_object(self):
        """Generic file-like objects without getvalue/stat should pass silently."""
        sio = StringIO("hello")
        _validate_file_size(sio)  # Should not raise


# ===================================================================
# _detect_format_from_lines tests
# ===================================================================

class TestDetectFormatFromLines:
    """Test _detect_format_from_lines."""

    def test_detect_23andme(self):
        """Should detect 23andMe format from header lines."""
        lines = _read_header_lines(str(SAMPLE_23ANDME), max_lines=50)
        assert _detect_format_from_lines(lines) == "23andme"

    def test_detect_ancestry(self):
        """Should detect AncestryDNA format from header lines."""
        lines = _read_header_lines(str(SAMPLE_ANCESTRY), max_lines=50)
        assert _detect_format_from_lines(lines) == "ancestry"

    def test_detect_myheritage(self):
        """Should detect MyHeritage format from header lines."""
        lines = _read_header_lines(str(SAMPLE_MYHERITAGE_QUOTED), max_lines=50)
        assert _detect_format_from_lines(lines) == "myheritage"

    def test_detect_vcf(self):
        """Should detect VCF format from header lines."""
        lines = _read_header_lines(str(SAMPLE_VCF), max_lines=50)
        assert _detect_format_from_lines(lines) == "vcf"


# ===================================================================
# Streaming vs content-based parser equivalence tests
# ===================================================================

class TestStreamingEquivalence23andMe:
    """Streaming 23andMe parser produces identical output to content-based parser."""

    def test_v3_carrier_file(self):
        content = SAMPLE_23ANDME.read_text(encoding="utf-8")
        expected = _parse_23andme_from_content(content)
        actual = _parse_23andme_streaming(str(SAMPLE_23ANDME))
        assert actual == expected

    def test_v4_female_file(self):
        content = SAMPLE_23ANDME_V4.read_text(encoding="utf-8")
        expected = _parse_23andme_from_content(content)
        actual = _parse_23andme_streaming(str(SAMPLE_23ANDME_V4))
        assert actual == expected

    def test_bytesio_input(self):
        content = SAMPLE_23ANDME.read_text(encoding="utf-8")
        expected = _parse_23andme_from_content(content)
        bio = BytesIO(content.encode("utf-8"))
        actual = _parse_23andme_streaming(bio)
        assert actual == expected


class TestStreamingEquivalenceAncestry:
    """Streaming AncestryDNA parser produces identical output to content-based parser."""

    def test_v1_female_file(self):
        content = SAMPLE_ANCESTRY.read_text(encoding="utf-8")
        expected = _parse_ancestry_from_content(content)
        actual = _parse_ancestry_streaming(str(SAMPLE_ANCESTRY))
        assert actual == expected

    def test_v2_diverse_file(self):
        content = SAMPLE_ANCESTRY_V2.read_text(encoding="utf-8")
        expected = _parse_ancestry_from_content(content)
        actual = _parse_ancestry_streaming(str(SAMPLE_ANCESTRY_V2))
        assert actual == expected


class TestStreamingEquivalenceMyHeritage:
    """Streaming MyHeritage parser produces identical output to content-based parser."""

    def test_quoted_csv(self):
        content = SAMPLE_MYHERITAGE_QUOTED.read_text(encoding="utf-8")
        expected = _parse_myheritage_from_content(content)
        actual = _parse_myheritage_streaming(str(SAMPLE_MYHERITAGE_QUOTED))
        assert actual == expected

    def test_unquoted_csv(self):
        content = SAMPLE_MYHERITAGE_UNQUOTED.read_text(encoding="utf-8")
        expected = _parse_myheritage_from_content(content)
        actual = _parse_myheritage_streaming(str(SAMPLE_MYHERITAGE_UNQUOTED))
        assert actual == expected


class TestStreamingEquivalenceVCF:
    """Streaming VCF parser produces identical output to content-based parser."""

    def test_panel_vcf(self):
        content = SAMPLE_VCF.read_text(encoding="utf-8")
        expected = _parse_vcf_from_content(content)
        actual = _parse_vcf_streaming(str(SAMPLE_VCF))
        assert actual == expected

    def test_wgs_vcf(self):
        content = SAMPLE_VCF_WGS.read_text(encoding="utf-8")
        expected = _parse_vcf_from_content(content)
        actual = _parse_vcf_streaming(str(SAMPLE_VCF_WGS))
        assert actual == expected


# ===================================================================
# SNP count limit enforcement
# ===================================================================

class TestSNPCountLimit:
    """Streaming parsers should raise when SNP count exceeds MAX_SNP_COUNT."""

    def test_23andme_snp_limit(self, tmp_path):
        """23andMe streaming parser should raise on exceeding SNP count limit."""
        # Generate a file with more than MAX_SNP_COUNT lines
        # We use a small limit via patching to avoid generating 10M lines
        big_file = tmp_path / "big_23andme.txt"
        lines = ["# This data file generated by 23andMe"]
        for i in range(110):
            lines.append(f"rs{i}\t1\t{1000 + i}\tAA")
        big_file.write_text("\n".join(lines), encoding="utf-8")

        with patch("Source.parser.MAX_SNP_COUNT", 100):
            with pytest.raises(ValueError, match="SNP count exceeds maximum"):
                _parse_23andme_streaming(str(big_file))

    def test_ancestry_snp_limit(self, tmp_path):
        """AncestryDNA streaming parser should raise on exceeding SNP count limit."""
        big_file = tmp_path / "big_ancestry.txt"
        lines = ["#AncestryDNA", "rsid\tchromosome\tposition\tallele1\tallele2"]
        for i in range(110):
            lines.append(f"rs{i}\t1\t{1000 + i}\tA\tG")
        big_file.write_text("\n".join(lines), encoding="utf-8")

        with patch("Source.parser.MAX_SNP_COUNT", 100):
            with pytest.raises(ValueError, match="SNP count exceeds maximum"):
                _parse_ancestry_streaming(str(big_file))

    def test_myheritage_snp_limit(self, tmp_path):
        """MyHeritage streaming parser should raise on exceeding SNP count limit."""
        big_file = tmp_path / "big_myheritage.csv"
        lines = ["RSID,CHROMOSOME,POSITION,RESULT"]
        for i in range(110):
            lines.append(f"rs{i},1,{1000 + i},AG")
        big_file.write_text("\n".join(lines), encoding="utf-8")

        with patch("Source.parser.MAX_SNP_COUNT", 100):
            with pytest.raises(ValueError, match="SNP count exceeds maximum"):
                _parse_myheritage_streaming(str(big_file))

    def test_vcf_snp_limit(self, tmp_path):
        """VCF streaming parser should raise on exceeding SNP count limit."""
        big_file = tmp_path / "big.vcf"
        lines = [
            "##fileformat=VCFv4.2",
            "#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\tFORMAT\tSAMPLE",
        ]
        for i in range(110):
            lines.append(f"1\t{1000 + i}\trs{i}\tA\tG\t.\tPASS\tNS=1\tGT\t0/1")
        big_file.write_text("\n".join(lines), encoding="utf-8")

        with patch("Source.parser.MAX_SNP_COUNT", 100):
            with pytest.raises(ValueError, match="SNP count exceeds maximum"):
                _parse_vcf_streaming(str(big_file))


# ===================================================================
# Empty / malformed file handling
# ===================================================================

class TestEmptyAndMalformedFiles:
    """Streaming parsers should raise clear errors for empty or malformed files."""

    def test_empty_23andme_raises(self):
        """Empty 23andMe file should raise ValueError."""
        bio = BytesIO(b"# 23andMe comment\n")
        with pytest.raises(ValueError, match="No valid SNP data"):
            _parse_23andme_streaming(bio)

    def test_empty_ancestry_raises(self):
        """Empty AncestryDNA file should raise ValueError."""
        bio = BytesIO(b"#AncestryDNA\nrsid\tchromosome\tposition\tallele1\tallele2\n")
        with pytest.raises(ValueError, match="No valid SNP data"):
            _parse_ancestry_streaming(bio)

    def test_empty_myheritage_raises(self):
        """Empty MyHeritage file should raise ValueError."""
        bio = BytesIO(b"RSID,CHROMOSOME,POSITION,RESULT\n")
        with pytest.raises(ValueError, match="No valid SNP data"):
            _parse_myheritage_streaming(bio)

    def test_empty_vcf_raises(self):
        """Empty VCF file should raise ValueError."""
        content = (
            "##fileformat=VCFv4.2\n"
            "#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\tFORMAT\tSAMPLE\n"
        )
        bio = BytesIO(content.encode("utf-8"))
        with pytest.raises(ValueError, match="No valid SNP data"):
            _parse_vcf_streaming(bio)

    def test_completely_empty_file(self):
        """A zero-byte file should produce no lines and fail gracefully."""
        bio = BytesIO(b"")
        with pytest.raises(ValueError, match="No valid SNP data"):
            _parse_23andme_streaming(bio)


# ===================================================================
# parse_genetic_file integration (two-phase streaming)
# ===================================================================

class TestParseGeneticFileStreaming:
    """Integration tests for the refactored parse_genetic_file."""

    def test_23andme_path(self):
        """parse_genetic_file should work with a 23andMe file path."""
        snps, fmt = parse_genetic_file(str(SAMPLE_23ANDME))
        assert fmt == "23andme"
        assert isinstance(snps, dict)
        assert len(snps) > 0

    def test_ancestry_path(self):
        """parse_genetic_file should work with an AncestryDNA file path."""
        snps, fmt = parse_genetic_file(str(SAMPLE_ANCESTRY))
        assert fmt == "ancestry"
        assert len(snps) > 0

    def test_myheritage_path(self):
        """parse_genetic_file should work with a MyHeritage file path."""
        snps, fmt = parse_genetic_file(str(SAMPLE_MYHERITAGE_QUOTED))
        assert fmt == "myheritage"
        assert len(snps) > 0

    def test_vcf_path(self):
        """parse_genetic_file should work with a VCF file path."""
        snps, fmt = parse_genetic_file(str(SAMPLE_VCF))
        assert fmt == "vcf"
        assert len(snps) > 0

    def test_bytesio_23andme(self):
        """parse_genetic_file should work with BytesIO 23andMe data."""
        content = SAMPLE_23ANDME.read_text(encoding="utf-8")
        bio = BytesIO(content.encode("utf-8"))
        snps, fmt = parse_genetic_file(bio)
        assert fmt == "23andme"
        assert len(snps) > 0

    def test_bytesio_vcf(self):
        """parse_genetic_file should work with BytesIO VCF data."""
        content = SAMPLE_VCF.read_text(encoding="utf-8")
        bio = BytesIO(content.encode("utf-8"))
        snps, fmt = parse_genetic_file(bio)
        assert fmt == "vcf"
        assert len(snps) > 0

    def test_unknown_format_raises(self):
        """parse_genetic_file should raise ValueError for unrecognized format."""
        bio = BytesIO(b"random garbage content\nno format markers\n")
        with pytest.raises(ValueError, match="Unrecognized genetic data format"):
            parse_genetic_file(bio)

    def test_file_size_limit_enforced(self):
        """parse_genetic_file should reject oversized files."""

        class FakeBigBytesIO(BytesIO):
            """BytesIO subclass that reports an oversized getvalue()."""

            def getvalue(self):
                return b"x" * (MAX_FILE_SIZE_BYTES + 1)

        big_bio = FakeBigBytesIO(b"tiny")
        with pytest.raises(ValueError, match="File too large"):
            parse_genetic_file(big_bio)

    def test_streaming_output_matches_content_based(self):
        """Streaming parse_genetic_file should produce identical results
        to what the old content-based parsers produced."""
        # 23andMe
        content_23 = SAMPLE_23ANDME.read_text(encoding="utf-8")
        expected_23 = _parse_23andme_from_content(content_23)
        actual_23, fmt_23 = parse_genetic_file(str(SAMPLE_23ANDME))
        assert fmt_23 == "23andme"
        assert actual_23 == expected_23

        # AncestryDNA
        content_anc = SAMPLE_ANCESTRY.read_text(encoding="utf-8")
        expected_anc = _parse_ancestry_from_content(content_anc)
        actual_anc, fmt_anc = parse_genetic_file(str(SAMPLE_ANCESTRY))
        assert fmt_anc == "ancestry"
        assert actual_anc == expected_anc

        # MyHeritage
        content_mh = SAMPLE_MYHERITAGE_QUOTED.read_text(encoding="utf-8")
        expected_mh = _parse_myheritage_from_content(content_mh)
        actual_mh, fmt_mh = parse_genetic_file(str(SAMPLE_MYHERITAGE_QUOTED))
        assert fmt_mh == "myheritage"
        assert actual_mh == expected_mh

        # VCF
        content_vcf = SAMPLE_VCF.read_text(encoding="utf-8")
        expected_vcf = _parse_vcf_from_content(content_vcf)
        actual_vcf, fmt_vcf = parse_genetic_file(str(SAMPLE_VCF))
        assert fmt_vcf == "vcf"
        assert actual_vcf == expected_vcf


# ===================================================================
# Backward compatibility: _read_file_content still works
# ===================================================================

class TestReadFileContentBackwardCompat:
    """Ensure the deprecated _read_file_content still works."""

    def test_read_file_content_str_path(self):
        content = _read_file_content(str(SAMPLE_23ANDME))
        assert isinstance(content, str)
        assert "23andMe" in content

    def test_read_file_content_bytesio(self):
        raw = SAMPLE_23ANDME.read_bytes()
        bio = BytesIO(raw)
        content = _read_file_content(bio)
        assert isinstance(content, str)
        assert len(content) > 0
