"""Comprehensive test suite for Source/parser.py -- genetic data file parser.

Covers all four formats (23andMe, AncestryDNA, MyHeritage/FTDNA, VCF),
format detection, validation, parsing, edge cases, error handling,
genotype statistics, and return value structure.

The streaming parser tests live in test_parser_streaming.py; this file
focuses on the public API, format-specific validators/parsers, and
edge-case coverage that is not addressed elsewhere.
"""

from io import BytesIO, StringIO
from pathlib import Path

import pytest
from Source.parser import (
    _detect_format_from_content,
    detect_format,
    get_detailed_stats,
    get_genotype_stats,
    parse_23andme,
    parse_23andme_with_metadata,
    parse_ancestry,
    parse_genetic_file,
    parse_myheritage,
    parse_vcf,
    validate_23andme_format,
    validate_23andme_format_from_content,
    validate_ancestry_format,
    validate_ancestry_format_from_content,
    validate_genetic_file,
    validate_myheritage_format,
    validate_myheritage_format_from_content,
    validate_vcf_format,
    validate_vcf_format_from_content,
)

# ---------------------------------------------------------------------------
# Paths to sample data
# ---------------------------------------------------------------------------
SAMPLE_DIR = Path(__file__).resolve().parent.parent / "sample_data"

SAMPLE_23ANDME = SAMPLE_DIR / "23andme" / "sample_23andme_v3_carrier_01.txt"
SAMPLE_23ANDME_V4 = SAMPLE_DIR / "23andme" / "sample_23andme_v4_female_01.txt"
SAMPLE_23ANDME_V5 = SAMPLE_DIR / "23andme" / "sample_23andme_v5_male_02.txt"
SAMPLE_ANCESTRY = SAMPLE_DIR / "ancestry" / "sample_ancestry_v1_female_01.txt"
SAMPLE_ANCESTRY_V2 = SAMPLE_DIR / "ancestry" / "sample_ancestry_v2_diverse_01.txt"
SAMPLE_MYHERITAGE_QUOTED = SAMPLE_DIR / "myheritage" / "sample1_quoted.csv"
SAMPLE_MYHERITAGE_UNQUOTED = SAMPLE_DIR / "myheritage" / "sample5_unquoted.csv"
SAMPLE_VCF = SAMPLE_DIR / "vcf" / "sample_vcf_panel_01.vcf"
SAMPLE_VCF_WGS = SAMPLE_DIR / "vcf" / "sample_vcf_wgs_male_01.vcf"
SAMPLE_VCF_CLINICAL = SAMPLE_DIR / "vcf" / "sample_vcf_clinical_01.vcf"


# ---------------------------------------------------------------------------
# Fixtures: synthetic file content
# ---------------------------------------------------------------------------

@pytest.fixture()
def valid_23andme_content():
    """Minimal valid 23andMe file content."""
    return (
        "# This data file generated by 23andMe at: Thu Feb 05 2026\n"
        "#\n"
        "# rsid\tchromosome\tposition\tgenotype\n"
        "rs4477212\t1\t82154\tAA\n"
        "rs3094315\t1\t752566\tAG\n"
        "rs3131972\t1\t752721\tGG\n"
        "rs12124819\t1\t776546\tAA\n"
        "rs11240777\t1\t798959\tAG\n"
        "rs6681049\t1\t800007\tCC\n"
        "rs4970383\t1\t838555\tAC\n"
        "rs4475691\t1\t846808\tCC\n"
        "rs7537756\t1\t854250\tAG\n"
        "rs13302982\t1\t861808\tGG\n"
        "rs1110052\t1\t873558\tGT\n"
    )


@pytest.fixture()
def valid_ancestry_content():
    """Minimal valid AncestryDNA file content."""
    return (
        "#AncestryDNA raw data download\n"
        "#This file was generated by AncestryDNA\n"
        "#\n"
        "rsid\tchromosome\tposition\tallele1\tallele2\n"
        "rs4477212\t1\t82154\tA\tA\n"
        "rs3094315\t1\t752566\tA\tG\n"
        "rs3131972\t1\t752721\tG\tG\n"
        "rs12124819\t1\t776546\tA\tA\n"
        "rs11240777\t1\t798959\tA\tG\n"
        "rs6681049\t1\t800007\tC\tC\n"
        "rs4970383\t1\t838555\tA\tC\n"
        "rs4475691\t1\t846808\tC\tC\n"
        "rs7537756\t1\t854250\tA\tG\n"
        "rs13302982\t1\t861808\tG\tG\n"
        "rs1110052\t1\t873558\tG\tT\n"
    )


@pytest.fixture()
def valid_myheritage_content():
    """Minimal valid MyHeritage CSV file content (quoted)."""
    return (
        'RSID,CHROMOSOME,POSITION,RESULT\n'
        '"rs4477212","1","82154","AA"\n'
        '"rs3094315","1","752566","AG"\n'
        '"rs3131972","1","752721","GG"\n'
        '"rs12124819","1","776546","AA"\n'
        '"rs11240777","1","798959","AG"\n'
        '"rs6681049","1","800007","CC"\n'
        '"rs4970383","1","838555","AC"\n'
        '"rs4475691","1","846808","CC"\n'
        '"rs7537756","1","854250","AG"\n'
        '"rs13302982","1","861808","GG"\n'
        '"rs1110052","1","873558","GT"\n'
    )


@pytest.fixture()
def valid_vcf_content():
    """Minimal valid VCF file content."""
    return (
        "##fileformat=VCFv4.2\n"
        "##source=TestGenerator\n"
        "##reference=GRCh38\n"
        "#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\tFORMAT\tSAMPLE\n"
        "1\t82154\trs4477212\tA\tG\t.\tPASS\tNS=1\tGT\t0/0\n"
        "1\t752566\trs3094315\tA\tG\t.\tPASS\tNS=1\tGT\t0/1\n"
        "1\t752721\trs3131972\tG\tA\t.\tPASS\tNS=1\tGT\t0/0\n"
        "1\t776546\trs12124819\tA\tT\t.\tPASS\tNS=1\tGT\t0/0\n"
        "1\t798959\trs11240777\tA\tG\t.\tPASS\tNS=1\tGT\t0/1\n"
        "1\t800007\trs6681049\tC\tT\t.\tPASS\tNS=1\tGT\t0/0\n"
        "1\t838555\trs4970383\tA\tC\t.\tPASS\tNS=1\tGT\t0/1\n"
        "1\t846808\trs4475691\tC\tT\t.\tPASS\tNS=1\tGT\t0/0\n"
        "1\t854250\trs7537756\tA\tG\t.\tPASS\tNS=1\tGT\t0/1\n"
        "1\t861808\trs13302982\tG\tA\t.\tPASS\tNS=1\tGT\t0/0\n"
        "1\t873558\trs1110052\tG\tT\t.\tPASS\tNS=1\tGT\t0/1\n"
    )


# ===================================================================
# 1. Format Detection Tests
# ===================================================================

class TestDetectFormat:
    """Test detect_format and _detect_format_from_content."""

    def test_detect_format_23andme_file(self):
        """detect_format should identify a 23andMe file from disk path."""
        assert detect_format(str(SAMPLE_23ANDME)) == "23andme"

    def test_detect_format_ancestry_file(self):
        """detect_format should identify an AncestryDNA file from disk path."""
        assert detect_format(str(SAMPLE_ANCESTRY)) == "ancestry"

    def test_detect_format_myheritage_quoted_file(self):
        """detect_format should identify a MyHeritage file (quoted CSV) from disk path."""
        assert detect_format(str(SAMPLE_MYHERITAGE_QUOTED)) == "myheritage"

    def test_detect_format_myheritage_unquoted_file(self):
        """detect_format should identify a MyHeritage file (unquoted CSV) from disk path."""
        assert detect_format(str(SAMPLE_MYHERITAGE_UNQUOTED)) == "myheritage"

    def test_detect_format_vcf_file(self):
        """detect_format should identify a VCF file from disk path."""
        assert detect_format(str(SAMPLE_VCF)) == "vcf"

    def test_detect_format_vcf_clinical(self):
        """detect_format should identify the clinical VCF sample."""
        assert detect_format(str(SAMPLE_VCF_CLINICAL)) == "vcf"

    def test_detect_format_bytesio_23andme(self, valid_23andme_content):
        """detect_format should work with BytesIO for 23andMe."""
        bio = BytesIO(valid_23andme_content.encode("utf-8"))
        assert detect_format(bio) == "23andme"

    def test_detect_format_bytesio_ancestry(self, valid_ancestry_content):
        """detect_format should work with BytesIO for AncestryDNA."""
        bio = BytesIO(valid_ancestry_content.encode("utf-8"))
        assert detect_format(bio) == "ancestry"

    def test_detect_format_bytesio_vcf(self, valid_vcf_content):
        """detect_format should work with BytesIO for VCF."""
        bio = BytesIO(valid_vcf_content.encode("utf-8"))
        assert detect_format(bio) == "vcf"

    def test_detect_format_unknown_garbage(self):
        """detect_format should return 'unknown' for random content."""
        bio = BytesIO(b"this is just garbage content\nwith no markers\n")
        assert detect_format(bio) == "unknown"

    def test_detect_format_empty_file(self):
        """detect_format should return 'unknown' for an empty file."""
        bio = BytesIO(b"")
        assert detect_format(bio) == "unknown"

    def test_detect_format_nonexistent_path(self, tmp_path):
        """detect_format should return 'unknown' for a missing file."""
        fake_path = str(tmp_path / "nonexistent.txt")
        assert detect_format(fake_path) == "unknown"

    def test_detect_format_binary_content(self):
        """detect_format should return 'unknown' for binary/non-UTF-8 content."""
        bio = BytesIO(bytes(range(256)))
        assert detect_format(bio) == "unknown"

    def test_detect_23andme_without_header_comment(self):
        """detect_format should identify 23andMe by data line heuristic even without comment header."""
        content = (
            "rs4477212\t1\t82154\tAA\n"
            "rs3094315\t1\t752566\tAG\n"
            "rs3131972\t1\t752721\tGG\n"
            "rs12124819\t1\t776546\tAA\n"
            "rs11240777\t1\t798959\tAG\n"
            "rs6681049\t1\t800007\tCC\n"
            "rs4970383\t1\t838555\tAC\n"
            "rs4475691\t1\t846808\tCC\n"
            "rs7537756\t1\t854250\tAG\n"
            "rs13302982\t1\t861808\tGG\n"
        )
        assert _detect_format_from_content(content) == "23andme"

    def test_detect_myheritage_without_header_row(self):
        """detect_format should identify MyHeritage by CSV data heuristic."""
        content = (
            "rs4477212,1,82154,AA\n"
            "rs3094315,1,752566,AG\n"
            "rs3131972,1,752721,GG\n"
            "rs12124819,1,776546,AA\n"
            "rs11240777,1,798959,AG\n"
        )
        assert _detect_format_from_content(content) == "myheritage"

    def test_detect_ancestry_by_header_row_without_comment(self):
        """detect_format should identify AncestryDNA by allele1/allele2 header."""
        content = (
            "rsid\tchromosome\tposition\tallele1\tallele2\n"
            "rs4477212\t1\t82154\tA\tA\n"
            "rs3094315\t1\t752566\tA\tG\n"
        )
        assert _detect_format_from_content(content) == "ancestry"

    @pytest.mark.parametrize("version_line", [
        "##fileformat=VCFv4.1",
        "##fileformat=VCFv4.2",
        "##fileformat=VCFv4.3",
    ])
    def test_detect_vcf_various_versions(self, version_line):
        """detect_format should identify VCF regardless of minor version."""
        content = (
            f"{version_line}\n"
            "#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\tFORMAT\tSAMPLE\n"
            "1\t100\trs1\tA\tG\t.\tPASS\tNS=1\tGT\t0/1\n"
        )
        assert _detect_format_from_content(content) == "vcf"


# ===================================================================
# 2. 23andMe Parsing Tests
# ===================================================================

class TestParse23andMe:
    """Test parse_23andme and validation."""

    def test_parse_23andme_from_path(self):
        """parse_23andme should parse a real sample file from disk."""
        snps = parse_23andme(str(SAMPLE_23ANDME))
        assert isinstance(snps, dict)
        assert len(snps) > 0
        # Check known rsid from the sample
        assert "rs75030207" in snps

    def test_parse_23andme_from_bytesio(self):
        """parse_23andme should parse from BytesIO."""
        content = SAMPLE_23ANDME.read_text(encoding="utf-8")
        bio = BytesIO(content.encode("utf-8"))
        snps = parse_23andme(bio)
        assert isinstance(snps, dict)
        assert len(snps) > 0

    def test_parse_23andme_from_stringio(self, valid_23andme_content):
        """parse_23andme should parse from StringIO."""
        sio = StringIO(valid_23andme_content)
        snps = parse_23andme(sio)
        assert len(snps) == 11

    def test_parse_23andme_genotype_values(self, valid_23andme_content):
        """Genotype values should be correct for known rsids."""
        bio = BytesIO(valid_23andme_content.encode("utf-8"))
        snps = parse_23andme(bio)
        assert snps["rs4477212"] == "AA"
        assert snps["rs3094315"] == "AG"
        assert snps["rs1110052"] == "GT"

    def test_parse_23andme_skips_no_calls(self):
        """No-call entries (genotype '--') should be skipped."""
        content = (
            "# 23andMe data\n"
            "# rsid\tchromosome\tposition\tgenotype\n"
            "rs4477212\t1\t82154\tAA\n"
            "rs3094315\t1\t752566\t--\n"
            "rs3131972\t1\t752721\tGG\n"
        )
        bio = BytesIO(content.encode("utf-8"))
        snps = parse_23andme(bio)
        assert "rs3094315" not in snps
        assert len(snps) == 2

    def test_parse_23andme_skips_non_rs_header_rows(self):
        """Uncommented header rows starting with 'SNP' or 'ID' should be skipped.

        Note: 'rsid' starts with 'rs' so the parser treats it as a valid ID;
        only header keywords that do NOT start with 'rs'/'i' are skipped.
        """
        content = (
            "# 23andMe data\n"
            "# rsid\tchromosome\tposition\tgenotype\n"
            "SNP\tchromosome\tposition\tgenotype\n"
            "rs4477212\t1\t82154\tAA\n"
            "rs3094315\t1\t752566\tAG\n"
        )
        bio = BytesIO(content.encode("utf-8"))
        snps = parse_23andme(bio)
        assert "SNP" not in snps
        assert len(snps) == 2

    def test_parse_23andme_file_not_found(self, tmp_path):
        """parse_23andme should raise FileNotFoundError for missing files."""
        with pytest.raises(FileNotFoundError):
            parse_23andme(str(tmp_path / "nonexistent.txt"))

    def test_parse_23andme_invalid_format_raises(self):
        """parse_23andme should raise ValueError for invalid format."""
        content = "just some random text\nno valid data here\n"
        bio = BytesIO(content.encode("utf-8"))
        with pytest.raises(ValueError, match="Invalid 23andMe"):
            parse_23andme(bio)

    def test_parse_23andme_empty_data_raises(self):
        """parse_23andme should raise ValueError when no valid SNPs found."""
        content = (
            "# 23andMe data\n"
            "# rsid\tchromosome\tposition\tgenotype\n"
            "rs4477212\t1\t82154\t--\n"
            "rs3094315\t1\t752566\t--\n"
        )
        bio = BytesIO(content.encode("utf-8"))
        with pytest.raises(ValueError, match="No valid SNP data"):
            parse_23andme(bio)

    def test_parse_23andme_v4_sample(self):
        """parse_23andme should parse a v4 sample file."""
        snps = parse_23andme(str(SAMPLE_23ANDME_V4))
        assert isinstance(snps, dict)
        assert len(snps) > 0

    def test_parse_23andme_v5_sample(self):
        """parse_23andme should parse a v5 sample file."""
        snps = parse_23andme(str(SAMPLE_23ANDME_V5))
        assert isinstance(snps, dict)
        assert len(snps) > 0

    def test_parse_23andme_accepts_indel_ids(self, valid_23andme_content):
        """Parser should accept 'i'-prefixed IDs (internal/indel markers)."""
        content = valid_23andme_content + "i4000759\t1\t900000\tDI\n"
        bio = BytesIO(content.encode("utf-8"))
        snps = parse_23andme(bio)
        assert "i4000759" in snps
        assert snps["i4000759"] == "DI"


# ===================================================================
# 3. 23andMe Validation Tests
# ===================================================================

class TestValidate23andMe:
    """Test validate_23andme_format and validate_23andme_format_from_content."""

    def test_validate_valid_file(self):
        """validate_23andme_format should accept a real sample file."""
        is_valid, err = validate_23andme_format(str(SAMPLE_23ANDME))
        assert is_valid is True
        assert err == ""

    def test_validate_valid_content(self, valid_23andme_content):
        """validate_23andme_format_from_content should accept valid content."""
        is_valid, err = validate_23andme_format_from_content(valid_23andme_content)
        assert is_valid is True
        assert err == ""

    def test_validate_too_short(self):
        """Content with fewer than 2 lines should be invalid."""
        is_valid, err = validate_23andme_format_from_content("single line")
        assert is_valid is False
        assert "too short" in err

    def test_validate_no_header_signature(self):
        """Content without 23andMe signature should be invalid."""
        content = (
            "# Some random file\n"
            "rs4477212\t1\t82154\tAA\n"
            "rs3094315\t1\t752566\tAG\n"
        )
        is_valid, err = validate_23andme_format_from_content(content)
        assert is_valid is False
        assert "missing header signature" in err

    def test_validate_only_comments(self):
        """Content with only comments (no data lines) should be invalid."""
        content = (
            "# 23andMe data\n"
            "# rsid\tchromosome\tposition\tgenotype\n"
            "# Just comments, no data\n"
        )
        is_valid, err = validate_23andme_format_from_content(content)
        assert is_valid is False
        assert "no data lines" in err

    def test_validate_wrong_format_data(self):
        """Content with wrong format data lines should be invalid."""
        content = (
            "# 23andMe data\n"
            "garbage data line 1\n"
            "garbage data line 2\n"
            "garbage data line 3\n"
            "garbage data line 4\n"
            "garbage data line 5\n"
            "garbage data line 6\n"
            "garbage data line 7\n"
            "garbage data line 8\n"
            "garbage data line 9\n"
            "garbage data line 10\n"
        )
        is_valid, err = validate_23andme_format_from_content(content)
        assert is_valid is False

    def test_validate_bytesio(self, valid_23andme_content):
        """validate_23andme_format should accept BytesIO input."""
        bio = BytesIO(valid_23andme_content.encode("utf-8"))
        is_valid, err = validate_23andme_format(bio)
        assert is_valid is True

    def test_validate_nonexistent_file(self, tmp_path):
        """validate_23andme_format should return False for missing file."""
        is_valid, err = validate_23andme_format(str(tmp_path / "missing.txt"))
        assert is_valid is False
        assert "File not found" in err

    def test_validate_binary_file(self):
        """validate_23andme_format should handle non-UTF-8 binary gracefully."""
        bio = BytesIO(bytes(range(256)))
        is_valid, err = validate_23andme_format(bio)
        assert is_valid is False


# ===================================================================
# 4. AncestryDNA Parsing Tests
# ===================================================================

class TestParseAncestry:
    """Test parse_ancestry and validation."""

    def test_parse_ancestry_from_path(self):
        """parse_ancestry should parse a real sample file from disk."""
        snps = parse_ancestry(str(SAMPLE_ANCESTRY))
        assert isinstance(snps, dict)
        assert len(snps) > 0
        assert "rs75030207" in snps

    def test_parse_ancestry_from_bytesio(self, valid_ancestry_content):
        """parse_ancestry should parse from BytesIO."""
        bio = BytesIO(valid_ancestry_content.encode("utf-8"))
        snps = parse_ancestry(bio)
        assert len(snps) == 11

    def test_parse_ancestry_genotype_concatenation(self, valid_ancestry_content):
        """Allele1 and allele2 should be concatenated into genotype."""
        bio = BytesIO(valid_ancestry_content.encode("utf-8"))
        snps = parse_ancestry(bio)
        assert snps["rs4477212"] == "AA"
        assert snps["rs3094315"] == "AG"
        assert snps["rs1110052"] == "GT"

    def test_parse_ancestry_skips_no_calls(self):
        """No-call entries (allele value '0') should be skipped."""
        content = (
            "#AncestryDNA raw data download\n"
            "rsid\tchromosome\tposition\tallele1\tallele2\n"
            "rs4477212\t1\t82154\tA\tA\n"
            "rs3094315\t1\t752566\t0\t0\n"
            "rs3131972\t1\t752721\tG\tG\n"
        )
        bio = BytesIO(content.encode("utf-8"))
        snps = parse_ancestry(bio)
        assert "rs3094315" not in snps
        assert len(snps) == 2

    def test_parse_ancestry_skips_header_row(self, valid_ancestry_content):
        """Header row with column names should be skipped."""
        bio = BytesIO(valid_ancestry_content.encode("utf-8"))
        snps = parse_ancestry(bio)
        assert "rsid" not in snps

    def test_parse_ancestry_invalid_format_raises(self):
        """parse_ancestry should raise ValueError for invalid format."""
        bio = BytesIO(b"random text content\n")
        with pytest.raises(ValueError, match="Invalid AncestryDNA"):
            parse_ancestry(bio)

    def test_parse_ancestry_v2_sample(self):
        """parse_ancestry should parse a v2 sample file."""
        snps = parse_ancestry(str(SAMPLE_ANCESTRY_V2))
        assert isinstance(snps, dict)
        assert len(snps) > 0

    def test_parse_ancestry_case_insensitive_alleles(self):
        """Alleles should be uppercased."""
        content = (
            "#AncestryDNA raw data download\n"
            "rsid\tchromosome\tposition\tallele1\tallele2\n"
            "rs4477212\t1\t82154\ta\tg\n"
            "rs3094315\t1\t752566\tc\tt\n"
        )
        bio = BytesIO(content.encode("utf-8"))
        snps = parse_ancestry(bio)
        assert snps["rs4477212"] == "AG"
        assert snps["rs3094315"] == "CT"


# ===================================================================
# 5. AncestryDNA Validation Tests
# ===================================================================

class TestValidateAncestry:
    """Test validate_ancestry_format and validate_ancestry_format_from_content."""

    def test_validate_valid_file(self):
        """validate_ancestry_format should accept a real sample file."""
        is_valid, err = validate_ancestry_format(str(SAMPLE_ANCESTRY))
        assert is_valid is True
        assert err == ""

    def test_validate_valid_content(self, valid_ancestry_content):
        """validate_ancestry_format_from_content should accept valid content."""
        is_valid, err = validate_ancestry_format_from_content(valid_ancestry_content)
        assert is_valid is True

    def test_validate_too_short(self):
        """Content with fewer than 2 lines should be invalid."""
        is_valid, err = validate_ancestry_format_from_content("single line")
        assert is_valid is False
        assert "too short" in err

    def test_validate_no_ancestry_header(self):
        """Content without AncestryDNA or allele header should be invalid."""
        content = (
            "# Some random file\n"
            "rs4477212\t1\t82154\tA\tA\n"
        )
        is_valid, err = validate_ancestry_format_from_content(content)
        assert is_valid is False
        assert "missing header signature" in err

    def test_validate_nonexistent_file(self, tmp_path):
        """validate_ancestry_format should return False for missing file."""
        is_valid, err = validate_ancestry_format(str(tmp_path / "missing.txt"))
        assert is_valid is False

    def test_validate_binary_file(self):
        """validate_ancestry_format should handle non-UTF-8 binary gracefully."""
        bio = BytesIO(bytes(range(256)))
        is_valid, err = validate_ancestry_format(bio)
        assert is_valid is False
        assert "encoding error" in err


# ===================================================================
# 6. MyHeritage Parsing Tests
# ===================================================================

class TestParseMyHeritage:
    """Test parse_myheritage and validation."""

    def test_parse_myheritage_quoted_csv(self):
        """parse_myheritage should parse a quoted CSV sample file."""
        snps = parse_myheritage(str(SAMPLE_MYHERITAGE_QUOTED))
        assert isinstance(snps, dict)
        assert len(snps) > 0
        assert "rs75030207" in snps

    def test_parse_myheritage_unquoted_csv(self):
        """parse_myheritage should parse an unquoted CSV sample file."""
        snps = parse_myheritage(str(SAMPLE_MYHERITAGE_UNQUOTED))
        assert isinstance(snps, dict)
        assert len(snps) > 0

    def test_parse_myheritage_from_bytesio(self, valid_myheritage_content):
        """parse_myheritage should parse from BytesIO."""
        bio = BytesIO(valid_myheritage_content.encode("utf-8"))
        snps = parse_myheritage(bio)
        assert len(snps) == 11

    def test_parse_myheritage_genotype_values(self, valid_myheritage_content):
        """Genotype values should be correct for known rsids."""
        bio = BytesIO(valid_myheritage_content.encode("utf-8"))
        snps = parse_myheritage(bio)
        assert snps["rs4477212"] == "AA"
        assert snps["rs3094315"] == "AG"

    def test_parse_myheritage_skips_no_calls(self):
        """No-call entries (result '--') should be skipped."""
        content = (
            "RSID,CHROMOSOME,POSITION,RESULT\n"
            "rs4477212,1,82154,AA\n"
            "rs3094315,1,752566,--\n"
            "rs3131972,1,752721,GG\n"
        )
        bio = BytesIO(content.encode("utf-8"))
        snps = parse_myheritage(bio)
        assert "rs3094315" not in snps
        assert len(snps) == 2

    def test_parse_myheritage_accepts_vg_ids(self):
        """Parser should accept VG-prefixed proprietary IDs."""
        content = (
            "RSID,CHROMOSOME,POSITION,RESULT\n"
            "rs4477212,1,82154,AA\n"
            "VG01S345,1,90000,AG\n"
        )
        bio = BytesIO(content.encode("utf-8"))
        snps = parse_myheritage(bio)
        assert "VG01S345" in snps

    def test_parse_myheritage_invalid_format_raises(self):
        """parse_myheritage should raise ValueError for invalid format."""
        bio = BytesIO(b"random text content\n")
        with pytest.raises(ValueError, match="Invalid MyHeritage"):
            parse_myheritage(bio)

    def test_parse_myheritage_skips_header_row(self, valid_myheritage_content):
        """Header row with RSID should be skipped."""
        bio = BytesIO(valid_myheritage_content.encode("utf-8"))
        snps = parse_myheritage(bio)
        assert "RSID" not in snps
        assert "rsid" not in snps


# ===================================================================
# 7. MyHeritage Validation Tests
# ===================================================================

class TestValidateMyHeritage:
    """Test validate_myheritage_format and validate_myheritage_format_from_content."""

    def test_validate_valid_file(self):
        """validate_myheritage_format should accept a real sample file."""
        is_valid, err = validate_myheritage_format(str(SAMPLE_MYHERITAGE_QUOTED))
        assert is_valid is True

    def test_validate_valid_unquoted(self):
        """validate_myheritage_format should accept an unquoted CSV."""
        is_valid, err = validate_myheritage_format(str(SAMPLE_MYHERITAGE_UNQUOTED))
        assert is_valid is True

    def test_validate_too_short(self):
        """Content with fewer than 2 lines should be invalid."""
        is_valid, err = validate_myheritage_format_from_content("single line")
        assert is_valid is False
        assert "too short" in err

    def test_validate_no_header(self):
        """Content without recognized header should fail if data is bad too."""
        content = (
            "foo,bar,baz,qux\n"
            "not_valid,data,here,XX\n"
        )
        is_valid, err = validate_myheritage_format_from_content(content)
        assert is_valid is False

    def test_validate_nonexistent_file(self, tmp_path):
        """validate_myheritage_format should return False for missing file."""
        is_valid, err = validate_myheritage_format(str(tmp_path / "missing.csv"))
        assert is_valid is False

    def test_validate_binary_file(self):
        """validate_myheritage_format should handle non-UTF-8 binary gracefully."""
        bio = BytesIO(bytes(range(256)))
        is_valid, err = validate_myheritage_format(bio)
        assert is_valid is False
        assert "encoding error" in err


# ===================================================================
# 8. VCF Parsing Tests
# ===================================================================

class TestParseVCF:
    """Test parse_vcf and VCF-specific parsing logic."""

    def test_parse_vcf_from_path(self):
        """parse_vcf should parse a real VCF sample file."""
        snps = parse_vcf(str(SAMPLE_VCF))
        assert isinstance(snps, dict)
        assert len(snps) > 0

    def test_parse_vcf_from_bytesio(self, valid_vcf_content):
        """parse_vcf should parse from BytesIO."""
        bio = BytesIO(valid_vcf_content.encode("utf-8"))
        snps = parse_vcf(bio)
        assert len(snps) > 0

    def test_parse_vcf_genotype_values(self, valid_vcf_content):
        """Genotype values should be correctly resolved from GT indices."""
        bio = BytesIO(valid_vcf_content.encode("utf-8"))
        snps = parse_vcf(bio)
        # rs4477212: REF=A, ALT=G, GT=0/0 -> AA
        assert snps["rs4477212"] == "AA"
        # rs3094315: REF=A, ALT=G, GT=0/1 -> AG
        assert snps["rs3094315"] == "AG"

    def test_parse_vcf_homozygous_alt(self):
        """VCF parser should handle homozygous ALT genotype (1/1)."""
        content = (
            "##fileformat=VCFv4.2\n"
            "#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\tFORMAT\tSAMPLE\n"
            "1\t100\trs123\tA\tG\t.\tPASS\tNS=1\tGT\t1/1\n"
        )
        bio = BytesIO(content.encode("utf-8"))
        snps = parse_vcf(bio)
        assert snps["rs123"] == "GG"

    def test_parse_vcf_phased_genotype(self):
        """VCF parser should handle phased genotypes (|)."""
        content = (
            "##fileformat=VCFv4.2\n"
            "#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\tFORMAT\tSAMPLE\n"
            "1\t100\trs123\tA\tG\t.\tPASS\tNS=1\tGT\t0|1\n"
        )
        bio = BytesIO(content.encode("utf-8"))
        snps = parse_vcf(bio)
        assert snps["rs123"] == "AG"

    def test_parse_vcf_skips_no_call(self):
        """VCF parser should skip no-call genotypes (./.)."""
        content = (
            "##fileformat=VCFv4.2\n"
            "#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\tFORMAT\tSAMPLE\n"
            "1\t100\trs123\tA\tG\t.\tPASS\tNS=1\tGT\t./.\n"
            "1\t200\trs456\tC\tT\t.\tPASS\tNS=1\tGT\t0/1\n"
        )
        bio = BytesIO(content.encode("utf-8"))
        snps = parse_vcf(bio)
        assert "rs123" not in snps
        assert "rs456" in snps

    def test_parse_vcf_skips_variants_without_rsid(self):
        """VCF parser should skip variants without rsIDs (ID='.')."""
        content = (
            "##fileformat=VCFv4.2\n"
            "#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\tFORMAT\tSAMPLE\n"
            "1\t100\t.\tA\tG\t.\tPASS\tNS=1\tGT\t0/1\n"
            "1\t200\trs456\tC\tT\t.\tPASS\tNS=1\tGT\t0/1\n"
        )
        bio = BytesIO(content.encode("utf-8"))
        snps = parse_vcf(bio)
        assert len(snps) == 1
        assert "rs456" in snps

    def test_parse_vcf_skips_indels(self):
        """VCF parser should skip indels (multi-base REF or ALT)."""
        content = (
            "##fileformat=VCFv4.2\n"
            "#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\tFORMAT\tSAMPLE\n"
            "1\t100\trs123\tAT\tA\t.\tPASS\tNS=1\tGT\t0/1\n"
            "1\t200\trs456\tC\tCGA\t.\tPASS\tNS=1\tGT\t0/1\n"
            "1\t300\trs789\tA\tG\t.\tPASS\tNS=1\tGT\t0/1\n"
        )
        bio = BytesIO(content.encode("utf-8"))
        snps = parse_vcf(bio)
        assert "rs123" not in snps  # multi-base REF
        assert "rs456" not in snps  # multi-base ALT
        assert "rs789" in snps

    def test_parse_vcf_multi_allelic(self):
        """VCF parser should handle multi-allelic sites with comma-separated ALTs."""
        content = (
            "##fileformat=VCFv4.2\n"
            "#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\tFORMAT\tSAMPLE\n"
            "1\t100\trs123\tA\tG,T\t.\tPASS\tNS=1\tGT\t1/2\n"
        )
        bio = BytesIO(content.encode("utf-8"))
        snps = parse_vcf(bio)
        # index 1 = G (first ALT), index 2 = T (second ALT)
        assert snps["rs123"] == "GT"

    def test_parse_vcf_gt_not_first_in_format(self):
        """VCF parser should find GT correctly even when not first in FORMAT."""
        content = (
            "##fileformat=VCFv4.2\n"
            "#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\tFORMAT\tSAMPLE\n"
            "1\t100\trs123\tA\tG\t.\tPASS\tNS=1\tDP:GT:GQ\t30:0/1:99\n"
        )
        bio = BytesIO(content.encode("utf-8"))
        snps = parse_vcf(bio)
        assert snps["rs123"] == "AG"

    def test_parse_vcf_invalid_format_raises(self):
        """parse_vcf should raise ValueError for invalid format."""
        bio = BytesIO(b"random text content\n")
        with pytest.raises(ValueError, match="Invalid VCF"):
            parse_vcf(bio)

    def test_parse_vcf_clinical_sample(self):
        """parse_vcf should parse the clinical VCF sample."""
        snps = parse_vcf(str(SAMPLE_VCF_CLINICAL))
        assert isinstance(snps, dict)
        assert len(snps) > 0

    def test_parse_vcf_wgs_sample(self):
        """parse_vcf should parse the WGS VCF sample."""
        snps = parse_vcf(str(SAMPLE_VCF_WGS))
        assert isinstance(snps, dict)
        assert len(snps) > 0

    def test_parse_vcf_half_call_skipped(self):
        """VCF parser should skip half-calls where one allele is '.'."""
        content = (
            "##fileformat=VCFv4.2\n"
            "#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\tFORMAT\tSAMPLE\n"
            "1\t100\trs123\tA\tG\t.\tPASS\tNS=1\tGT\t./0\n"
            "1\t200\trs456\tC\tT\t.\tPASS\tNS=1\tGT\t0/1\n"
        )
        bio = BytesIO(content.encode("utf-8"))
        snps = parse_vcf(bio)
        assert "rs123" not in snps
        assert "rs456" in snps


# ===================================================================
# 9. VCF Validation Tests
# ===================================================================

class TestValidateVCF:
    """Test validate_vcf_format and validate_vcf_format_from_content."""

    def test_validate_valid_file(self):
        """validate_vcf_format should accept a real VCF sample."""
        is_valid, err = validate_vcf_format(str(SAMPLE_VCF))
        assert is_valid is True
        assert err == ""

    def test_validate_valid_content(self, valid_vcf_content):
        """validate_vcf_format_from_content should accept valid content."""
        is_valid, err = validate_vcf_format_from_content(valid_vcf_content)
        assert is_valid is True

    def test_validate_missing_fileformat_line(self):
        """VCF without ##fileformat line should be invalid."""
        content = (
            "#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\tFORMAT\tSAMPLE\n"
            "1\t100\trs123\tA\tG\t.\tPASS\tNS=1\tGT\t0/1\n"
        )
        is_valid, err = validate_vcf_format_from_content(content)
        assert is_valid is False
        assert "fileformat" in err.lower()

    def test_validate_missing_chrom_header(self):
        """VCF without #CHROM header should be invalid."""
        content = (
            "##fileformat=VCFv4.2\n"
            "1\t100\trs123\tA\tG\t.\tPASS\tNS=1\tGT\t0/1\n"
        )
        is_valid, err = validate_vcf_format_from_content(content)
        assert is_valid is False
        assert "CHROM" in err

    def test_validate_too_few_columns(self):
        """VCF with fewer than 10 columns in #CHROM header should be invalid."""
        content = (
            "##fileformat=VCFv4.2\n"
            "#CHROM\tPOS\tID\tREF\tALT\n"
            "1\t100\trs123\tA\tG\n"
        )
        is_valid, err = validate_vcf_format_from_content(content)
        assert is_valid is False
        assert "columns" in err

    def test_validate_no_data_lines(self):
        """VCF with headers but no data should be invalid."""
        content = (
            "##fileformat=VCFv4.2\n"
            "#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\tFORMAT\tSAMPLE\n"
        )
        is_valid, err = validate_vcf_format_from_content(content)
        assert is_valid is False
        assert "no data lines" in err.lower()

    def test_validate_no_gt_in_format(self):
        """VCF with FORMAT lacking GT should be invalid."""
        content = (
            "##fileformat=VCFv4.2\n"
            "#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\tFORMAT\tSAMPLE\n"
            "1\t100\trs123\tA\tG\t.\tPASS\tNS=1\tDP:GQ\t30:99\n"
        )
        is_valid, err = validate_vcf_format_from_content(content)
        assert is_valid is False

    def test_validate_too_short(self):
        """Content with fewer than 2 lines should be invalid."""
        is_valid, err = validate_vcf_format_from_content("single line")
        assert is_valid is False
        assert "too short" in err

    def test_validate_nonexistent_file(self, tmp_path):
        """validate_vcf_format should return False for missing file."""
        is_valid, err = validate_vcf_format(str(tmp_path / "missing.vcf"))
        assert is_valid is False

    def test_validate_binary_file(self):
        """validate_vcf_format should handle non-UTF-8 binary gracefully."""
        bio = BytesIO(bytes(range(256)))
        is_valid, err = validate_vcf_format(bio)
        assert is_valid is False
        assert "encoding error" in err


# ===================================================================
# 10. Universal Parser (parse_genetic_file) Tests
# ===================================================================

class TestParseGeneticFile:
    """Test the universal parse_genetic_file function."""

    def test_parse_23andme_file(self):
        """parse_genetic_file should auto-detect and parse 23andMe."""
        snps, fmt = parse_genetic_file(str(SAMPLE_23ANDME))
        assert fmt == "23andme"
        assert len(snps) > 0

    def test_parse_ancestry_file(self):
        """parse_genetic_file should auto-detect and parse AncestryDNA."""
        snps, fmt = parse_genetic_file(str(SAMPLE_ANCESTRY))
        assert fmt == "ancestry"
        assert len(snps) > 0

    def test_parse_myheritage_file(self):
        """parse_genetic_file should auto-detect and parse MyHeritage."""
        snps, fmt = parse_genetic_file(str(SAMPLE_MYHERITAGE_QUOTED))
        assert fmt == "myheritage"
        assert len(snps) > 0

    def test_parse_vcf_file(self):
        """parse_genetic_file should auto-detect and parse VCF."""
        snps, fmt = parse_genetic_file(str(SAMPLE_VCF))
        assert fmt == "vcf"
        assert len(snps) > 0

    def test_parse_unknown_format_raises(self):
        """parse_genetic_file should raise ValueError for unrecognized format."""
        bio = BytesIO(b"random garbage content\nno format markers\n")
        with pytest.raises(ValueError, match="Unrecognized genetic data format"):
            parse_genetic_file(bio)

    def test_parse_genetic_file_returns_tuple(self):
        """parse_genetic_file should return a 2-tuple of (dict, str)."""
        result = parse_genetic_file(str(SAMPLE_23ANDME))
        assert isinstance(result, tuple)
        assert len(result) == 2
        assert isinstance(result[0], dict)
        assert isinstance(result[1], str)


# ===================================================================
# 11. Universal Validator (validate_genetic_file) Tests
# ===================================================================

class TestValidateGeneticFile:
    """Test the universal validate_genetic_file function."""

    def test_validate_23andme(self):
        """validate_genetic_file should accept and identify a 23andMe file."""
        is_valid, err, fmt = validate_genetic_file(str(SAMPLE_23ANDME))
        assert is_valid is True
        assert fmt == "23andme"
        assert err == ""

    def test_validate_ancestry(self):
        """validate_genetic_file should accept and identify an AncestryDNA file."""
        is_valid, err, fmt = validate_genetic_file(str(SAMPLE_ANCESTRY))
        assert is_valid is True
        assert fmt == "ancestry"

    def test_validate_myheritage(self):
        """validate_genetic_file should accept and identify a MyHeritage file."""
        is_valid, err, fmt = validate_genetic_file(str(SAMPLE_MYHERITAGE_QUOTED))
        assert is_valid is True
        assert fmt == "myheritage"

    def test_validate_vcf(self):
        """validate_genetic_file should accept and identify a VCF file."""
        is_valid, err, fmt = validate_genetic_file(str(SAMPLE_VCF))
        assert is_valid is True
        assert fmt == "vcf"

    def test_validate_unknown_format(self):
        """validate_genetic_file should return unknown for garbage content."""
        bio = BytesIO(b"totally random content\n")
        is_valid, err, fmt = validate_genetic_file(bio)
        assert is_valid is False
        assert fmt == "unknown"

    def test_validate_binary_content(self):
        """validate_genetic_file should handle binary content gracefully."""
        bio = BytesIO(bytes(range(256)))
        is_valid, err, fmt = validate_genetic_file(bio)
        assert is_valid is False
        assert fmt == "unknown"
        assert "encoding error" in err

    def test_validate_returns_3_tuple(self):
        """validate_genetic_file should return a 3-tuple."""
        result = validate_genetic_file(str(SAMPLE_23ANDME))
        assert isinstance(result, tuple)
        assert len(result) == 3


# ===================================================================
# 12. Genotype Statistics Tests
# ===================================================================

class TestGenotypeStats:
    """Test get_genotype_stats and get_detailed_stats."""

    def test_get_genotype_stats_basic(self):
        """get_genotype_stats should compute correct stats."""
        snps = {"rs1": "AA", "rs2": "AG", "rs3": "TT", "rs4": "CT"}
        stats = get_genotype_stats(snps)
        assert stats["total_snps"] == 4
        assert stats["homozygous_count"] == 2  # AA, TT
        assert stats["heterozygous_count"] == 2  # AG, CT

    def test_get_genotype_stats_empty(self):
        """get_genotype_stats should handle empty dict."""
        stats = get_genotype_stats({})
        assert stats["total_snps"] == 0
        assert stats["homozygous_count"] == 0
        assert stats["heterozygous_count"] == 0

    def test_get_genotype_stats_single_allele(self):
        """Single-allele genotypes (e.g., X/Y in males) should count as homozygous."""
        snps = {"rs1": "A", "rs2": "T", "rs3": "AG"}
        stats = get_genotype_stats(snps)
        assert stats["homozygous_count"] == 2  # A, T
        assert stats["heterozygous_count"] == 1  # AG

    def test_get_genotype_stats_distribution(self):
        """get_genotype_stats should correctly count genotype distribution."""
        snps = {"rs1": "AA", "rs2": "AA", "rs3": "AG", "rs4": "GG"}
        stats = get_genotype_stats(snps)
        assert stats["genotype_distribution"]["AA"] == 2
        assert stats["genotype_distribution"]["AG"] == 1
        assert stats["genotype_distribution"]["GG"] == 1

    def test_get_detailed_stats_empty(self):
        """get_detailed_stats should handle empty SNPs."""
        stats = get_detailed_stats({}, {})
        assert stats["total_snps"] == 0
        assert stats["chromosomes"] == []

    def test_get_detailed_stats_with_metadata(self):
        """get_detailed_stats should use chromosome data from metadata."""
        snps = {"rs1": "AA", "rs2": "AG", "rs3": "GG"}
        metadata = {
            "chromosome_data": {"rs1": "1", "rs2": "1", "rs3": "2"},
            "position_data": {"rs1": "100", "rs2": "200", "rs3": "300"},
            "file_version": "v5"
        }
        stats = get_detailed_stats(snps, metadata)
        assert stats["total_snps"] == 3
        assert "1" in stats["chromosomes"]
        assert "2" in stats["chromosomes"]
        assert stats["chromosome_counts"]["1"] == 2
        assert stats["chromosome_counts"]["2"] == 1
        assert stats["file_version"] == "v5"


# ===================================================================
# 13. parse_23andme_with_metadata Tests
# ===================================================================

class TestParse23andMeWithMetadata:
    """Test parse_23andme_with_metadata."""

    def test_returns_tuple(self):
        """Should return a 2-tuple of (snps, metadata)."""
        result = parse_23andme_with_metadata(str(SAMPLE_23ANDME))
        assert isinstance(result, tuple)
        assert len(result) == 2

    def test_snps_dict(self):
        """First element should be a non-empty SNP dictionary."""
        snps, _ = parse_23andme_with_metadata(str(SAMPLE_23ANDME))
        assert isinstance(snps, dict)
        assert len(snps) > 0

    def test_metadata_structure(self):
        """Metadata should contain chromosome_data, position_data, file_version."""
        _, metadata = parse_23andme_with_metadata(str(SAMPLE_23ANDME))
        assert "chromosome_data" in metadata
        assert "position_data" in metadata
        assert "file_version" in metadata
        assert isinstance(metadata["chromosome_data"], dict)
        assert isinstance(metadata["position_data"], dict)

    def test_metadata_has_matching_rsids(self):
        """chromosome_data and position_data should have same rsids as snps."""
        snps, metadata = parse_23andme_with_metadata(str(SAMPLE_23ANDME))
        for rsid in snps:
            assert rsid in metadata["chromosome_data"]
            assert rsid in metadata["position_data"]

    def test_file_not_found(self, tmp_path):
        """Should raise FileNotFoundError for missing file."""
        with pytest.raises(FileNotFoundError):
            parse_23andme_with_metadata(str(tmp_path / "missing.txt"))

    def test_invalid_format_raises(self):
        """Should raise ValueError for invalid format."""
        bio = BytesIO(b"random text\n")
        with pytest.raises(ValueError, match="Invalid 23andMe"):
            parse_23andme_with_metadata(bio)

    def test_bytesio_input(self):
        """Should work with BytesIO input."""
        content = SAMPLE_23ANDME.read_text(encoding="utf-8")
        bio = BytesIO(content.encode("utf-8"))
        snps, metadata = parse_23andme_with_metadata(bio)
        assert len(snps) > 0

    def test_version_detection(self, valid_23andme_content):
        """Should detect version from header comment if present."""
        content = valid_23andme_content.replace(
            "# This data file generated by 23andMe at: Thu Feb 05 2026",
            "# This data file generated by 23andMe at: Thu Feb 05 2026\n# version: 5.0"
        )
        bio = BytesIO(content.encode("utf-8"))
        _, metadata = parse_23andme_with_metadata(bio)
        assert "version" in metadata["file_version"].lower()


# ===================================================================
# 14. Edge Cases and Error Handling
# ===================================================================

class TestEdgeCases:
    """Test edge cases across all formats."""

    def test_file_with_only_comments(self):
        """A file with only comments and no data should fail validation."""
        content = "# 23andMe data\n# Just comments\n# No data\n"
        is_valid, err = validate_23andme_format_from_content(content)
        assert is_valid is False

    def test_mixed_line_endings(self, valid_23andme_content):
        """Parser should handle mixed line endings (\\n, \\r\\n)."""
        # Replace some newlines with \r\n
        content = valid_23andme_content.replace("\n", "\r\n", 3)
        bio = BytesIO(content.encode("utf-8"))
        snps = parse_23andme(bio)
        assert len(snps) > 0

    def test_extra_whitespace_in_23andme(self):
        """Parser should handle extra whitespace in fields."""
        content = (
            "# 23andMe data\n"
            "# rsid\tchromosome\tposition\tgenotype\n"
            "rs4477212 \t 1 \t 82154 \t AA \n"
            "rs3094315\t1\t752566\tAG\n"
        )
        bio = BytesIO(content.encode("utf-8"))
        snps = parse_23andme(bio)
        assert "rs4477212" in snps
        assert snps["rs4477212"] == "AA"

    def test_ancestry_partial_no_call(self):
        """AncestryDNA with one allele as '0' should skip that SNP."""
        content = (
            "#AncestryDNA raw data download\n"
            "rsid\tchromosome\tposition\tallele1\tallele2\n"
            "rs4477212\t1\t82154\tA\t0\n"
            "rs3094315\t1\t752566\tA\tG\n"
        )
        bio = BytesIO(content.encode("utf-8"))
        snps = parse_ancestry(bio)
        assert "rs4477212" not in snps
        assert "rs3094315" in snps

    def test_vcf_allele_index_out_of_range(self):
        """VCF parser should skip entries where GT index exceeds allele list."""
        content = (
            "##fileformat=VCFv4.2\n"
            "#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\tFORMAT\tSAMPLE\n"
            "1\t100\trs123\tA\tG\t.\tPASS\tNS=1\tGT\t0/5\n"
            "1\t200\trs456\tC\tT\t.\tPASS\tNS=1\tGT\t0/1\n"
        )
        bio = BytesIO(content.encode("utf-8"))
        snps = parse_vcf(bio)
        assert "rs123" not in snps
        assert "rs456" in snps

    def test_vcf_dot_no_call(self):
        """VCF parser should skip single-dot no-call '.'."""
        content = (
            "##fileformat=VCFv4.2\n"
            "#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\tFORMAT\tSAMPLE\n"
            "1\t100\trs123\tA\tG\t.\tPASS\tNS=1\tGT\t.\n"
            "1\t200\trs456\tC\tT\t.\tPASS\tNS=1\tGT\t0/1\n"
        )
        bio = BytesIO(content.encode("utf-8"))
        snps = parse_vcf(bio)
        assert "rs123" not in snps

    def test_vcf_phased_no_call(self):
        """VCF parser should skip phased no-call '.|.'."""
        content = (
            "##fileformat=VCFv4.2\n"
            "#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\tFORMAT\tSAMPLE\n"
            "1\t100\trs123\tA\tG\t.\tPASS\tNS=1\tGT\t.|.\n"
            "1\t200\trs456\tC\tT\t.\tPASS\tNS=1\tGT\t0/1\n"
        )
        bio = BytesIO(content.encode("utf-8"))
        snps = parse_vcf(bio)
        assert "rs123" not in snps
        assert "rs456" in snps

    def test_23andme_empty_genotype_skipped(self):
        """23andMe parser should skip empty genotype fields."""
        content = (
            "# 23andMe data\n"
            "# rsid\tchromosome\tposition\tgenotype\n"
            "rs4477212\t1\t82154\t\n"
            "rs3094315\t1\t752566\tAG\n"
        )
        bio = BytesIO(content.encode("utf-8"))
        snps = parse_23andme(bio)
        assert "rs4477212" not in snps
        assert "rs3094315" in snps
        assert len(snps) == 1

    def test_myheritage_empty_result_skipped(self):
        """MyHeritage parser should skip empty result fields."""
        content = (
            "RSID,CHROMOSOME,POSITION,RESULT\n"
            "rs4477212,1,82154,\n"
            "rs3094315,1,752566,AG\n"
        )
        bio = BytesIO(content.encode("utf-8"))
        snps = parse_myheritage(bio)
        assert "rs4477212" not in snps
        assert "rs3094315" in snps


# ===================================================================
# 15. Return Value Structure Tests
# ===================================================================

class TestReturnValueStructure:
    """Verify that all parsers return the expected data structures."""

    @pytest.mark.parametrize("parser_func,sample_path", [
        (parse_23andme, SAMPLE_23ANDME),
        (parse_ancestry, SAMPLE_ANCESTRY),
        (parse_myheritage, SAMPLE_MYHERITAGE_QUOTED),
        (parse_vcf, SAMPLE_VCF),
    ])
    def test_parser_returns_dict(self, parser_func, sample_path):
        """All parsers should return a dict."""
        result = parser_func(str(sample_path))
        assert isinstance(result, dict)

    @pytest.mark.parametrize("parser_func,sample_path", [
        (parse_23andme, SAMPLE_23ANDME),
        (parse_ancestry, SAMPLE_ANCESTRY),
        (parse_myheritage, SAMPLE_MYHERITAGE_QUOTED),
        (parse_vcf, SAMPLE_VCF),
    ])
    def test_parser_keys_are_strings(self, parser_func, sample_path):
        """All dict keys (rsids) should be strings."""
        result = parser_func(str(sample_path))
        for key in result:
            assert isinstance(key, str)

    @pytest.mark.parametrize("parser_func,sample_path", [
        (parse_23andme, SAMPLE_23ANDME),
        (parse_ancestry, SAMPLE_ANCESTRY),
        (parse_myheritage, SAMPLE_MYHERITAGE_QUOTED),
        (parse_vcf, SAMPLE_VCF),
    ])
    def test_parser_values_are_strings(self, parser_func, sample_path):
        """All dict values (genotypes) should be strings."""
        result = parser_func(str(sample_path))
        for value in result.values():
            assert isinstance(value, str)

    @pytest.mark.parametrize("parser_func,sample_path", [
        (parse_23andme, SAMPLE_23ANDME),
        (parse_ancestry, SAMPLE_ANCESTRY),
        (parse_myheritage, SAMPLE_MYHERITAGE_QUOTED),
        (parse_vcf, SAMPLE_VCF),
    ])
    def test_parser_rsids_start_with_valid_prefix(self, parser_func, sample_path):
        """All rsids should start with 'rs', 'i', or 'VG'."""
        result = parser_func(str(sample_path))
        for key in result:
            assert key.startswith("rs") or key.startswith("i") or key.startswith("VG"), (
                f"Unexpected rsid prefix: {key}"
            )

    @pytest.mark.parametrize("parser_func,sample_path", [
        (parse_23andme, SAMPLE_23ANDME),
        (parse_ancestry, SAMPLE_ANCESTRY),
        (parse_myheritage, SAMPLE_MYHERITAGE_QUOTED),
        (parse_vcf, SAMPLE_VCF),
    ])
    def test_parser_genotypes_are_nonempty(self, parser_func, sample_path):
        """All genotype values should be non-empty strings."""
        result = parser_func(str(sample_path))
        for value in result.values():
            assert len(value) > 0

    @pytest.mark.parametrize("validator_func,sample_path", [
        (validate_23andme_format, SAMPLE_23ANDME),
        (validate_ancestry_format, SAMPLE_ANCESTRY),
        (validate_myheritage_format, SAMPLE_MYHERITAGE_QUOTED),
        (validate_vcf_format, SAMPLE_VCF),
    ])
    def test_validator_returns_tuple(self, validator_func, sample_path):
        """All validators should return a 2-tuple of (bool, str)."""
        result = validator_func(str(sample_path))
        assert isinstance(result, tuple)
        assert len(result) == 2
        assert isinstance(result[0], bool)
        assert isinstance(result[1], str)


# ===================================================================
# 16. File I/O and tmp_path Tests
# ===================================================================

class TestFileIOEdgeCases:
    """Test file I/O edge cases using tmp_path."""

    def test_23andme_from_tmp_file(self, tmp_path, valid_23andme_content):
        """parse_23andme should work with a file created in tmp_path."""
        test_file = tmp_path / "test_23andme.txt"
        test_file.write_text(valid_23andme_content, encoding="utf-8")
        snps = parse_23andme(str(test_file))
        assert len(snps) == 11

    def test_ancestry_from_tmp_file(self, tmp_path, valid_ancestry_content):
        """parse_ancestry should work with a file created in tmp_path."""
        test_file = tmp_path / "test_ancestry.txt"
        test_file.write_text(valid_ancestry_content, encoding="utf-8")
        snps = parse_ancestry(str(test_file))
        assert len(snps) == 11

    def test_myheritage_from_tmp_file(self, tmp_path, valid_myheritage_content):
        """parse_myheritage should work with a file created in tmp_path."""
        test_file = tmp_path / "test_myheritage.csv"
        test_file.write_text(valid_myheritage_content, encoding="utf-8")
        snps = parse_myheritage(str(test_file))
        assert len(snps) == 11

    def test_vcf_from_tmp_file(self, tmp_path, valid_vcf_content):
        """parse_vcf should work with a file created in tmp_path."""
        test_file = tmp_path / "test.vcf"
        test_file.write_text(valid_vcf_content, encoding="utf-8")
        snps = parse_vcf(str(test_file))
        assert len(snps) > 0

    def test_detect_format_from_tmp_file(self, tmp_path, valid_vcf_content):
        """detect_format should work with a file created in tmp_path."""
        test_file = tmp_path / "test.vcf"
        test_file.write_text(valid_vcf_content, encoding="utf-8")
        assert detect_format(str(test_file)) == "vcf"
