#!/usr/bin/env python3
"""
Regenerate ALL sample data files to include the ACTUAL rsIDs from carrier_panel.json
and trait_snps.json so the Tortit app can analyze them properly.
"""

import json
import random
import os
from pathlib import Path
from datetime import datetime

# Set seed for reproducibility but still get variety
random.seed(42)

# Paths
BASE_DIR = Path(r"C:\Users\t2tec\Tortit")
DATA_DIR = BASE_DIR / "data"
SAMPLE_DIR = BASE_DIR / "sample_data"

def load_json(filepath):
    with open(filepath, 'r', encoding='utf-8') as f:
        return json.load(f)

def generate_filler_rsids(count=100):
    """Generate common filler rsIDs that look realistic."""
    filler = []
    # Common rsIDs that are often in DTC tests but not in our panels
    common_prefixes = [1000, 2000, 3000, 4000, 5000, 6000, 7000, 8000, 9000]
    for i in range(count):
        prefix = random.choice(common_prefixes)
        filler.append(f"rs{prefix + random.randint(1, 999)}")
    return list(set(filler))  # Remove duplicates

def get_genotype_for_disease(disease, profile_type):
    """
    Generate genotype based on profile type.
    profile_type: 'healthy', 'carrier', 'mixed', 'affected_some'
    """
    ref = disease['reference_allele']
    path = disease['pathogenic_allele']

    if profile_type == 'healthy':
        # 90% homozygous reference, 10% carrier
        if random.random() < 0.90:
            return ref + ref
        else:
            return ref + path if random.random() < 0.5 else path + ref
    elif profile_type == 'carrier':
        # 60% carrier, 30% homozygous reference, 10% affected
        r = random.random()
        if r < 0.60:
            return ref + path if random.random() < 0.5 else path + ref
        elif r < 0.90:
            return ref + ref
        else:
            return path + path
    elif profile_type == 'affected_some':
        # 20% affected, 40% carrier, 40% reference
        r = random.random()
        if r < 0.20:
            return path + path
        elif r < 0.60:
            return ref + path if random.random() < 0.5 else path + ref
        else:
            return ref + ref
    else:  # mixed
        # Random distribution
        r = random.random()
        if r < 0.70:
            return ref + ref
        elif r < 0.95:
            return ref + path if random.random() < 0.5 else path + ref
        else:
            return path + path

def get_genotype_for_trait(trait, variation_seed):
    """Generate genotype from available phenotype_map genotypes with variation."""
    available_genotypes = list(trait['phenotype_map'].keys())

    # Use variation_seed to get different distributions per file
    random.seed(variation_seed + hash(trait['rsid']))
    genotype = random.choice(available_genotypes)
    random.seed()  # Reset seed

    return genotype

def get_filler_genotype():
    """Generate a random genotype for filler SNPs."""
    alleles = ['A', 'C', 'G', 'T']
    a1 = random.choice(alleles)
    a2 = random.choice(alleles)
    return a1 + a2

def generate_23andme_file(filepath, diseases, traits, filler_rsids, profile_type, file_seed):
    """Generate a 23andMe format file."""
    random.seed(file_seed)

    lines = [
        "# This data file generated by 23andMe at: " + datetime.now().strftime("%a %b %d %H:%M:%S %Y"),
        "#",
        "# This file contains raw genotype data, including data that is not used in 23andMe reports.",
        "# This data has undergone a general quality review however only a subset of markers have been ",
        "# individually validated for accuracy. As such, this data is suitable only for research, ",
        "# educational, and informational use and not for medical or other use.",
        "#",
        "# Below is a text version of your data. Fields are TAB-separated",
        "# Each line corresponds to a single SNP. For each SNP, we provide its identifier ",
        "# (an rsid or an internal id), its location on the reference human genome, and the ",
        "# genotype call oriented with respect to the plus strand on the human reference sequence.",
        "#",
        "# rsid\tchromosome\tposition\tgenotype"
    ]

    position = 752566

    # Add all disease SNPs
    for disease in diseases:
        genotype = get_genotype_for_disease(disease, profile_type)
        chrom = random.randint(1, 22)
        lines.append(f"{disease['rsid']}\t{chrom}\t{position}\t{genotype}")
        position += random.randint(100, 500)

    # Add all trait SNPs
    for trait in traits:
        genotype = get_genotype_for_trait(trait, file_seed)
        chrom = trait.get('chromosome', str(random.randint(1, 22)))
        lines.append(f"{trait['rsid']}\t{chrom}\t{position}\t{genotype}")
        position += random.randint(100, 500)

    # Add filler SNPs
    for rsid in filler_rsids:
        genotype = get_filler_genotype()
        chrom = random.randint(1, 22)
        lines.append(f"{rsid}\t{chrom}\t{position}\t{genotype}")
        position += random.randint(100, 500)

    with open(filepath, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines))

    print(f"Generated: {filepath}")

def generate_ancestry_file(filepath, diseases, traits, filler_rsids, profile_type, file_seed):
    """Generate an AncestryDNA format file."""
    random.seed(file_seed)

    lines = [
        "#AncestryDNA raw data download",
        "#This file was generated by AncestryDNA",
        "#Data was collected using AncestryDNA array version: V2.0",
        "#Data is formatted according to AncestryDNA specifications",
        "#",
        "#This data has undergone quality review by AncestryDNA but may contain errors",
        "#This data is for informational purposes only and should not be used for medical decisions",
        "#",
        "#rsid\tchromosome\tposition\tallele1\tallele2"
    ]

    position = 752566

    # Add all disease SNPs
    for disease in diseases:
        genotype = get_genotype_for_disease(disease, profile_type)
        chrom = random.randint(1, 22)
        a1, a2 = genotype[0], genotype[1]
        lines.append(f"{disease['rsid']}\t{chrom}\t{position}\t{a1}\t{a2}")
        position += random.randint(100, 500)

    # Add all trait SNPs
    for trait in traits:
        genotype = get_genotype_for_trait(trait, file_seed)
        chrom = trait.get('chromosome', str(random.randint(1, 22)))
        a1, a2 = genotype[0], genotype[1]
        lines.append(f"{trait['rsid']}\t{chrom}\t{position}\t{a1}\t{a2}")
        position += random.randint(100, 500)

    # Add filler SNPs
    for rsid in filler_rsids:
        genotype = get_filler_genotype()
        chrom = random.randint(1, 22)
        a1, a2 = genotype[0], genotype[1]
        lines.append(f"{rsid}\t{chrom}\t{position}\t{a1}\t{a2}")
        position += random.randint(100, 500)

    with open(filepath, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines))

    print(f"Generated: {filepath}")

def generate_myheritage_file(filepath, diseases, traits, filler_rsids, profile_type, file_seed, quoted=True):
    """Generate a MyHeritage format CSV file."""
    random.seed(file_seed)

    lines = ["RSID,CHROMOSOME,POSITION,RESULT"]

    position = 752566

    def format_value(val, quoted):
        if quoted:
            return f'"{val}"'
        return str(val)

    # Add all disease SNPs
    for disease in diseases:
        genotype = get_genotype_for_disease(disease, profile_type)
        chrom = random.randint(1, 22)
        if quoted:
            lines.append(f'"{disease["rsid"]}","{chrom}","{position}","{genotype}"')
        else:
            lines.append(f'{disease["rsid"]},{chrom},{position},{genotype}')
        position += random.randint(100, 500)

    # Add all trait SNPs
    for trait in traits:
        genotype = get_genotype_for_trait(trait, file_seed)
        chrom = trait.get('chromosome', str(random.randint(1, 22)))
        if quoted:
            lines.append(f'"{trait["rsid"]}","{chrom}","{position}","{genotype}"')
        else:
            lines.append(f'{trait["rsid"]},{chrom},{position},{genotype}')
        position += random.randint(100, 500)

    # Add filler SNPs
    for rsid in filler_rsids:
        genotype = get_filler_genotype()
        chrom = random.randint(1, 22)
        if quoted:
            lines.append(f'"{rsid}","{chrom}","{position}","{genotype}"')
        else:
            lines.append(f'{rsid},{chrom},{position},{genotype}')
        position += random.randint(100, 500)

    with open(filepath, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines))

    print(f"Generated: {filepath}")

def genotype_to_vcf_gt(genotype, ref, alt):
    """Convert genotype string to VCF GT format."""
    a1, a2 = genotype[0], genotype[1]

    # Determine allele indices (0 = ref, 1 = alt)
    def allele_index(a):
        if a == ref:
            return '0'
        else:
            return '1'

    return f"{allele_index(a1)}/{allele_index(a2)}"

def generate_vcf_file(filepath, diseases, traits, filler_rsids, profile_type, file_seed):
    """Generate a VCF format file."""
    random.seed(file_seed)

    today = datetime.now().strftime("%Y%m%d")

    lines = [
        "##fileformat=VCFv4.2",
        f"##fileDate={today}",
        "##source=TortitSampleGenerator",
        "##reference=GRCh38",
        '##INFO=<ID=NS,Number=1,Type=Integer,Description="Number of Samples With Data">',
        '##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">',
        '##FORMAT=<ID=GQ,Number=1,Type=Integer,Description="Genotype Quality">',
        '##FORMAT=<ID=DP,Number=1,Type=Integer,Description="Read Depth">',
        "#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\tFORMAT\tSAMPLE"
    ]

    position = 752566

    # Add all disease SNPs
    for disease in diseases:
        genotype = get_genotype_for_disease(disease, profile_type)
        ref = disease['reference_allele']
        alt = disease['pathogenic_allele']
        gt = genotype_to_vcf_gt(genotype, ref, alt)
        chrom = random.randint(1, 22)
        gq = random.randint(90, 99)
        dp = random.randint(30, 100)
        lines.append(f"{chrom}\t{position}\t{disease['rsid']}\t{ref}\t{alt}\t.\tPASS\tNS=1\tGT:GQ:DP\t{gt}:{gq}:{dp}")
        position += random.randint(100, 500)

    # Add all trait SNPs
    for trait in traits:
        genotype = get_genotype_for_trait(trait, file_seed)
        ref = trait['alleles']['ref']
        alt = trait['alleles']['alt']
        gt = genotype_to_vcf_gt(genotype, ref, alt)
        chrom = trait.get('chromosome', str(random.randint(1, 22)))
        gq = random.randint(90, 99)
        dp = random.randint(30, 100)
        lines.append(f"{chrom}\t{position}\t{trait['rsid']}\t{ref}\t{alt}\t.\tPASS\tNS=1\tGT:GQ:DP\t{gt}:{gq}:{dp}")
        position += random.randint(100, 500)

    # Add filler SNPs
    for rsid in filler_rsids:
        genotype = get_filler_genotype()
        ref = genotype[0]
        alt = genotype[1] if genotype[1] != genotype[0] else random.choice([a for a in 'ACGT' if a != ref])
        gt = genotype_to_vcf_gt(genotype, ref, alt)
        chrom = random.randint(1, 22)
        gq = random.randint(90, 99)
        dp = random.randint(30, 100)
        lines.append(f"{chrom}\t{position}\t{rsid}\t{ref}\t{alt}\t.\tPASS\tNS=1\tGT:GQ:DP\t{gt}:{gq}:{dp}")
        position += random.randint(100, 500)

    with open(filepath, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines))

    print(f"Generated: {filepath}")

def main():
    print("Loading carrier panel and trait SNPs...")
    diseases = load_json(DATA_DIR / "carrier_panel.json")
    traits = load_json(DATA_DIR / "trait_snps.json")

    print(f"Loaded {len(diseases)} disease SNPs")
    print(f"Loaded {len(traits)} trait SNPs")

    filler_rsids = generate_filler_rsids(100)
    print(f"Generated {len(filler_rsids)} filler rsIDs")

    total_snps = len(diseases) + len(traits) + len(filler_rsids)
    print(f"Each file will have {total_snps} SNPs")

    # Ensure directories exist
    for subdir in ['23andme', 'ancestry', 'myheritage', 'vcf']:
        (SAMPLE_DIR / subdir).mkdir(parents=True, exist_ok=True)

    # Profile types for variety
    profiles_23andme = ['healthy', 'carrier', 'mixed', 'affected_some', 'mixed', 'carrier']
    profiles_ancestry = ['healthy', 'carrier', 'mixed', 'affected_some', 'healthy', 'carrier']
    profiles_myheritage = ['healthy', 'carrier', 'mixed', 'affected_some', 'healthy', 'carrier']
    profiles_vcf = ['healthy', 'carrier', 'mixed', 'affected_some', 'mixed']

    # Generate 23andMe files (6 files)
    print("\n=== Generating 23andMe files ===")
    files_23andme = [
        "sample_23andme_v3_male_01.txt",
        "sample_23andme_v4_female_01.txt",
        "sample_23andme_v5_male_02.txt",
        "sample_23andme_v4_female_02.txt",
        "sample_23andme_v5_mixed_01.txt",
        "sample_23andme_v3_carrier_01.txt"
    ]
    for i, filename in enumerate(files_23andme):
        filepath = SAMPLE_DIR / "23andme" / filename
        generate_23andme_file(filepath, diseases, traits, filler_rsids, profiles_23andme[i], file_seed=i*1000)

    # Generate AncestryDNA files (6 files)
    print("\n=== Generating AncestryDNA files ===")
    files_ancestry = [
        "sample_ancestry_v1_male_01.txt",
        "sample_ancestry_v1_female_01.txt",
        "sample_ancestry_v2_male_01.txt",
        "sample_ancestry_v2_female_01.txt",
        "sample_ancestry_v1_mixed_01.txt",
        "sample_ancestry_v2_diverse_01.txt"
    ]
    for i, filename in enumerate(files_ancestry):
        filepath = SAMPLE_DIR / "ancestry" / filename
        generate_ancestry_file(filepath, diseases, traits, filler_rsids, profiles_ancestry[i], file_seed=i*2000)

    # Generate MyHeritage files (6 files - 4 quoted, 2 unquoted)
    print("\n=== Generating MyHeritage files ===")
    files_myheritage = [
        ("sample1_quoted.csv", True),
        ("sample2_quoted.csv", True),
        ("sample3_quoted.csv", True),
        ("sample4_quoted.csv", True),
        ("sample5_unquoted.csv", False),
        ("sample6_unquoted.csv", False)
    ]
    for i, (filename, quoted) in enumerate(files_myheritage):
        filepath = SAMPLE_DIR / "myheritage" / filename
        generate_myheritage_file(filepath, diseases, traits, filler_rsids, profiles_myheritage[i], file_seed=i*3000, quoted=quoted)

    # Generate VCF files (5 files)
    print("\n=== Generating VCF files ===")
    files_vcf = [
        "sample_vcf_wgs_male_01.vcf",
        "sample_vcf_wgs_female_01.vcf",
        "sample_vcf_exome_01.vcf",
        "sample_vcf_panel_01.vcf",
        "sample_vcf_clinical_01.vcf"
    ]
    for i, filename in enumerate(files_vcf):
        filepath = SAMPLE_DIR / "vcf" / filename
        generate_vcf_file(filepath, diseases, traits, filler_rsids, profiles_vcf[i], file_seed=i*4000)

    # Verification
    print("\n=== Verification ===")

    # Check for CF rsID (rs75030207)
    test_file = SAMPLE_DIR / "23andme" / "sample_23andme_v3_male_01.txt"
    with open(test_file, 'r') as f:
        content = f.read()
        if 'rs75030207' in content:
            print(f"[OK] rs75030207 (CF) found in {test_file.name}")
        else:
            print(f"[FAIL] rs75030207 (CF) NOT found in {test_file.name}")

    # Check for eye color rsID (rs12913832)
    if 'rs12913832' in content:
        print(f"[OK] rs12913832 (eye color) found in {test_file.name}")
    else:
        print(f"[FAIL] rs12913832 (eye color) NOT found in {test_file.name}")

    # Count SNPs in a file
    snp_count = len([line for line in content.split('\n') if line and not line.startswith('#')])
    print(f"\nTotal SNPs in sample file: {snp_count}")

    print("\n=== Generation Complete ===")
    print(f"Generated {len(files_23andme)} 23andMe files")
    print(f"Generated {len(files_ancestry)} AncestryDNA files")
    print(f"Generated {len(files_myheritage)} MyHeritage files")
    print(f"Generated {len(files_vcf)} VCF files")
    print(f"\nTotal files: {len(files_23andme) + len(files_ancestry) + len(files_myheritage) + len(files_vcf)}")

if __name__ == "__main__":
    main()
