/**
 * Privacy Verification E2E Tests
 *
 * Verifies Mergenix's core privacy promise: "Your DNA never leaves your device."
 *
 * All genetic analysis runs client-side in Web Workers. These tests use
 * Playwright's network interception layer to prove that NO genetic data
 * is ever transmitted to any server during the analysis workflow.
 *
 * Strategy: Allowlist mode
 *   - Before analysis, install a page.on('request') listener that captures
 *     every outgoing network request.
 *   - After analysis completes, assert that zero captured requests contain
 *     genetic data (rsIDs, genotype strings, large POST bodies).
 *   - Assert that zero requests were made to third-party tracking domains.
 *
 * 5 test scenarios — all P0 (privacy is a core product guarantee).
 *
 * @see apps/web/hooks/use-genetics-worker.ts  — Web Worker bridge
 * @see packages/genetics-engine/src/worker    — Worker implementation
 */

import { test, expect } from '@playwright/test';
import type { Request } from '@playwright/test';

// ── Privacy Test DNA Fixture ─────────────────────────────────────────────
//
// A minimal 23andMe-format file (~50 SNPs) with recognisable rsIDs that
// the genetics engine can parse. The rsIDs here match the demo dataset so
// the engine produces valid results — which maximises code coverage of the
// worker path without requiring a live backend.
//
// IMPORTANT: These exact rsID strings are used as "canary values" — if any
// of them appear in a network request body the privacy tests will fail.
// Do NOT change the rsIDs without also updating CANARY_RSIDS below.

const PRIVACY_TEST_DNA_CONTENT = [
  '# This data file generated by 23andMe at: Thu Jan 01 00:00:00 2026',
  '#',
  '# rsid\tchromosome\tposition\tgenotype',
  'rs113993960\t7\t117559590\tDI',
  'rs387906309\t15\t72346580\tCT',
  'rs334\t11\t5248232\tAT',
  'rs28942078\t19\t11241241\tCT',
  'rs137854473\t15\t48937836\tAG',
  'rs1050828\tX\t154536002\tCT',
  'rs137852339\tX\t154929412\tAG',
  'rs5030858\t12\t103311124\tCT',
  'rs76763715\t1\t155237654\tAG',
  'rs1554286580\t5\t70924941\tCC',
  'rs28940893\t17\t3387396\tGG',
  'rs113993962\t15\t91350441\tCC',
  'rs104942698\t9\t111658588\tCC',
  'rs12913832\t15\t28365618\tAG',
  'rs1805007\t16\t89919709\tCT',
  'rs17822931\t16\t48258198\tCC',
  'rs12203592\t6\t396321\tCT',
  'rs4988235\t2\t136616754\tCT',
  'rs713598\t7\t141673345\tGC',
  'rs4481887\t1\t248039451\tGA',
  'rs72921001\t11\t6963888\tCT',
  'rs1815739\t11\t66560624\t--',
  'rs762551\t15\t75041917\tAA',
  'rs75030207\t10\t94942290\tCT',
  'rs76173977\t10\t94981296\tAG',
].join('\n');

/**
 * Canary rsID values embedded in the test DNA fixture.
 * Any network request body containing these strings is a privacy violation.
 */
const CANARY_RSIDS = [
  'rs113993960',
  'rs387906309',
  'rs334',
  'rs28942078',
  'rs137854473',
  'rs12913832',
  'rs1805007',
  'rs4988235',
];

/**
 * Canary genotype substrings. Short strings like "AT", "CT" are too common
 * (they appear in URLs, headers, etc.) so we only flag multi-genotype
 * patterns that unambiguously indicate a genetic data payload.
 */
const CANARY_GENOTYPE_PATTERNS = [
  // Tab-separated SNP record pattern: rsid \t chr \t pos \t genotype
  /rs\d+\t\d+\t\d+\t[ACGTDI-]{1,2}/,
  // Batch of rsIDs — 3+ rsIDs in the same body = genetic payload
  /(rs\d+.*){3,}/,
];

/**
 * Third-party analytics / tracking domains that must NOT receive any
 * requests during the analysis workflow.
 */
const BLOCKED_THIRD_PARTY_DOMAINS = [
  'google-analytics.com',
  'analytics.google.com',
  'googletagmanager.com',
  'mixpanel.com',
  'segment.com',
  'segment.io',
  'amplitude.com',
  'fullstory.com',
  'hotjar.com',
  'clarity.ms',
  'intercom.io',
  'intercom.com',
  'heap.io',
  'heap.com',
  'sentry.io',  // Error reporter — tested separately below
  'datadog-browser-agent',
  'newrelic.com',
  'bugsnag.com',
  'rollbar.com',
  'logrocket.com',
  'facebook.com/tr',
  'doubleclick.net',
];

// ── Helpers ──────────────────────────────────────────────────────────────

/**
 * Returns true if the request body contains any recognisable genetic data.
 *
 * Checks:
 * 1. The body contains one of the canary rsID strings.
 * 2. The body matches a tab-separated SNP record pattern.
 * 3. The body contains 3 or more rsID references (batch upload).
 */
function bodyContainsGeneticData(body: string): boolean {
  for (const rsid of CANARY_RSIDS) {
    if (body.includes(rsid)) return true;
  }
  for (const pattern of CANARY_GENOTYPE_PATTERNS) {
    if (pattern.test(body)) return true;
  }
  return false;
}

/**
 * Returns true if the request URL's hostname matches a blocked third-party
 * analytics/tracking domain.
 */
function isBlockedThirdPartyDomain(url: string): boolean {
  try {
    const { hostname } = new URL(url);
    return BLOCKED_THIRD_PARTY_DOMAINS.some((domain) => hostname.includes(domain));
  } catch {
    return false;
  }
}

/**
 * Collect captured privacy-violating requests and return a formatted
 * diagnostic string for assertion failure messages.
 */
function formatViolations(violations: { url: string; method: string; body: string }[]): string {
  return violations
    .map(
      (v, i) =>
        `  Violation ${i + 1}: [${v.method}] ${v.url}\n` +
        `    Body excerpt: ${v.body.slice(0, 300)}`,
    )
    .join('\n');
}

/**
 * Upload the privacy test DNA fixture to both parent file inputs.
 * Returns after both files are set (upload is synchronous in Playwright).
 */
async function uploadPrivacyTestFiles(page: import('@playwright/test').Page): Promise<void> {
  const fileInputs = page.locator('input[type="file"]');
  await expect(fileInputs).toHaveCount(2);

  const filePayload = {
    name: 'privacy-test-parent.txt',
    mimeType: 'text/plain',
    buffer: Buffer.from(PRIVACY_TEST_DNA_CONTENT),
  };

  await fileInputs.nth(0).setInputFiles({ ...filePayload, name: 'privacy-test-parentA.txt' });
  await fileInputs.nth(1).setInputFiles({ ...filePayload, name: 'privacy-test-parentB.txt' });
}

// ── Test Suite ──────────────────────────────────────────────────────────

test.describe('Privacy — Zero Network Calls During Analysis', () => {
  /**
   * Test 1 (P0): The core privacy claim.
   *
   * Uploads real DNA files and starts the Web Worker analysis pipeline.
   * Monitors ALL outgoing POST/PUT/PATCH requests to the app's own API
   * (/api/* and the configured NEXT_PUBLIC_API_URL backend).
   * Asserts that none of them contain genetic data in the request body.
   */
  test('1. free-tier analysis sends no genetic data to server', async ({ page }) => {
    test.slow(); // Worker analysis takes up to 30s on slow CI machines

    // ── Phase 1: Set up network monitoring BEFORE navigation ────────────
    const geneticDataViolations: { url: string; method: string; body: string }[] = [];

    page.on('request', (request: Request) => {
      const method = request.method();
      // Only inspect mutation requests — GET/HEAD/OPTIONS never carry user data
      if (!['POST', 'PUT', 'PATCH'].includes(method)) return;

      const url = request.url();
      // Only inspect requests to the app's own origin or backend API
      const isOwnOrigin =
        url.startsWith('http://localhost:3000') ||
        url.startsWith('http://localhost:8000') ||
        url.includes('/api/');

      if (!isOwnOrigin) return;

      const body = request.postData() ?? '';
      if (bodyContainsGeneticData(body)) {
        geneticDataViolations.push({ url, method, body });
      }
    });

    // ── Phase 2: Navigate and upload DNA files ───────────────────────────
    await page.goto('/analysis');
    await expect(
      page.getByRole('heading', { name: /genetic analysis/i }),
    ).toBeVisible();

    await uploadPrivacyTestFiles(page);

    // ── Phase 3: Start analysis ──────────────────────────────────────────
    const startButton = page.getByRole('button', { name: /start analysis/i });
    await expect(startButton).toBeVisible();
    await startButton.click();

    // Wait for either completion (results heading) or the progress bar to
    // appear and then resolve. Give up to 30s for the worker to finish.
    await Promise.race([
      page
        .getByRole('heading', { name: /analysis results/i, level: 2 })
        .waitFor({ timeout: 30_000 }),
      // Fallback: if the app shows an error, the progressbar disappears
      page
        .getByRole('progressbar', { name: /analysis progress/i })
        .waitFor({ state: 'detached', timeout: 30_000 }),
    ]).catch(() => {
      // If neither resolves within 30s, the test will still pass if no
      // violations were captured — the assertion below is the real gate.
    });

    // ── Phase 4: Assert no genetic data left the browser ─────────────────
    expect(
      geneticDataViolations,
      `PRIVACY VIOLATION: ${geneticDataViolations.length} request(s) contained genetic data:\n` +
        formatViolations(geneticDataViolations),
    ).toHaveLength(0);
  });

  /**
   * Test 2 (P0): No analytics or tracking beacons during analysis.
   *
   * Even if the app has analytics integrations, they must not fire while
   * genetic data is being processed in the worker.
   */
  test('2. no analytics or tracking beacons during analysis', async ({ page }) => {
    test.slow();

    // ── Phase 1: Monitor all outgoing requests ───────────────────────────
    const trackingRequests: { url: string; method: string }[] = [];

    page.on('request', (request: Request) => {
      const url = request.url();
      if (isBlockedThirdPartyDomain(url)) {
        trackingRequests.push({ url, method: request.method() });
      }
    });

    // ── Phase 2: Navigate and trigger analysis via demo mode ─────────────
    // We use demo mode here because it exercises the same result-rendering
    // code paths without requiring a running backend for file parsing.
    await page.goto('/analysis');
    await expect(
      page.getByRole('heading', { name: /genetic analysis/i }),
    ).toBeVisible();

    const demoButton = page.getByRole('button', { name: /try demo analysis/i });
    await expect(demoButton).toBeVisible();
    await demoButton.click();

    // Wait for results to render — this exercises the full analysis UI
    await expect(
      page.getByRole('heading', { name: /analysis results/i, level: 2 }),
    ).toBeVisible({ timeout: 15_000 });

    // ── Phase 3: Assert zero tracking requests ───────────────────────────
    expect(
      trackingRequests,
      `PRIVACY VIOLATION: ${trackingRequests.length} request(s) to third-party tracking domain(s):\n` +
        trackingRequests.map((r) => `  [${r.method}] ${r.url}`).join('\n'),
    ).toHaveLength(0);
  });

  /**
   * Test 3 (P0): Web Worker does not trigger fetch/XHR during processing.
   *
   * The worker runs in an isolated thread. This test verifies that the
   * ONLY network activity during file upload and analysis is the initial
   * page load and any pre-existing auth/session API calls — not any
   * request that carries DNA data.
   *
   * Implementation note: We capture all requests AFTER the page has
   * settled (after the initial page load), then trigger file upload and
   * analysis. Any new POST/PUT/PATCH to the app's API is unexpected.
   */
  test('3. Web Worker does not make fetch calls during processing', async ({ page }) => {
    test.slow();

    // Navigate first and wait for initial page load to settle
    await page.goto('/analysis');
    await expect(
      page.getByRole('heading', { name: /genetic analysis/i }),
    ).toBeVisible();

    // Allow some time for auth-store initialization requests to complete
    // before we start the "clean" monitoring window.
    await page.waitForTimeout(1_500);

    // ── Phase 2: Start clean network monitoring ──────────────────────────
    const unexpectedApiRequests: { url: string; method: string; body: string }[] = [];

    page.on('request', (request: Request) => {
      const method = request.method();
      if (!['POST', 'PUT', 'PATCH'].includes(method)) return;

      const url = request.url();
      // Watch for any POST to app backend — this should NOT happen during analysis
      const isApiRequest =
        url.includes('/api/') ||
        url.startsWith('http://localhost:8000') ||
        url.includes('/analysis/') ||
        url.includes('/genetics/');

      if (isApiRequest) {
        unexpectedApiRequests.push({
          url,
          method,
          body: request.postData() ?? '',
        });
      }
    });

    // ── Phase 3: Upload files and trigger analysis ───────────────────────
    await uploadPrivacyTestFiles(page);

    const startButton = page.getByRole('button', { name: /start analysis/i });
    await expect(startButton).toBeVisible();
    await startButton.click();

    // Wait for analysis to complete or error out
    await Promise.race([
      page
        .getByRole('heading', { name: /analysis results/i, level: 2 })
        .waitFor({ timeout: 30_000 }),
      page
        .getByRole('progressbar', { name: /analysis progress/i })
        .waitFor({ state: 'detached', timeout: 30_000 }),
    ]).catch(() => {});

    // ── Phase 4: Assert no unexpected API calls were made ─────────────────
    // Filter out any known-legitimate calls (e.g. analysis/results for saving)
    // We care specifically about calls during the ANALYSIS phase, not afterward.
    // The /analysis/results endpoint is only called when the user clicks Save.
    const geneticsApiViolations = unexpectedApiRequests.filter(
      (r) => !r.url.includes('/analysis/results'),
    );

    expect(
      geneticsApiViolations,
      `PRIVACY VIOLATION: ${geneticsApiViolations.length} unexpected API call(s) during analysis:\n` +
        formatViolations(geneticsApiViolations),
    ).toHaveLength(0);
  });

  /**
   * Test 4 (P0): Error reporting does not include genetic data.
   *
   * If an error occurs during analysis (e.g. malformed file), the app
   * may send an error report to an error tracking service (e.g. Sentry).
   * This test verifies that no such report contains rsIDs or genotype data.
   *
   * We intercept any request to known error-reporting endpoints and inspect
   * the body for genetic content.
   */
  test('4. error reporting does not include genetic data', async ({ page }) => {
    // ── Phase 1: Intercept all error reporting requests ──────────────────
    const errorReportViolations: { url: string; body: string }[] = [];

    // Intercept Sentry and allow it (we check content, not block it)
    await page.route('**sentry.io**', async (route) => {
      const body = route.request().postData() ?? '';
      if (bodyContainsGeneticData(body)) {
        errorReportViolations.push({
          url: route.request().url(),
          body,
        });
      }
      // Allow the request to proceed normally so we don't break error reporting
      await route.continue();
    });

    // Also watch for generic error payloads to any endpoint
    const allErrorPayloads: { url: string; body: string }[] = [];
    page.on('request', (request: Request) => {
      const url = request.url();
      const method = request.method();
      if (method !== 'POST') return;

      // Look for error reporting patterns in any POST body
      const body = request.postData() ?? '';
      if (
        body.length > 0 &&
        (url.includes('error') || url.includes('log') || url.includes('report')) &&
        bodyContainsGeneticData(body)
      ) {
        allErrorPayloads.push({ url, body });
      }
    });

    // ── Phase 2: Trigger an analysis with a malformed file ───────────────
    await page.goto('/analysis');
    await expect(
      page.getByRole('heading', { name: /genetic analysis/i }),
    ).toBeVisible();

    // Upload one valid file and one malformed file to provoke an error
    const fileInputs = page.locator('input[type="file"]');
    await expect(fileInputs).toHaveCount(2);

    // Parent A: valid DNA file (to pass initial validation)
    await fileInputs.nth(0).setInputFiles({
      name: 'privacy-test-parentA.txt',
      mimeType: 'text/plain',
      buffer: Buffer.from(PRIVACY_TEST_DNA_CONTENT),
    });

    // Parent B: malformed content that will cause a parse error
    // It still contains rsID-like patterns so we can detect if they leak
    const malformedContent = [
      '# malformed DNA file',
      'rs12913832\tINVALID\tNOT_A_NUMBER\tXX',
      'rs1805007\t??\t??\t??',
      'NOT_AN_RSID\t1\t100\tAA',
      ...Array.from({ length: 10 }, (_, i) => `rs${100 + i}\t1\t${1000 + i}\tAA`),
    ].join('\n');

    await fileInputs.nth(1).setInputFiles({
      name: 'privacy-test-malformed.txt',
      mimeType: 'text/plain',
      buffer: Buffer.from(malformedContent),
    });

    // Try to start analysis (may show validation error immediately or during worker processing)
    const startButton = page.getByRole('button', { name: /start analysis/i });
    const startVisible = await startButton.isVisible().catch(() => false);
    if (startVisible) {
      await startButton.click();
    }

    // Wait for any error display or timeout
    await page
      .getByText(/error|invalid|failed/i)
      .first()
      .waitFor({ timeout: 15_000 })
      .catch(() => {});

    // Allow time for any async error reports to be dispatched
    await page.waitForTimeout(2_000);

    // ── Phase 3: Assert no genetic data in error reports ─────────────────
    expect(
      errorReportViolations,
      `PRIVACY VIOLATION: ${errorReportViolations.length} error report(s) to Sentry contained genetic data:\n` +
        errorReportViolations.map((r) => `  ${r.url}: ${r.body.slice(0, 200)}`).join('\n'),
    ).toHaveLength(0);

    expect(
      allErrorPayloads,
      `PRIVACY VIOLATION: ${allErrorPayloads.length} error report(s) to unknown endpoint(s) contained genetic data:\n` +
        allErrorPayloads.map((r) => `  ${r.url}: ${r.body.slice(0, 200)}`).join('\n'),
    ).toHaveLength(0);
  });

  /**
   * Test 5 (P0): Page unload does not beacon genetic data.
   *
   * navigator.sendBeacon() is commonly used for "fire and forget" analytics
   * on page unload. This test verifies that navigating away mid-analysis
   * does NOT send a beacon containing genetic content.
   *
   * Implementation: We use page.route() to intercept all POST requests
   * (sendBeacon uses POST), and also listen for 'requestfinished' to catch
   * any beacon that was sent during the unload event.
   */
  test('5. page unload does not beacon genetic data', async ({ page }) => {
    test.slow();

    // ── Phase 1: Set up beacon monitoring ───────────────────────────────
    const beaconViolations: { url: string; body: string }[] = [];

    // Intercept ALL POST requests to catch sendBeacon (which also uses POST)
    await page.route('**', async (route) => {
      const request = route.request();
      if (request.method() === 'POST') {
        const body = request.postData() ?? '';
        if (bodyContainsGeneticData(body)) {
          beaconViolations.push({
            url: request.url(),
            body,
          });
        }
      }
      await route.continue();
    });

    // Also capture via the lower-level 'request' event for completeness
    page.on('request', (request: Request) => {
      if (request.method() === 'POST') {
        const body = request.postData() ?? '';
        if (bodyContainsGeneticData(body)) {
          const existing = beaconViolations.find((v) => v.url === request.url());
          if (!existing) {
            beaconViolations.push({ url: request.url(), body });
          }
        }
      }
    });

    // ── Phase 2: Upload files and start analysis ─────────────────────────
    await page.goto('/analysis');
    await expect(
      page.getByRole('heading', { name: /genetic analysis/i }),
    ).toBeVisible();

    await uploadPrivacyTestFiles(page);

    const startButton = page.getByRole('button', { name: /start analysis/i });
    await expect(startButton).toBeVisible();
    await startButton.click();

    // Wait briefly for the worker to start processing (analysis in progress)
    const progressbar = page.getByRole('progressbar', { name: /analysis progress/i });
    await progressbar.waitFor({ timeout: 15_000 }).catch(() => {
      // If progressbar never appears, analysis might have completed very fast
      // or an error occurred — either way we continue to the navigation step
    });

    // ── Phase 3: Navigate away mid-analysis ──────────────────────────────
    // This triggers the page's unload / beforeunload handlers.
    // sendBeacon() calls made in these handlers will be captured above.
    await page.goto('/');

    // Allow time for any async beacons to complete after navigation
    await page.waitForTimeout(2_000);

    // ── Phase 4: Assert no genetic data was beaconed ──────────────────────
    expect(
      beaconViolations,
      `PRIVACY VIOLATION: ${beaconViolations.length} sendBeacon/POST request(s) contained genetic data on unload:\n` +
        beaconViolations.map((v) => `  [POST] ${v.url}\n  Body: ${v.body.slice(0, 300)}`).join('\n'),
    ).toHaveLength(0);
  });
});
